### ISSUE TITLE
Keyword is not found if preceded by Spanish question mark

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#1003]
## What did you expect to happen?
Keywords to be found regardless of they are preceded by a Spanish question mark or not.

## What happened instead?
Spanish questions start with an upside-down question mark attached to the first word of the sentence. Because of this question mark, the keyword is not recognized if it is at the beginning of a question.  

![schermafbeelding 2017-01-02 om 14 11 26](https://cloud.githubusercontent.com/assets/17744553/21589783/b4b72010-d0f5-11e6-8fe3-ccae56417d35.png)
![2](https://cloud.githubusercontent.com/assets/17744553/21589800/db7c3a82-d0f5-11e6-86a8-d274b9093890.png)

## How can we reproduce this behavior?
Start a sentence with a Spanish question mark, directly followed by your focus keyword. 

## Technical info

* Platform: WordPress
* Platform version: 4.7
* Yoast SEO version: 4.0.2

**Comment by terw-dan** [comment]
When solving this issue, please use the following branch: https://github.com/Yoast/YoastSEO.js/tree/issue1003-keyword-match-spanish-questionmark
