### ISSUE TITLE
Which file(s) do we enqueue?

### ISSUE THREAD

**Issue by beatelite** [Yoast/YoastSEO.js#1009]
## What did you expect to happen?
For the docs to at least let us know what file(s) from yoastseo to enqueue to get the basic example in the docs to work.

Is it app.js is it index.js? I've tried them all but notta. There's nothing in the dist folder which is where I'd expect to find it. Do I have to load all the NPM dependencies?

Trying to load the js to do on page analysis on the frontend of a wp page.

**Comment by terw-dan** [comment]
I would advise to follow the installation as described here: https://github.com/Yoast/YoastSEO.js

If you require YoastSEO in your project, you don't need to enqueue files manually. Using the app will enable you to run analysis, that can be required like this: `var App = require( "yoastseo" ).App;`

If you encounter issues implementing YoastSEO, please let us know. 

Regarding the dependencies, all dependencies are installed when you install YoastSEO.

**Comment by beatelite** [comment]
When you say require YoastSEO, you mean require the wp plugin or the YoastSEO.js? 

I do have the wp version required in my composer file but I was not able to get it to work.

**Comment by terw-dan** [comment]
In this case the YoastSEO.js. This works independently from the WordPress plugin, so you can integrate it on any platform you like.

**Comment by atimmer** [comment]
If you want to integrate YoastSEO.js directly you need to use a tool like [`browserify`] or [`webpack`] to compile everything down to a file the browser can actually execute. Because the browser doesn't know about `require` statements. This would be the preferred way to use YoastSEO.js.

[`browserify`]: http://browserify.org/
[`webpack`]: https://webpack.github.io/

**Comment by Djennez** [comment]
I am closing this thread due to inactivity.
