### ISSUE TITLE
Relevant words analysis does not handle tables correctly

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#1014]
## What did you expect to happen?
The prominent word analysis to not find word combinations of words from different cells. 

## What happened instead?
It did find word combinations consisting of words from different cells. The entire table seems to be viewed as one sentence (also see https://github.com/Yoast/YoastSEO.js/issues/820).

![schermafbeelding_2017-01-05_om_14_08_23](https://cloud.githubusercontent.com/assets/17744553/21681774/01d78468-d351-11e6-8f55-ca1947c6994a.png)

![schermafbeelding 2017-01-05 om 14 09 43](https://cloud.githubusercontent.com/assets/17744553/21681711/b821ea3e-d350-11e6-86a7-ab5b85b474df.png)

```
<table>
<tbody>
<tr>
<td><strong>Twitter Analytics</strong></td>
<td><strong>Twitter cards</strong></td>
<td><strong>homepage SEO</strong></td>
<td><strong>Instagram Analytics</strong></td>
</tr>
<tr>
<td>Twitter Analytics</td>
<td>Twitter cards</td>
<td>homepage SEO</td>
<td>Instagram Analytics</td>
</tr>
<tr>
<td>Twitter</td>
<td>Twitter</td>
<td>business name or brand</td>
<td>Instagram</td>
</tr>
<tr>
<td>analytics</td>
<td>Twitter account</td>
<td>homepage</td>
<td>followers</td>
</tr>
<tr>
<td>Twitter analytics dashboard</td>
<td>account</td>
<td>optimize your homepage</td>
<td>analytics</td>
</tr>
<tr>
<td>Twitter cards</td>
<td>data</td>
<td>site name</td>
<td>engagement rate</td>
</tr>
</tbody>
</table>
```

**Comment by nataliashitova** [comment]
The new mechanism for internal linking suggestions and insights (https://github.com/Yoast/javascript/issues/79) does not check for multi-word combinations, which effectively solves the issue.
