### ISSUE TITLE
Remove the rounded borders of the snippet preview

### ISSUE THREAD

**Issue by afercia** [Yoast/YoastSEO.js#1030]
See https://github.com/Yoast/wordpress-seo/issues/6374

This very, very, light border is almost unnoticeable but affects the max-width of the snippet preview which currently is `598px` and should be `600px` instead:

![screen shot 2017-01-13 at 13 23 29](https://cloud.githubusercontent.com/assets/1682452/21930175/dd436352-d994-11e6-8a4b-f660365936ab.png)

**Comment by omarreiss** [comment]
@hedgefield could you upload your designs here? Apparently @afercia was working on the same problem.

**Comment by hedgefield** [comment]
Hey @afercia, we also tried out this design change yesterday, the CSS changes we made are listed below with an example:

.yoast-section {
REMOVED border-radius property
REMOVED border property
ADDED box-shadow: 0 1px 2px rgba(0,0,0,.2);
}

![borderssquare](https://cloud.githubusercontent.com/assets/6073772/22068891/c1871b08-dd96-11e6-8e05-b68f38d313d2.png)

I believe the box shadow is the same as the wordpress meta boxes have, that's where those values came from.

**Comment by afercia** [comment]
@hedgefield thanks. Great because box-shadow will not affect the size of the elements, while border does. In #1031 I'm already removing the rounded border so if no objections maybe this can be merged and then we'll adjust what needs to be adjusted?

**Comment by omarreiss** [comment]
@afercia if you don't mind, could you update the PR(s) to implement @hedgefield's design consistently across the entire analysis section of the metabox?

**Comment by afercia** [comment]
Sure, will have a look.

**Comment by afercia** [comment]
Looking a bit into this, the `yoast-section` styling is currently imported from different places and there's a bit of repetition. I'd propose to don't add the box shadow here and add it in https://github.com/Yoast/yoast-components/issues/129 because, as far as I understand, it should be the default styling of the `yoast-section` component.

**Comment by hedgefield** [comment]
Sounds good. I figured the properties out using the inspector so it's always a bit hard to tell where exactly is the best place to put it, but you're right, this should apply to all yoast sections.

**Comment by afercia** [comment]
Screenshot with https://github.com/Yoast/yoast-components/issues/129 applied and after building all the stuff: notice the Mobile Snippet Preview already has its own box shadow (I guess to mimic the style of the Google mobile snippet). So there are two nested boxes, both with the same box shadow.

When switching to the desktop preview there's just one box shadow of course. Also no padding inside the snippet, this results in sort of "moving" effect that maybe is a bit jarring. I'd suggest to reset at least the top padding.

<img width="798" alt="screen shot 2017-01-19 at 16 24 12" src="https://cloud.githubusercontent.com/assets/1682452/22115871/eaca2f90-de6e-11e6-82c0-e1521eb23dec.png">

**Comment by omarreiss** [comment]
Fixing the jarring by resetting the padding seems like a good improvement. There's also https://github.com/Yoast/wordpress-seo/issues/6468 that should make the mobile snippet preview more intuitive. Only thing confusing about your screenshot is that the mobile snippet preview is shown while the desktop view seems to be selected.

**Comment by afercia** [comment]
> the mobile snippet preview is shown while the desktop view seems to be selected

Yep, I'm afraid it doesn't work exactly as expected, see https://github.com/Yoast/wordpress-seo/issues/6477
