### ISSUE TITLE
Matching keywords in non-latin alphabets doesn't work properly

### ISSUE THREAD

**Issue by terw-dan** [Yoast/YoastSEO.js#104]
Currently matching keywords in non-latin alphabets (ie Hebrew or Cyrillic) doesn't work properly, since wordboundaries aren't recognized in these languages. 

The problem is the fact JavaScript cannot match wordboundaries in these languages, so words that match partially are also found as match (so 'ab' not only matches 'ab', but also 'abc' or 'dab', where it should only match 'ab'). 
see: http://blog.stevenlevithan.com/archives/fixing-javascript-regexp

A possible solution would be to convert all spaces or periods to a specific character and use that as word boundaries. 
Another solution is converting every character to a alphanumeric char (a-z0-9), but this limits to only 36 characters, and some languages have (many) more. 
Also, not in every language it would be desirable to use spaces as wordboundaries, as certain prefixes of words would still make a good match of the keyword.

**Comment by atimmer** [comment]
This has been fixed.
