### ISSUE TITLE
Html code appears in the prominent keyword section

### ISSUE THREAD

**Issue by CarolineGeven** [Yoast/YoastSEO.js#1044]
Copied from https://github.com/Yoast/wordpress-seo-premium/issues/947

### What did you expect to happen?
Prominent Keywords To appear
### What happened instead?
Html output appeared instead. 

### With DIVI
**1.Add a post**

**2.Create using Divi's pagebuilder**

![screen shot 2016-12-20 at 6 17 27 pm](https://cloud.githubusercontent.com/assets/8238074/21371664/92f7fe46-c6e0-11e6-84ca-22f7e19ec56d.png)

**3.See content bloom html code appear in prominent keywords section**

![screen shot 2016-12-20 at 6 17 34 pm](https://cloud.githubusercontent.com/assets/8238074/21371668/982988bc-c6e0-11e6-8f01-b95f7b29eb28.png)

### With OptinMonster
**1.Add Optin Monster Shortcode**

![screen shot 2017-02-23 at 10 28 36 am](https://cloud.githubusercontent.com/assets/8238074/23265511/de6d169a-f9b2-11e6-944d-d38ec6811c35.png)

**2.See fonts appear in Prominent Keywords Section**

![screen shot 2017-02-23 at 10 28 56 am](https://cloud.githubusercontent.com/assets/8238074/23265532/eca7520c-f9b2-11e6-82ee-7c066c388cac.png)

**3.Remove Shortcode**

![screen shot 2017-02-23 at 10 29 31 am](https://cloud.githubusercontent.com/assets/8238074/23265566/091123a0-f9b3-11e6-96e1-9a5f97b45a7a.png)

**4.See Prominent Keywords appear**

![screen shot 2017-02-23 at 10 29 36 am](https://cloud.githubusercontent.com/assets/8238074/23265562/0708a790-f9b3-11e6-8b6c-2adc5223ad1a.png)

### What did you expect to happen?
Prominent keywords to appear
### What happened instead?
They did not
### How can we reproduce this behavior?
**1. Add a container, a text module, and a button**

![screen shot 2017-02-22 at 10 27 40 am](https://cloud.githubusercontent.com/assets/8238074/23218220/b526b56c-f8e9-11e6-8c7c-72d8b1244b44.png)

**2. Edit the button. Go to the second tab called "Design". The first property is "Button Style". Set it to "Custom" and save.** 

![1](https://cloud.githubusercontent.com/assets/8238074/23218249/c5a93496-f8e9-11e6-8f0f-e073a735c0c6.png)

**3.Update the page and wait for Yoast to analyse the content. Now check "Prominent Keywords" section.** 

![screen shot 2017-02-22 at 10 27 19 am](https://cloud.githubusercontent.com/assets/8238074/23218268/d612b79e-f8e9-11e6-801d-b037976554a8.png)

**4.Edit the button again. Change button style to Green (or any other style) and save.** 

![2](https://cloud.githubusercontent.com/assets/8238074/23218309/f4e7993c-f8e9-11e6-82ec-90fb4469a577.png)

**5.Update the page and wait for Yoast to analyse the content.** 

**6.Now check "Prominent Keywords" section. It displays the right words.**

![screen shot 2017-02-22 at 10 27 22 am](https://cloud.githubusercontent.com/assets/8238074/23218322/fbf26a54-f8e9-11e6-900c-2972116576b1.png)

### Technical info
* WordPress version: 4.7.2
* Yoast SEO version: 4.3.2
* Fusion Builder: 1.0.6
*Fusion Core: 3.0.6
* Avada: 5.0.6

**Notes:** No JavaScript errors appear
-------

We should make sure we do not analyse the content within a `<style></style>`block.

**Comment by CarolineGeven** [comment]
Please inform the customer of conversation # 166347 when this conversation has been closed.

**Comment by CarolineGeven** [comment]
Please inform the customer of conversation # 167104 when this conversation has been closed.

**Comment by CarolineGeven** [comment]
Please inform the customer of conversation # 170164 when this conversation has been closed.

**Comment by atimmer** [comment]
The way to fix this is to include an HTML parser in YoastSEO.js and then excluding everything between `style` and `script` tags.

**Comment by CarolineGeven** [comment]
Please inform the customer of conversation # 180522 when this conversation has been closed.

**Comment by CarolineGeven** [comment]
Please inform the customer of conversation # 180536 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 181844 when this conversation has been closed.

**Comment by IreneStr** [comment]
XHTML matching with regexes: http://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags/1732454#1732454

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 183526 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 184248 when this conversation has been closed.

**Comment by iamazik** [comment]
An example of Avada fusion builder code which is appearing in the prominent words section:
![image001](https://cloud.githubusercontent.com/assets/8946603/23806712/f08af446-05ec-11e7-9b4e-e6fd9b693bd4.jpg)

**Comment by iamazik** [comment]
Please inform the customer of conversation # 185235 when this conversation has been closed.

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/YoastSEO.js/issues/840

**Comment by iamazik** [comment]
Please inform the customer of conversation # 185793 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 186855 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 187625 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 187760 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 188191 when this conversation has been closed.

**Comment by iamazik** [comment]
Related: https://github.com/Yoast/YoastSEO.js/issues/1127

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 188484 when this conversation has been closed.

**Comment by Pcosta88** [comment]
**Avada Content Boxes module results in html elements in prominent keyword section**

**Add Content Boxes**
![screen shot 2017-04-07 at 10 13 35 am](https://cloud.githubusercontent.com/assets/8238074/24804073/45f2f7aa-1b7b-11e7-9db1-9f34426dc1de.png)

**See html elements**
![screen shot 2017-04-07 at 10 14 07 am](https://cloud.githubusercontent.com/assets/8238074/24804083/4bf7381e-1b7b-11e7-92c9-53286b96e68b.png)

**Delete content boxes and see prominent keywords appear**
![screen shot 2017-04-07 at 10 14 40 am](https://cloud.githubusercontent.com/assets/8238074/24804109/5db08a56-1b7b-11e7-879f-3c35c181cf7f.png)


**Specs**
Avada Theme: 5.1.5
Yoast: 4.5
WordPress: 4.7.3

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 188191 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 191331 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 191182 when this conversation has been closed.

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/YoastSEO.js/issues/1134

**Comment by CarolineGeven** [comment]
Please inform the customer of conversation # 189501 when this conversation has been closed.

**Comment by Pcosta88** [comment]
@andizer  I am confused as to why this was closed. Can you clarify? Was the issue resolved or was it closed as we are in the process on working on a new HTML parser?

**Comment by atimmer** [comment]
@Pcosta88 This has been fixed by excluding `<style>` and `<script>` tags. If issues still persist we should create new issues for them.

**Comment by Pcosta88** [comment]
@atimmer Ahh ok. The milestone does not show complete. So I was unsure. I'll open a new issue if it returns.
