### ISSUE TITLE
Source code should be excluded from the paper

### ISSUE THREAD

**Issue by CarolineGeven** [Yoast/YoastSEO.js#1051]
Copied from https://github.com/Yoast/wordpress-seo/issues/6495

### What did you expect to happen?
I wrote a great post, and I expected to get a top rating in the readability tab. 
(Just kidding. I'm not a native speaker of English, so I don't really expect to write a great post. But you know what I mean).

### What happened instead?
The readability check confused me with reporting seven consecutive sentences starting with the same word. As it turned out, this was part of the source code I showed on my programmer's blog. I can only guess, but I suspect the source code is also evaluated by the other tests, such as the Flesch reading ease test.

### How can we reproduce this behavior?
Create a blog post containing this snippet:

Lorem ipsum sunt dolorem.
[sourcecode]
npm install bootstrap --save
npm install datatables.net --save
npm install datatables.net-bs --save
npm install datatables.net-select --save
npm install datatables.net-select-bs --save
npm install jquery --save
npm install @types/jquery --save-dev
[/sourcecode]
Consectetur adipiscing elit. 

Can you provide a link to a page which shows this issue?
https://www.beyondjava.net/blog/how-to-use-a-javascript-datatable-in-an-angular-application/ 

### Technical info
* WordPress version: 4.7.1
* Yoast SEO version: 4.1

**Comment by atimmer** [comment]
Shortcodes are not in the domain of YoastSEO.js so should be dealt with in Yoast SEO.

The part that has to be fixed in YoastSEO.js is that we should exclude everything between `code` tags. See also https://github.com/Yoast/YoastSEO.js/issues/1044#issuecomment-275068472.

**Comment by stephanrauh** [comment]
I don't care where shortcodes are dealt with, as long as they are dealt with! :) 

I understand that it's difficult to decide which shortcode should be included and which shortcodes should be excluded from the rating. But I believe that [sourcecode] is a fairly common shortcode and that the content of this shortcode should always be ignored.

**Comment by stephanrauh** [comment]
BTW, I'm reluctant to offer a pull request because I don't have enough spare time, but if need be, I'd be ready, even if I'm already busy contributing to other open source projects. Just tell me.

**Comment by CarolineGeven** [comment]
@atimmer, could you please elaborate with what should be dealt with in Yoast SEO and which part belongs in yoastseo.js? I've discussed this with @terw-dan and we've concluded that this issue belongs in thie repository. I would like to hear which issue belongs to Yoast SEO and which to yoastseo.js.

**Comment by CarolineGeven** [comment]
@stephanrauh Could you please open your JavaScript console and execute `YoastSEO.app.paper.getText();` and let us know the result? This way we can determine whether the shortcodes are already registered or not. Are you using a specific plugin for this?
Thanks.

**Comment by stephanrauh** [comment]
Sure. If I enter this text in the non-wisiwig editor of Wordpress:
```
The other day I followed (and participated) in an interesting Twitter discussion about the pros and cons of the <code>Optional</code> class in Java. Some people seem to prefer using functional programming over the good old <code>if</code> statement:

[sourcecode language="Java"]
Optional<Soundcard> soundcard = ...;
soundcard.ifPresent(System.out::println);
[/sourcecode]
```

I get this result on the JavaScript console:
```
> YoastSEO.app.paper.getText()
"The other day I followed (and participated) in an interesting Twitter discussion about the pros and cons of the <code>Optional</code> class in Java. Some people seem to prefer using functional programming over the good old <code>if</code> statement:


Optional<Soundcard> soundcard = ...;
soundcard.ifPresent(System.out::println);
"
```

BTW, I also found quite a few "unable to tokenize" errors in the console log.

**Comment by terw-dan** [comment]
Thanks for your reply. 
It seems the content of the shortcode is simply parsed as plain text. In that case it will be very difficult to figure out whether something is a code snippet or not. 
We should check if we should override the sourcecode shortcode parsing or not. 

The tokenizer error seems to be related to: https://github.com/Yoast/YoastSEO.js/issues/840

**Comment by omarreiss** [comment]
We need to exclude `<code>` blocks from the paper. This shouldn't be too hard. Adding this to the queue.

**Comment by omarreiss** [comment]
Related #1080, #1077
