### ISSUE TITLE
The snippet preview toggler fails under certain conditions

### ISSUE THREAD

**Issue by afercia** [Yoast/YoastSEO.js#1071]
For reference, see #954 and #1054.

The snippet preview toggler should automatically switch to the "mobile preview" when the snippet container width doesn't allow to show the "desktop preview". This works well on the first load of the page. Shrink your browser's window, and you will see the snippet preview automatically switches to mobile, thus preserving the responsiveness of the whole metabox.

Note: the relevant viewport width breakpoint is 1249 pixels *when the WP admin menu is expanded*.

Dumping into the console some numbers, see screenshot below:

![screen shot 2017-02-15 at 14 59 37](https://cloud.githubusercontent.com/assets/1682452/22979922/4d66492a-f398-11e6-8851-73b86a49c7c5.png)

Hope the screenshot helps making clear that, when shrinking the window, the snippet container is allowed to shrink and when its width gets less than 640 pixels, the automatic switch happens.

However, now try this:
- make the browser window larger
- refresh the page
- click on the "mobile" button
- click on the "desktop" button

A couple CSS rules just got applied to some elements:
```
.snippet-editor__view--desktop {
    width: 600px;
    background: #fff;
}

.snippet-editor__view--desktop .snippet_container__title {
    width: 600px;
}
```

Those elements are children of the snippet preview and have a fixed width. Thus, the snippet preview container is not allowed to shrink under 640 pixels (600 width + padding) any longer. The `previewWidth` is always `640` and the condition to make the toggler work properly is never met:

![screen shot 2017-02-15 at 15 00 42](https://cloud.githubusercontent.com/assets/1682452/22980240/48c398e0-f399-11e6-82bb-4167908f736e.png)

To my understanding, the fixed 600 pixels width is probably meant to make the desktop preview always have a... desktop width. But that leads us to the original problem: on small screens, pressing the Desktop button will make the metabox overlap and hide some content on the right.

We should probably clarify what is the exact behavior to implement. Maybe one relevant point is:
should the toggle buttons be hidden when the preview container is under the allowed `minimumDesktopWidth`? Reading the the original PR, see @atimmer [comment](https://github.com/Yoast/YoastSEO.js/pull/954#issuecomment-267362508)
> The button for the desktop variant should be hidden if there is no room for the desktop variant.

Not sure if the plans have changed later, but this hasn't been implemented so on small screens we still have the original problem.

Couple additional issues:

1
Should `handleWindowResizing` run also on the `orientationchange` event? As far as I know, not all platforms/devices/browsers fire the `resize` event, especially on mobile.

3
In the mobile mode, avoid the title to wrap in multiple lines, see https://github.com/Yoast/wordpress-seo/issues/6548 (aside: in the issue, it is correctly reported that the relevant viewport width breakpoint is 1249 pixels)

**Comment by afercia** [comment]
Taking into account the WordPress admin menu can be expanded/collapsed, things get more complicated since the check for the available room should run also when expanding/collapsing the menu.

**Comment by omarreiss** [comment]
Dropping by for some requirement decisions. I didn't read the whole issue but I'm responding to a summary @atimmer gave me. Hope this gives some direction:

- First things first, screen resizing isn't a real world usecase we should optimize for. That would be heavily over-engineering things. 
- Of course we should adapt nicely to the viewport (on init, I don't care so much about resizing). If on a mobile viewport, it's nicer to initially show the mobile snippet preview. People need to still be able to switch to the desktop preview as the responsiveness isn't the primary goal of the feature. As a user I still need to be able to optimize for desktop search results, also on mobile. So the switcher shouldn't be hidden.
- In the mobile viewport, my desktop preview will run off the screen. I prefer this gets fixed with horizontal scrolling.

As far as technical solutions go, I'll leave it up to @atimmer @moorscode @afercia.

**Comment by afercia** [comment]
What about adding some explanation in the inline help text? As far as I know, we're not saying anything anywhere to explain how the Mobile/Desktop switch works. Something simple (without entering technical terms such ass 600px width) could help, perhaps:

![screen shot 2017-02-17 at 09 25 48](https://cloud.githubusercontent.com/assets/1682452/23058050/4fbe9bda-f4f3-11e6-87bb-e926c1b94258.png)

**Comment by afercia** [comment]
Worth noting that fixing the layout in the mobile view, will keep breaking the title length check, as mentioned in https://github.com/Yoast/wordpress-seo/issues/6457#issuecomment-280670374
