### ISSUE TITLE
Use site language to show relevant links

### ISSUE THREAD

**Issue by andizer** [Yoast/YoastSEO.js#1074]
I've set my site language to Dutch and my user language is English. This results in the Dutch analysis for my content, but the readability checks are given in English. This is great. But the text given in the readability is linking me to an English wikipedia content. 

For example the transition words is link to the English version of a wikipedia page about it.

It would be great to have a Yoast Knowlegde base article or something like that, which is showing the right explanation, in the site language that is being used, with examples for the check. 

So for transitionwords the result is in English but I am being linked to the Dutch version about it.

**Comment by omarreiss** [comment]
I agree this would be nice. However, our knowledge base isn't translated at the moment. When that changes, we need to come up with a general approach to fix this everywhere in our software.
