### ISSUE TITLE
Prominent words: Exclude code blocks

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#1077]
We should exclude code blocks from the prominent words analysis, both with [code] (incl. [code light="true" lang="php"] etc.) and with `<code>`.

This should ensure the following types of 'words' are no longer included:

- $before
- server_name
- $url = get_permalink
- yoast_disable_admin_bar 9
- h2 id=&quot
- wp_redirect
- $wp_query-&gt
- width=300 height=400&amp
- id=”640511 style=”button color=”blue (current count = 0, possibly already fixed)
- banner text= icon= url= (current count = 0, possibly already fixed)
- return_false 99
- meta property=&quot

**Comment by CarolineGeven** [comment]
Related to #1051

**Comment by omarreiss** [comment]
This should be fixed on the paper level. See #1051
