### ISSUE TITLE
Prominent words: Exclude urls and e-mail addresses

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#1083]
We should exclude urls from the prominent words analysis. This should ensure the following types of 'words' are no longer included:
- v=vwp16izsnto 
Post URL: https://yoast.com/yoastcon-livestream/ 
(current count = 0, possibly already fixed)

**Comment by iamazik** [comment]
Please inform the customer of conversation # 405219 when this conversation has been closed.

**Comment by iamazik** [comment]
This is important as when a page mostly contains URLs (i.e. HTML sitemap page) and it appears in the internal linking suggestions on other pages.

### Screenshots
![89a0e6d3ee813c457593cf73fb68c85a _www lookupstrata com au_wp-admin_post php_post 31611 action edit](https://user-images.githubusercontent.com/8946603/42734182-98014372-8861-11e8-8a27-257b4682cbd6.png)
![e1948641f5eafb396d980c969d2e7ee8 _www lookupstrata com au_visitor-sitemap_](https://user-images.githubusercontent.com/8946603/42734183-9840ba5c-8861-11e8-95dd-c2fcd995de01.png)

**Comment by IreneStr** [comment]
Closing because the prominent word calculation has had a complete overhaul in Yoast SEO 14.7. Because we calculate them smarter, I doubt this is still a problem. A new issue can be created on Jira if this issue is still present.
