### ISSUE TITLE
English prominent words: Filter out combinations containing numbers and coordinating conjunctions

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#1091]
We should filter out word combinations solely containing numbers and coordinating conjunctions.

Example from yoast.com: 7 14 or 30

**Comment by CarolineGeven** [comment]
We shouldn't forget number combinations such as phone numbers

**Comment by IreneStr** [comment]
Closing because the prominent words calculation will be changed soon.
