### ISSUE TITLE
English prominent words: add more function words to word lists

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#1092]
The following words should be added to the respective word lists:

## additionalTransitionWords
- e.g (no period at end!)
- etc (no period at end!)
- and/or
- instead
- whether

## numerals
- millions (`million` is currently in the list twice)

## generalAdjectivesAdverbs
- able
- available
- average
- awful
- awesome
- basic
- beautiful
- busy
- certain
- current
- entire
- everywhere
- important
- major
- multiple
- normal
- necessary
- obvious
- particular
- partly
- special
- specific
(extend list with most frequent English words: https://en.wikipedia.org/wiki/Most_common_words_in_English)

## delexicalisedVerbs
- consists
- consist
- consisted
- ensure
- ensures
- ensured

## quantifiers
- kinds

## interviewVerbs
- talks
- talked
- announces
- announced
- tells
- told
- discusses
- discussed
- suggests
- suggested
- understands
- understood

## vagueNouns
- instance
- instances
- detail
- details
- factor
- factors
- difference
- differences

## miscellaneous
- sorry
- please

**Comment by amboutwe** [comment]
Please add `approximately` to the list, too.

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 186020 when this conversation has been closed.
