### ISSUE TITLE
Prominent words: Find a way to avoid similar sequences of combinations of increasing length

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#1109]
We should find a way to avoid sequences like the following from showing up in the prominent words:
- compatibility
- compatibility with yoast
- compatibility with yoast seo
- compatibility with yoast seo 4.0

## Dilemma
For the Insights, longer combinations might be more useful, while for linking suggestions more compact combinations might be more useful.

**Comment by omarreiss** [comment]
I think for linking suggestions they can simply all be indexed if they are relevant. We just need to make sure we have a way to filter out the less relevant variants for the insights.

**Comment by IreneStr** [comment]
Closing because the prominent words calculation will be changed soon.
