### ISSUE TITLE
Wrong Sentence While Using French

### ISSUE THREAD

**Issue by iamazik** [Yoast/YoastSEO.js#1121]
## What did you expect to happen?
The content analysis should use the correct sentence while using the French language.

## What happened instead?
The content analysis incorrect sentence while using the French language.

Wrong: `wrong : 6.5% des phrases contiennent plus que 20 mots, ce qui est inférieure ou égale à la valeur maximale recommandée de 25%.`

Correct: `ce qui est inférieur ou égal`

* Platform: WordPress
* Platform version: 4.7.3
* Yoast SEO version: 4.4

**Comment by iamazik** [comment]
Please inform the customer of conversation # 185600 when this conversation has been closed.

**Comment by CarolineGeven** [comment]
We do not handle translations in the plugin, these are handled on WordPress.org. We rely on our community for translations, if one of the French translations is incorrect, the user can create an account on WordPress.org and suggest a fix:
https://translate.wordpress.org/projects/wp-plugins/wordpress-seo/stable/fr/default?filters%5Bterm%5D=valeur+maximale+recommand%C3%A9e&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc
