### ISSUE TITLE
Keyword Matching in Meta Description fails when keyword has a period at the start another word in front of it in the meta description

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/YoastSEO.js#1123]
## What did you expect to happen?
Yoast to find the Focus keyword in the Meta Description
## What happened instead?
It did not. The warning of "A meta description has been specified, but it does not contain the focus keyword." appeared

## How can we reproduce this behavior?
**1. Make keyword be ".Net Developer"**

**2. Make Meta Description be "Exceptional .Net Developer Resume"**

**3. See Warning**

![screen_shot_2017-03-30_at_3_13_37_pm](https://cloud.githubusercontent.com/assets/8238074/24521909/ca719b4c-155b-11e7-952d-ae7e02874728.png)

## Technical info

* Platform: WordPress 
* Platform version: 4.7.3
* Yoast SEO version: 4.5

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 188014 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 332054 when this conversation has been closed.

**Comment by iamazik** [comment]
When using `.Net` as the focus keyword, keyword density becomes 0%. Substituting `dot NET` for all instances of `.NET` fixes the problem but isn't very readable.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 487814 when this conversation has been closed.

**Comment by monbauza** [comment]
Another example of a focus keyword containing a period and not being detected: `Scalpel Handle No. 7`

**Comment by monbauza** [comment]
Keyphrases with a period are not detected in the body text either which triggers the warning `Keyphrase density: The focus keyphrase was found 0 times`

**Comment by monbauza** [comment]
Please inform the customer of conversation # 489524 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Closed .net keyword is seen in meta description and in body of text

<img width="598" alt="Screen Shot 2020-08-31 at 3 03 01 PM" src="https://user-images.githubusercontent.com/8238074/91756665-1ac81580-eb9b-11ea-8d30-59efabd91d2a.png">

<img width="645" alt="Screen Shot 2020-08-31 at 3 03 06 PM" src="https://user-images.githubusercontent.com/8238074/91756678-1ef43300-eb9b-11ea-89e5-68ecf8c9ddfe.png">

**Comment by caspervoogt** [comment]
I am experiencing a similar issue (not sure if identical) with focus keyphrase count being incorrect. [I recorded a brief (< 4 minute) screencast](https://www.loom.com/share/152df11ba7034050a98d787fe539235f) showing the issue on a test site. The test site only has 2 plugins enabled: Elementor and Yoast, on the 2021 theme. No CSS/JS optimizations or caching or anything. WordPress 5.8.
