### ISSUE TITLE
Focus keyword: regex input

### ISSUE THREAD

**Issue by diedexx** [Yoast/YoastSEO.js#114]
Once a regular expression is entered in the Focus Keyword field, the application will strip all the regex key characters and match the text on the remaining string.
For instance: `/[A]/i` becomes `Ai`.

**Comment by atimmer** [comment]
Google will search for `A i` when you put in `/[A]/i`. So we should try to mirror this behaviour.

**Comment by diedexx** [comment]
Doesn't seem to be relevant anymore. And even if it is, if it's not fixed by now, it's never going to be fixed
