### ISSUE TITLE
Make textLengthAssessment score categories more consistent

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#1144]
The textLengthAssessment for 'regular' texts has 5 score categories: 9, 7, 5, -10 and -20. However, the textLengthAssessment for cornerstone articles only has 4: 9, 7, -10 and -20. This should become more consistent. 

We should also consider removing negative scores.

**Comment by Djennez** [comment]
Consistency seems to have been acquired, according to https://github.com/Yoast/YoastSEO.js/wiki/Scoring-readability-analysis#3-sentence-length
