### ISSUE TITLE
Improve feedback text for textImagesAssessment

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#1145]
When the images on a page contain an alt text, but no keyword is set, the user gets a red bullet. However, the text "The images on this page contain alt attributes" sounds like a positive thing, making it is unclear why the bullet is red.
![schermafbeelding 2017-05-16 om 15 20 25](https://cloud.githubusercontent.com/assets/17744553/26107925/388b3714-3a4b-11e7-8621-7d548bfbe64c.png)

**Comment by monbauza** [comment]
A small comment from a user: the colour of the bullet is orange instead of red in the current version of the plugin - Yoast SEO v7.2.

![image](https://user-images.githubusercontent.com/9658774/38362871-a7595a8c-38d2-11e8-83c7-6ea71de715d6.png)

**Comment by IreneStr** [comment]
Closing. All feedback strings have been improved since this issue was created.
