### ISSUE TITLE
Check if the keyword has been used before is missing

### ISSUE THREAD

**Issue by benvaassen** [Yoast/YoastSEO.js#1150]
The check would tell me if I've used a focus keyword before. A red bullet if I've used it 2 times or more, an orange bullet if I did use it once before, green bullet if I didn't. All three checks are missing in Yoast SEO 4.8.
- `You've never used this focus keyword before.`
- `You've used this focus keyword once before, be sure to make very clear which URL on your site is the most important for this keyword.`
- `You've used this focus keyword 2 times before, it's probably a good idea to read this post on cornerstone content and improve your keyword strategy.`

## How can we reproduce this behavior?
- Create a new post
- Set the focus keyword to `meta keyword`
- Publish
- Create a new post
- Set the focus keyword to `meta keyword`

In Yoast SEO 4.8:
![add_new_post_ _dev_wordpress_ _wordpress](https://cloud.githubusercontent.com/assets/11910661/26406328/4533e3a0-4098-11e7-867f-1bd8e140e8b6.png)

In Yoast SEO 4.7.1:
![add_new_post_ _dev_wordpress_ _wordpress](https://cloud.githubusercontent.com/assets/11910661/26406678/4a58c8d6-4099-11e7-884b-119581c46313.png)

## Technical info
* Platform: WordPress 
* Platform version: 4.7.5
* Yoast SEO version: 4.8

**Comment by boblinthorst** [comment]
I did some research trying to fix this one. Didn't have the time to finish it up.
It seems the previouslyUsedKeywords assesment is correctly added to the list of assessments. But somewhere between the addition of the assesment and the execution of all assessments, it is either removed or the list of assessments is overwritten. 

the assessment itself probably works fine, the bug occurs with something else trying to do something with the _assessments.

**Comment by Pcosta88** [comment]
@benvaassen Consider re-opening as issue still happens: https://github.com/Yoast/wordpress-seo/issues/7012
