### ISSUE TITLE
Eye marker 'You're linking to another page with the focus keyword' not working

### ISSUE THREAD

**Issue by PatrickYoast** [Yoast/YoastSEO.js#1155]
When I click the eye marker I expect it to highlight the link the check is talking about
![banners_and_alerts_and_edit_post_ _awesomesaurus_ _wordpress](https://cloud.githubusercontent.com/assets/14159618/26830110/0c900d78-4ac8-11e7-987f-d1cc51df1c8a.png)

But instead, nothing is highlighted in the content.

**Comment by CarolineGeven** [comment]
Related to #1151

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/wordpress-seo/issues/7180

**Comment by monbauza** [comment]
Please inform the customer of conversation # 199193 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 200799 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 211789 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 240580 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 250023 when this conversation has been closed.

**Comment by suascat** [comment]
Please inform the customer of conversation # 269296 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 274746 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 273769 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 277640 when this conversation has been closed.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 307953 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 311540 when this conversation has been closed.

**Comment by suascat** [comment]
Please inform the customer of conversation # 311776 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 315340 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 324812 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 326909 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 333540 when this conversation has been closed.

**Comment by suascat** [comment]
Please inform the customer of conversation # 334622 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 338390 when this conversation has been closed.

**Comment by millsdmb** [comment]
I have the same issue.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 353652 when this conversation has been closed.

**Comment by ubergiant** [comment]
Nothing is highlighted when clicking the "highlight this result in the text" icon and the Yoast settings disappear:
<img width="569" alt="highlight this result in the text" src="https://user-images.githubusercontent.com/40047318/41135053-05ac1972-6b13-11e8-85f3-782fb3704a45.png">
<img width="426" alt="yoast hidden" src="https://user-images.githubusercontent.com/40047318/41135059-0cba0a3a-6b13-11e8-9c08-ed7d40262ecf.png">

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 403995 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 410493 when this conversation has been closed.

**Comment by PatrickYoast** [comment]
@CarolineGeven @dariaknl This is still broken in 8.0 RC2. Seeing the time this issue is open and the amount of reactions it seems to worth looking for a fix. (cc @omarreiss)

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 440043  when this conversation has been closed.

**Comment by Pcosta88** [comment]
Still happens with v11 of Yoast and v5.1.1 of WP

**A. Focus Keyword**


<img width="287" alt="Screen Shot 2019-04-26 at 10 52 47 AM" src="https://user-images.githubusercontent.com/8238074/56816489-a4cad600-6811-11e9-8bde-429c83bb1e50.png">


**B. Link added to it**

<img width="240" alt="Screen Shot 2019-04-26 at 10 52 42 AM" src="https://user-images.githubusercontent.com/8238074/56816506-ab594d80-6811-11e9-824b-884354b52cb7.png">


**C. Highlight Fails to work**

<img width="780" alt="Screen Shot 2019-04-26 at 10 52 34 AM" src="https://user-images.githubusercontent.com/8238074/56816517-af856b00-6811-11e9-8746-336b3d782729.png">

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 498698 when this conversation has been closed.

**Comment by Djennez** [comment]
Eye marker was removed from this analysis.
