### ISSUE TITLE
Cannot find module 'lodash/foreach' from examples/browserified

### ISSUE THREAD

**Issue by anoopnaik** [Yoast/YoastSEO.js#1164]
## What did you expect to happen?

I expected the documentation or read me to be more clear on how to use this js in my current project.

## What happened instead?

I am getting not found errors for js and css in web console while opening html in examples directory.

When I run grunt I get the following error (I have done "npm install" and lodash is installed with version 4.7.4):

`root:/***************/yoastseo# grunt build:js`
`Running "browserify:example" (browserify) task`
`Error: Cannot find module 'lodash/foreach' from '/******************/yoastseo/examples/browserified'`
`Warning: Error running grunt-browserify. Use --force to continue.`

`Aborted due to warnings.`

## How can we reproduce this behavior?
Download latest yoast release and run grunt.

## Technical info

* Platform: Standalone
* Platform version: N/A
* Yoast SEO version: 1.17.2

**Comment by lucasvieiramay** [comment]
I'm having the same problem!

**Comment by lucasvieiramay** [comment]
I find the solution!
You need to change in examples/browserified/example.js this import:
var forEach = require( "lodash/foreach" );
to:
var forEach = require( "lodash/forEach" );

Let me know if work!

**Comment by atimmer** [comment]
Ah, it is probably case sensitive on your machine and case-insensitive on ours.

**Comment by atimmer** [comment]
I have pushed a commit to fix this. Thank you for reporting 👍🏻.
