### ISSUE TITLE
Remove 1-syllable check from prominent words analysis

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#1166]
We should consider removing the 1-syllable check from the prominent words analysis. 

Currently, words with one syllable can not end up in the prominent words list (only in word combinations). The rationale behind this is that the most frequent words in a language tend to be the shortest, but also the least specific (and therefore not very relevant). This filtering also serves as an extra safety net to catch all function words (which also tend to be short) that we might have forgotten to remove using the other filters.

I more and more feel like denying all one-syllable words from being a prominent word is not the way to go:

- I can't really justify why 'dogs' cannot in the prominent word list when you are writing a text about dogs, but 'hamsters' can be in the list when you are writing about hamsters.
- A more practical reason: when we start adding languages we don't have a syllable counter for yet (i.e. French, Italian), the scope of the issue for adding the prominent words analysis becomes a lot bigger because of this syllable check.

Although the practical reason is valid as well, I think the first reason is sufficiently convincing to reconsider the 1-syllable check.

Any thoughts on this @atimmer @manuelaugustin @omarreiss?

**Comment by atimmer** [comment]
I was doubtful about excluding 1-syllable words from the start for the purposes of relating posts to each other. I say drop the 1-syllable filtering completely.

If you want we could try this out on yoast.com and do a sample to see how link suggestions change for different posts.

**Comment by omarreiss** [comment]
Agreed, I think we will end up working with a blacklist. I think transition words are already ignored right?

**Comment by IreneStr** [comment]
@omarreiss Yes, transition words and all other function words (words with little meaning except for their grammatical function) can never show up in the prominent word list.
