### ISSUE TITLE
SEO title feedback incorrect when you enter a space

### ISSUE THREAD

**Issue by benvaassen** [Yoast/YoastSEO.js#1167]
## What did you expect to happen?
I enter a space in the SEO title Snippet Preview. I expected the title to reflect the SEO title I entered and show a space with a small red feedback line. 

## What happened instead?
Instead, the title changes to "Please provide an SEO title by editing the snippet below" and shows a green feedback line. 

## How can we reproduce this behavior?
1. Create a new post
1. Edit the Snippet Editor
1. Delete your SEO title and enter a space " ". 

![image](https://user-images.githubusercontent.com/11910661/27084226-678754c4-504b-11e7-81e1-11b200e0a03a.png)

## Technical info
* Platform: WordPress
* Platform version: 4.8
* Yoast SEO version: 4.9

**Comment by omarreiss** [comment]
Issue seems to have been resolved after reactification.
