### ISSUE TITLE
Add time words to English, Dutch and Spanish transition word lists

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#1168]
We should add time words to the English, Dutch and Spanish transition word list.

German example: [ "sekunde", "sekunden", "minute", "minuten", "uhr", "uhren", "tag", "tages", "tags", "tage", "tagen", "woche", "wochen", "jahr", "jahres", "jahrs", "jahre", "jahren" ];

**Comment by manuelaugustin** [comment]
Also Dutch

**Comment by IreneStr** [comment]
Dutch: [ "seconde", "secondes", "seconden", "minuut", "minuten", "uur", "uren", "dag", "dagen", "week", "weken", "maand", "maanden", "jaar", "jaren", "vandaag", "morgen", "overmorgen", "gisteren", "eergisteren", "'s", "morgens", "avonds", "middags" ]

// 'Segundo' and 'segundos' are already included in the ordinalNumerals.
Spanish: [ "minuto", "minutos", "hora", "horas", "día", "días", "semana", "semanas", "mes", "meses", "año", "años", "hoy", "mañana", "ayer" ]

// 'Second' is already included in the ordinalNumerals.
English: [ “seconds”, “minute”, “minutes”, “hour”, “hours”, “day”, “days”, “week”, “weeks”, “month”, “months”, “year”, “years”, “today”, “tomorrow”, “yesterday” ]

Italian: remove duplicate `stamattina`

Add for German: "monat", "monate", "monates", "monats", "monaten"
