### ISSUE TITLE
Error: module not found

### ISSUE THREAD

**Issue by VitaliyLogvin** [Yoast/YoastSEO.js#1174]
Hi! When i run `browserify /node_modules/yoastseo/index.js -o destination.js -d`

Console wrote:

Error: module not found: "/node_modules/yoastseo/index.js" from file /node_modules/yoastseo/_fake.js
    at onresolve (/usr/lib/node_modules/browserify/node_modules/module-deps/index.js:180:30)
    at /usr/lib/node_modules/browserify/index.js:494:18
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/index.js:247:21
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:18
    at load (/usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by thulshof** [comment]
Thanks for your report. In most cases, running 'yarn install' will solve this issue. Could you try that?

**Comment by VitaliyLogvin** [comment]
Yes, I did it but the error remained. Help please run your plugin. 
Can you help compile the file? I download.
Thank you

**Comment by eugenevdm** [comment]
I tried `yarn install` but I am still getting the same issue.

**Comment by gokulmhegde** [comment]
I tried it, which didn't work.

Is there any solutions.
