### ISSUE TITLE
Prominent words: filter time indications

### ISSUE THREAD

**Issue by manuelaugustin** [Yoast/YoastSEO.js#1177]
Our list of prominent words currently includes time indications such as for example 'ore 15.30' ('3:30 PM'). These should be filtered, as they don't provide any information value. However, we need to make sure that we only filter the right combinations. For example, we don't want to filter 'ore di lavoro' ('working hours'). This issue needs to be investigated in all the languages for which we provide the prominent words feature.

**Comment by IreneStr** [comment]
Also: uur van de waarheid, year of the sheep etc.

**Comment by manuelaugustin** [comment]
Not relevant anymore; we include time words in our function word lists. The question of combinations isn't relevant anymore since the new internal linking was released.
