### ISSUE TITLE
I can not connect Russian language

### ISSUE THREAD

**Issue by VitaliyLogvin** [Yoast/YoastSEO.js#1191]
Hi! I installed your JS plugin on my site. He's awesome! But i have 4 questions. 
1) How can i change "example.com/" to "mysite.com" on Snippet preview? And that it can not be changed.
2) I can not connect Russian language. Is there no support for him?
3) How can i set predefined SEO title part which can not be changed. Like "Bla bla bla **- My Site**"
4) How can i set predefined meta description?

**Comment by Djennez** [comment]
This is a bit late of a reply to this question, but anyway.

- Russian is supported: https://github.com/Yoast/YoastSEO.js#supported-languages
- Please check our KB for the other questions: https://yoast.com/wordpress/plugins/seo/titles-and-meta-descriptions/
