### ISSUE TITLE
Purple view eye icon isn't highlighting the subheading followed by more than the recommended maximum of 300 words.

### ISSUE THREAD

**Issue by benvaassen** [Yoast/YoastSEO.js#1195]
The view icon is visible for this check, but when you click on it, nothing is highlighted in the text. 

![edit_post_ _dev_wordpress_ _wordpress](https://user-images.githubusercontent.com/11910661/28115959-41b47a92-6707-11e7-9d50-c019a769ecb6.png)

## To reproduce
Create a text with a subheading and insert over 300 words below in the paragraph. 

## To fix
Either remove the clickable view eye icon or ensure that the highlighting actually works. 

## Related issues
https://github.com/Yoast/wordpress-seo/issues/5930
https://github.com/Yoast/YoastSEO.js/issues/1066

## Technical info
* Platform: WordPress 
* Platform version: 4.8
* Yoast SEO version: 5.0.1

**Comment by benvaassen** [comment]
Please inform the customer of conversation # 207985 when this conversation has been closed.

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 219583 when this conversation has been closed.

**Comment by devnihil** [comment]
Please inform the customer of conversation # 232227 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 255200 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 276467 when this conversation has been closed.

**Comment by michaelbriantina** [comment]
Please inform the customer of conversation # 278351 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 292463 when this conversation has been closed.

**Comment by afercia** [comment]
Reporting language related notes from #1360 

- I guess "another" should be "an other" /cc @jcomack
- not sure about the difference between "Try to insert another subheading." vs. "Try to insert additional subheadings."

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/YoastSEO.js/issues/1151

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 293479 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 320167 when this conversation has been closed.

**Comment by benvaassen** [comment]
Please inform the customer of conversation # 333194 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 336046 when this conversation has been closed.

**Comment by mayada-ibrahim** [comment]
Please inform the customer of conversation # 337658 when this conversation has been closed.

**Comment by Shugar12** [comment]
I have the same problem.  I got an email saying that I should look at this thread for the answer but I do not see any answer.  Does anyone know the fix?  Thank you.

**Comment by Andrasx** [comment]
Hi, same issue here. The eye icon does not highlight subheadings with more than 300 words.
Please let me know if you could solve this issue.
I love yoast by the way!

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 375932 when this conversation has been closed.

**Comment by benvaassen** [comment]
Please inform the customer of conversation # 409225 when this conversation has been closed.

**Comment by mayada-ibrahim** [comment]
Please inform the customer of conversation # 415937 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 417249 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 417891 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 418428 when this conversation has been closed.

**Comment by michaelbriantina** [comment]
Please inform the customer of conversation # 419115 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 429630 when this conversation has been closed.

**Comment by jgajera** [comment]
+1 request to get subheadings highlight fixed!

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 438044 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 438749 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation #453980 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Eye Highlight Icon No Longer Appears

**1. Highlight fails to appear in the Yoast SEO Metabox**

<img width="828" alt="Screen Shot 2019-04-02 at 10 58 12 AM" src="https://user-images.githubusercontent.com/8238074/55412975-699cf600-5536-11e9-9b65-09c339277a99.png">



**2. Highlight Fails to Appear in the Yoast SEO Sidebar (if you have Gutenberg in use)**

<img width="302" alt="Screen Shot 2019-04-02 at 10 58 33 AM" src="https://user-images.githubusercontent.com/8238074/55412971-67d33280-5536-11e9-9632-599d10f9199f.png">

Tech Specs
WP: 5.1.1
Yoast: 10.1.1

**Comment by marium0505** [comment]
This has been an issue on my sites for years.

**Comment by Hansaplast** [comment]
It never worked on my website either, and I've been using Yoast (paid) for a few years now.
Is there any information the Yoast team can provide to help debugging this issue?

The only thing I keep reading and hearing these past years is "it's fixed" (not), "update your plugin" (not resolving the issue), "switch to the default WordPress theme" (not helpful either) and "can we get access to your website" (not happening - sorry).

**Comment by Djennez** [comment]
As of version [9.2.0](https://yoast.com/wordpress/plugins/seo/change-log-wordpress-seo/) we have completely [removed](https://github.com/Yoast/YoastSEO.js/issues/1956) this highlight feature from the plugin as it was not working properly. 
> Disables the non-functioning markers for the subheading distribution assessment.

This functionality might return once we have implemented other ways of calculating and highlighting similar problems in texts. 

As for now, I will close this issue as it is no longer relevant. If you have additional questions or comments, please feel free to leave those here.
