### ISSUE TITLE
Bullets on Focus Keyword tabs changing color when switching tabs

### ISSUE THREAD

**Issue by rmarcano** [Yoast/YoastSEO.js#1205]
## What did you expect to happen?
Bullet colors on the Focus Keyword tabs not to change

## What happened instead?
They change color sometimes when switching tabs.

## How can we reproduce this behavior?

- Add multiple focus keywords to a post
- Optimize the focus keywords on a post until the tab bullet is green. However there can be two or three orange and red warnings left on each keyword.
- Switch tabs. Notice color change from green to orange on the tab that loses focus.

See video sent by user: https://www.youtube.com/watch?v=igcqHqK0HYI&feature=youtu.be

I managed to reproduce the issue by following the above steps and leaving two or three warnings on the keyword. When every single bullet on the keyword analysis is green, I could not reproduce it.

## Technical info

* Platform: WordPress
* Platform version: 4.8
* Yoast SEO version: 5.0.2

**Comment by monbauza** [comment]
Related: https://github.com/Yoast/wordpress-seo-premium/issues/741

**Comment by rmarcano** [comment]
Issue closed here: https://github.com/Yoast/wordpress-seo-premium/issues/741
