### ISSUE TITLE
Prominent words differ depending on space or new-line.

### ISSUE THREAD

**Issue by moorscode** [Yoast/YoastSEO.js#1206]
## What did you expect to happen?
To have the same result if the lines were split by spaces or line-breaks.

## What happened instead?
![yoast_prominent_words_analysis](https://user-images.githubusercontent.com/2005352/28455808-96c13296-6e00-11e7-929f-cd765e12fee9.png)
![yoast_prominent_words_analysis](https://user-images.githubusercontent.com/2005352/28455817-a1bf7ff4-6e00-11e7-860e-b0215efd7f9a.png)

## How can we reproduce this behavior?
Have three sentences that are the same in words.
See the difference when the three two lines are combined with spaces vs with line-breaks.

If the sentence is repeated multiple times on the same line, the counts are relatively the same, but when the sentence is repeated 3 times on one line, the same behaviour exhibits.

![relevant words](https://user-images.githubusercontent.com/2005352/28456210-d91a4924-6e01-11e7-856c-6d03f6d060ea.gif)

## Technical info

* Yoast SEO version: develop

**Comment by manuelaugustin** [comment]
This issue isn't relevant anymore since we don't use word combinations anymore for prominent words and internal linking, but only single words.
