### ISSUE TITLE
Mobile snippet preview title and metadescription break out of div

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#1207]
![schermafbeelding 2017-07-25 om 11 28 02](https://user-images.githubusercontent.com/17744553/28565552-e15d661a-712c-11e7-8034-01d6f5ded720.png)

## How can we reproduce this behavior?
- Use the mobile snippet preview
- Use a very long word **without spaces** as title/metadescription.
- Resize your window to a width of +/- 860 px.

**Comment by omarreiss** [comment]
Not a real world usecase. Closing
