### ISSUE TITLE
Keyword can contain HTML-tags

### ISSUE THREAD

**Issue by andizer** [Yoast/YoastSEO.js#122]
It look likes the keyword can contain HTML-tags:
![add_new_post_ _theme_ _wordpress](https://cloud.githubusercontent.com/assets/325040/10879827/bd4ba830-8156-11e5-8bbb-d19907c26aae.png)

Another effect of html are the `<i>` tags:
![add_new_post_ _theme_ _wordpress](https://cloud.githubusercontent.com/assets/325040/10879860/f2a1dd6a-8156-11e5-886a-7583fca87193.png)

It seems the HTML will be parsed when the tags are started and closed.
![add_new_post_ _theme_ _wordpress](https://cloud.githubusercontent.com/assets/325040/10879932/60ed0d76-8157-11e5-86ba-bf4847b5a954.png)

**Comment by omarreiss** [comment]
Escape anything that is dynamically added to the feedback.
