### ISSUE TITLE
How to use examples/browserified/ ?

### ISSUE THREAD

**Issue by alexbayleaf** [Yoast/YoastSEO.js#1220]
## What did you expect to happen?

Clone the repo, then open examples/browserified/index.html and see a working version of YoastSEO.js in my browser.

## What happened instead?

It didn't work. It looks like there's no CSS and JS in dist/ which the index.html requires.

If I have to do something magic to populate dist/ can you please include that in README.md or put a readme in the examples subdir?

Btw, I thought maybe it had something to do with these instructions from your readme:

    npm install https://github.com/Yoast/YoastSEO.js#develop

However these errored out when done either from within or outside the repo. So basically I'm confused. 

## How can we reproduce this behavior?

Clone the repo fresh. Open examples/browserified/index.html in your browser. Witness its not-working-ness.

## Technical info

* Platform: Standalone
* Platform version: n/a
* Yoast SEO version: just cloned the repo a minute ago

**Comment by Xyfi** [comment]
In order to run the example you first have to build the project.

1. Make sure you have `npm` or yarn` installed.
2. Install `grunt`globally (`npm install -g grunt` or `yarn add global grunt`).
3. From the root of the project run: `grunt build`.

After that the example should function and the `dist` folder should contain the javascript bundle.

**Comment by alexbayleaf** [comment]
Thank you!

I think there might be a step missing though?


[alex@rebelgirl YoastSEO.js (develop)]$ npm install -g grunt
/usr/local/bin/grunt -> /usr/local/lib/node_modules/grunt/bin/grunt
+ grunt@1.0.1
added 92 packages in 6.92s
[alex@rebelgirl YoastSEO.js (develop)]$ grunt build
grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started

**Comment by Xyfi** [comment]
Hmm, it is part of the dev dependencies. Have you installed the dependencies using `npm install`?

**Comment by alexbayleaf** [comment]
I'm sorry, you're going to have to spell that out for me.

If you mean "npm install -g grunt" then yes, I just ran that.

If you mean "npm install https://github.com/Yoast/YoastSEO.js#develop" then I get this error message:

[alex@rebelgirl YoastSEO.js (develop)]$ npm install https://github.com/Yoast/YoastSEO.js#develop
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "yoastseo" under a package
npm ERR! also called "yoastseo". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alex/.npm/_logs/2017-08-09T08_48_22_223Z-debug.log

**Comment by Xyfi** [comment]
No just `npm install` without any other arguments, that installs all packages that are defined in `package.json`.

**Comment by alexbayleaf** [comment]
Ah, thank you! I'm not familiar with npm, so I didn't realise I was 
meant to do that.

"grunt build" now works, and the browserified page works for me. Hurrah!

Thank you for your help.

A.

**Comment by Xyfi** [comment]
@alexbayleaf No problem, glad to help. I have created an issue #1221 to address your issue in the future. Take care!
