### ISSUE TITLE
Page analysis: word count is inaccurate

### ISSUE THREAD

**Issue by diedexx** [Yoast/YoastSEO.js#124]
The word count of the page analysis is inaccurate when the content contains certain values.

The page analysis tells me that the text contains:
- 2 words when the content contains only one word (with or without whitespace).
    (the word count is only one off if it is calculated by the client side javascript. It shows the right amount after a refresh). e.g. "Word"
- 1 word (I expect 0 words once the point mentioned above is fixed) when entering a number followed by 2 spaces, dashes or commas. e.g. "12  "
- 3 words when entering a letter or word followed by two spaces. e.g. "Word  "

This issue occurs when creating and editing Post, Pages and Locations (Local SEO).

Using:
- Wordpress version 4.3.1
- Yoast SEO (branch 3.0) using all default setttings
- Google chrome

Other active plugins and themes:
- Local SEO for Yoast SEO (1.3.8)
- WordPress SEO News (2.2.5)
- Twenty Fifteen

**Comment by terw-dan** [comment]
this seems to go wrong when editting in tinyMCE.

**Comment by tacoverdo** [comment]
Possibly related to this issue:
The `more`-tag is counted as word.
![edit_post_ _wpbeta_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/11091519/73320632-887b-11e5-83fe-5bc784e87028.png)
