### ISSUE TITLE
Readability should exclude the text inside <code> </code>

### ISSUE THREAD

**Issue by benvaassen** [Yoast/YoastSEO.js#1245]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/wordpress-seo/blob/trunk/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
The readability count text in `<code>` brackets. Since code often starts with the same word, and obviously has no transition words, it leads to bogus results.

### Please describe what you expected to happen and why.
The text in `<code>` tags should not count towards readability.

### How can we reproduce this behavior?
1. Write some code inside `<code>` tags
2. Check readability score.

### Technical info
* WordPress version: 4.8.2
* Yoast SEO version: 5.5

**Comment by IreneStr** [comment]
See https://github.com/Yoast/YoastSEO.js/pull/1113 for inspiration

**Comment by manuelaugustin** [comment]
Related to #1051

**Comment by Xyfi** [comment]
Community patch #1259 still needs to be acceptance tested, #1250 is merged.
