### ISSUE TITLE
User's Role Language fails to highlight transition words

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/YoastSEO.js#1246]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/wordpress-seo/blob/trunk/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

German transition words not detected when site language English BUT user role is German

### Please describe what you expected to happen and why.

Even though my user language is in German I expected the transition words to be highlighted

### How can we reproduce this behavior?
**1.Add a post**

**2. Add some German transition words perhaps in a sentence like "Schließlich ist das Templatedesign ein musterbasiertes Modell für zukunftsorientierte Softwareanwendungen."**

**3. Set site language to English and User Language to German**

![1](https://user-images.githubusercontent.com/8238074/29718644-758c62ca-8981-11e7-90d0-8b12635b4b43.png)

**4.See transition words not highlighted**

![2](https://user-images.githubusercontent.com/8238074/29718660-8465fc3e-8981-11e7-89b0-e28bf61eed9b.png)

**5.Switch site language to German**

![screen shot 2017-08-25 at 10 38 45 am](https://user-images.githubusercontent.com/8238074/29718687-99f3de86-8981-11e7-9d39-a480d5244474.png)

**6.See transition words highlighted**

![3](https://user-images.githubusercontent.com/8238074/29718735-bbc6cd16-8981-11e7-86d6-7d0e91c3c7c6.png)

### Technical info
* WordPress version: 4.8.1
* Yoast SEO version: 5.3.2
* Relevant plugins in case of a bug:

**Comment by atimmer** [comment]
This is intended behaviour. We want to analyse the language of the content. We use the site language for this because that is also what is used to translate frontend WordPress content.
