### ISSUE TITLE
Clarification editable fields (snippet)

### ISSUE THREAD

**Issue by diedexx** [Yoast/YoastSEO.js#125]
<img width="694" alt="screen shot 2015-11-03 at 12 15 21" src="https://cloud.githubusercontent.com/assets/5352634/10907248/c2227e4c-8228-11e5-9dde-d87c459ef282.png">

It isn't clear that users can edit these fields without hovering over one of them. 

Showing the edit/pencil icon with low opacity might help the user out. 
<img width="595"  alt="screen shot 2015-11-03 at 12 47 49" src="https://cloud.githubusercontent.com/assets/5352634/10907286/1ed88da2-8229-11e5-9136-29a50d620c39.png">

Or maybe consider adding (greyish) labels in front of the fields.

Using:
- Wordpress version 4.3.1
- Yoast SEO (branch 3.0) using all default setttings
- Google chrome

Other active plugins and themes:
- Local SEO for Yoast SEO (1.3.8)
- WordPress SEO News (2.2.5)
- Twenty Fifteen

**Comment by atimmer** [comment]
This has been fixed in 1.1 with a completely redesign snippet editor.
