### ISSUE TITLE
30% transition words is too high for German text

### ISSUE THREAD

**Issue by gmmedia** [Yoast/YoastSEO.js#1254]
## What did you expect to happen?
The  readability analysis wants 30% of the sentences with transition words. That's mostly too high for a German text.

Let us change choose between 20% and 30%.

## What happened instead?
We have to change the text in a very artificial way. That makes the text worse then better.

## How can we reproduce this behavior?
Write a good German article an it will be most likely below the 30%.

## Technical info

* Platform: WordPress latest
* Yoast SEO version: WordPress latest

**Comment by IreneStr** [comment]
@gmmedia Thank you for your feedback.

The transition word assessment is the assessment for which it is the hardest to turn a red/orange bullet into a green bullet. Like you wrote, trying to increase the percentage of transition words by making changes to the first version of your post often results in artificial sounding sentences/paragraphs.

But actually, you don't have to have a green bullet for all assessments for your post to be readable. It's similar to what we recommend for our SEO analysis here: https://yoast.com/want-green-bullet-wp-seo/. As long as your overall score is green, you shouldn't worry too much about making big changes to your text. One orange bullet doesn't mean that your text is hard to read. However, keep the orange and red bullets from your previous texts in mind when you write future texts. So the next time you write, it might help to keep an eye on the transition words during the process of writing.

**Comment by gmmedia** [comment]
The problem is that the overall score is red!

Its a nice feature, but at the moment I have to deactivate it on most of the sites, because of the red bullet on well optimized articles.

The feature makes only sense, if it is possible to get a green bullet, on a good article. Not red and not orange.

The screen shows the result of a 4000 word article.
1. The red dot is because of code blocks. see issue https://github.com/Yoast/YoastSEO.js/issues/1245
2. Its a technical article. I can not get to flesch 60.
3. It makes no sense to write German article with 30% transition words

![2017-10-02_134210](https://user-images.githubusercontent.com/7474702/31187972-c8badd4c-a933-11e7-8f36-04fb7c3f38fe.png)
