### ISSUE TITLE
Sentence highlighting not working for: "The text contains 4 consecutive sentences starting with the same word. Try to mix things up!"

### ISSUE THREAD

**Issue by Xyfi** [Yoast/YoastSEO.js#1263]
## What did you expect to happen?
I expected the app to show me where the problem was by highlighting it.

## What happened instead?
No highlights appeared.

## How can we reproduce this behavior?
1. Create a post with the following content:
```
I want to do this. I want to do that. I want to do something else. I did a thing.
```
2. In the readability analysis click the highlight button for the following readability score: `The text contains 4 consecutive sentences starting with the same word. Try to mix things up!`.
3. No highlights should show up.

## Technical info

* Platform: WordPress
* Platform version: 4.8
* Yoast SEO version: 1.21

**Comment by monbauza** [comment]
Please inform the customer of conversation # 255200 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 254976 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 280439 when this conversation has been closed.

**Comment by PatrickYoast** [comment]
Please inform the customer of conversation # 398051 when this conversation has been closed.

**Comment by mayada-ibrahim** [comment]
Please inform the customer of conversation # 415937 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 424363 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 428054 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 429630 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 455151 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 455777 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 456982 when this conversation has been closed.

**Comment by igorschoester** [comment]
Rechecked this with Yoast SEO 9.6 and it works.

Check this in Chrome. With the block editor (Gutenberg and classic editor (plugin).

**Comment by Nantris** [comment]
I'm seeing exactly this issue in Gutenberg. All the text highlights for the other features work, except for this one:

`Consecutive sentences: The text contains 4 consecutive sentences starting with the same word. Try to mix things up!`

**Comment by G-kodes** [comment]
I have also seen this issue in the new Gutenburg editor. Funnily enough when I artificially create one such sentence:
```
I want to do this. I want to do that. I want to do something else. I did a thing.
```
**THEN** it picks it up as a second instance but the first still doesn't highlight.
