### ISSUE TITLE
URL representation in mobile snippet preview should match breadcrumb style.

### ISSUE THREAD

**Issue by omarreiss** [Yoast/YoastSEO.js#1267]
Today I did a lot of mobile Googling (Google.com, via US VPN)

I noticed the breadcrumb style url representation and could infer truncation logic as well:

### Not truncated

<img width="406" alt="screen shot 2017-10-18 at 15 55 58" src="https://user-images.githubusercontent.com/1488816/31723237-9cc5aabe-b41e-11e7-8f76-de3bd7da5f72.png">

### Truncated in the middle

<img width="406" alt="screen shot 2017-10-18 at 15 56 36" src="https://user-images.githubusercontent.com/1488816/31723239-9cf72bd4-b41e-11e7-8b07-895efe28689d.png">

### Truncated at the end

<img width="407" alt="screen shot 2017-10-18 at 15 58 30" src="https://user-images.githubusercontent.com/1488816/31723241-9d326dd4-b41e-11e7-81bb-c5b844d45f75.png">

@jdevalk do you agree we should implement this?

**Comment by omarreiss** [comment]
Related #1196

**Comment by omarreiss** [comment]
@moorscode noticed the protocol is stripped for non-https urls.

**Comment by jdevalk** [comment]
I agree.

**Comment by omarreiss** [comment]
Obsolete
