### ISSUE TITLE
Snippet preview is confusing for a screenreader

### ISSUE THREAD

**Issue by atimmer** [Yoast/YoastSEO.js#127]
For example, in the following screenshot the screenreader will just say "Twitter analytics, twitter analytics, twitter analytics" without it being clear what's it all about.
<img width="529" alt="screen shot 2015-11-03 at 16 12 46" src="https://cloud.githubusercontent.com/assets/584693/10911565/bcbad1b2-8245-11e5-94ae-6eadd3afea3d.png">

**Comment by atimmer** [comment]
@afercia How is this with the new snippet editor?

**Comment by afercia** [comment]
@atimmer it really depends on which browser and screen reader are used, see what Firefox and NVDA read out here: https://github.com/Yoast/wordpress-seo/issues/4134

For sure the three preview items need to be labeled.
