### ISSUE TITLE
Support plural forms [i18n]

### ISSUE THREAD

**Issue by omarreiss** [Yoast/YoastSEO.js#128]
Currently we have no way to support plurals since we initialize the strings in the config without context.

Jed has support for plurals, but we need to bring the strings to the place where they are actually used.

**Comment by omarreiss** [comment]
Some context from a WP perspective: https://codex.wordpress.org/I18n_for_WordPress_Developers#Plurals

**Comment by atimmer** [comment]
This has been covered with the assessments refactoring.
