### ISSUE TITLE
Prominent keywords are html code

### ISSUE THREAD

**Issue by pmbrix** [Yoast/YoastSEO.js#1284]
I have used shortcode for collapsing content in a section. SEO Yoast is displaying html code in stead of prominent words. Everytime I remove the section with the shortcode in it, then prominent words appear as expected, when I paste it back in it becomes as the preview shows.

## What did you expect to happen?
Keywords in article should appear
## What happened instead?
Html code appeared
![screen shot 2017-11-07 at 16 39 28](https://user-images.githubusercontent.com/33354887/32502152-4aa0a786-c3da-11e7-8eb1-ac1934b70730.png)
## How can we reproduce this behavior?
reproduce error by adding the collapse content plugin in article with normal copy content, and see how prominent words section changes

## Technical info
* Platform: WordPress  4.8.3
* Platform version: Unyson page Builder 2.7.9
* Yoast SEO version: 5.7.1
* Collapse Content plugin version Version 1.1.6 by wpshopmart

**Comment by Djennez** [comment]
This analysis has since been removed / changed, there have since also been a lot of changes to the way that shortcodes are being handled. 

Because this issue is outdated I will close it. If related issues arise, please submit them via new issues.
