### ISSUE TITLE
Implement updating content assessment

### ISSUE THREAD

**Issue by Michelle2403** [Yoast/YoastSEO.js#1295]
Description
This check is meant to warn users that their cornerstone content needs to be updated. This is a new check. The check only focuses on cornerstone content posts for now. Once these posts haven't been updated for 6 months, a notification in the notification center should be triggered. 

Boundaries
Trigger notification if a cornerstone content article hasn't been updated for 6 months. 

Feedback
Your cornerstone content post %1$s% hasn't been updated for 6 months.

**Comment by atimmer** [comment]
@Michelle2403 Should this only result in a notification in the notification center or also an assessment in the feedback under the post?

**Comment by Michelle2403** [comment]
This should only result in a notification in the notification center, so I just learned that 'assessment' is not the right name for this and that it might be a confusing issue this way. But for now, @IreneStr will know what to do with this one ;)

**Comment by IreneStr** [comment]
Moved to https://github.com/Yoast/wordpress-seo/issues/8309
