### ISSUE TITLE
Implement single H1 assessment

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#1298]
### Description
This assessment should check if a Paper only has one H1: the title (for posts and pages) or the name (for tags and categories). This check should be implemented for both posts, pages, tags and categories. 

### Boundaries
- More than one H1: bullet = red, score = 3.
- Only one H1: no score.

### Feedback
Your text contains more than one H1. Change all H1s in the body of your text to the appropriate heading level.

`appropriate heading level` should link to a KB article about heading levels and about why you shouldn't have more than one H1.

NB. Maybe we should write separate feedback strings for each type (posts, pages, tags and categories) to increase clarity.

**Comment by afercia** [comment]
for inspiration, see also the discussion on a similar issue for Gutenberg: https://github.com/WordPress/gutenberg/pull/4238

- more than 1 H1 is always incorrect
- one single H1: they check for the title first and if there's one, the warning message is: "Your theme _may_ already use a H1 for the post title"

**Comment by manuelaugustin** [comment]
Ah, that's great information. Thank you!
