### ISSUE TITLE
Implement taxonomy internal linking assessment

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#1299]
### Description
This assessment should check if taxonomies contain one or more internal links. This check should be implemented for tags and categories. 

### Boundaries
- One or more **internal** links: bullet = green, score = 9.
- No **internal** links: bullet = red, score = 3.

### Feedback
Red bullet: Your text doesn't contain any internal links. Consider adding some as appropriate.
Green bullet: Your text contains %1$d% internal link. / Your text contains %1$d% internal links.

**Comment by manuelaugustin** [comment]
This issue has been moved to https://github.com/Yoast/wordpress-seo/issues/9076
