### ISSUE TITLE
Analysis doesn't update when removing text by cutting

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/YoastSEO.js#130]
**Problem description and steps to reproduce**
* Create a new post
* Enter a title
* Write a text in the content area
* Check the content analysis. E.g. 
![edit_post_ _wpbeta_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/10936609/ff35c882-82ed-11e5-901e-7d37fd5aaa80.png)
* Select all the text in the content area and cut it (Cmd+X / Ctrl+X)
* Check the content analysis. E.g. 
![edit_post_ _wpbeta_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/10936655/4782e4c6-82ee-11e5-92d4-893de95ec6e1.png)
* Type any character in the content area
* The content analysis should now have updated.

**Tested versions**
WordPress 4.4-beta-2
Yoast SEO 3.0-beta-4

**Comment by terw-dan** [comment]
This is actually working, but tinyMCE takes incredibly long to fire a change event when a text is cut (seems to take up to 3 seconds).
