### ISSUE TITLE
Improve keyword density assessment

### ISSUE THREAD

**Issue by manuelaugustin** [Yoast/YoastSEO.js#1309]
### Description
- The upper boundary should be linked to combination length; it should be higher for more common (shorter) combinations and lower for less common (longer) combinations.
- The upper boundary for the keyword density is raised from 2.5% to 3% (`more than maximum`) and from 3.5% to 4% (`way more than maximum`), respectively.

### Formula

`(keyphrase_frequency / word_count) * 100 * (0.7 + keyphrase_length / 3)`

- `keyphrase_frequency / word_count * 100` is the base formula we've bee using so far. It expresses the keyphrase density in a percentage.

- To this formula a weight was added. The weight consists of the base (0.7), to which a specific weight for the keyphrase length (1/3) is added. These values were obtained by looking at sample texts and reverse-engineering a formula that yields  results which reflect a natural keyword density

### Boundaries
- `way more than maximum`: density > 4%
- `more than maximum`: 3% < density ≤ 4%
- `good`: 0.5% < density ≤ 3%
- `under minimum`: 0% < density ≤ 0.5% _or_ if they keyphrase is used only once in the text

*all of these numbers refer to rounded keyword density

### Feedback
- `way more than maximum`: They keyphrase was found %1$d% times, which is way more than the advised maximum of %2$d% times for a text of this length.
- `more than maximum`: They keyphrase was found %1$d% times, which is more than the advised maximum of %2$d% times for a text of this length.
- `good`: The keyphrase was found %1$d% times, which is great for a text of this length.
- `under minimum`: They keyphrase was found %1$d% times, which is under the recommended minimum of %2$d% times for a text of this length.

### Miscellaneous
- The user should be able to mark the keyword in the text.
- In order to make the feedback not overly complicated, the keyword density percentages should be dropped. Instead, we will provide feedback about the number of times the feedback has been used and how many times it should be used.

**Comment by atimmer** [comment]
@manuelaugustin Could you explain how that formula works? It is non-obvious so we should explain why it is this way.

**Comment by manuelaugustin** [comment]
@atimmer Thanks for the comment! I've added an explanation for the formula.

**Comment by manuelaugustin** [comment]
Update: `more than maximum` should be set to orange instead of red.
