### ISSUE TITLE
Add link to competing links explanation article

### ISSUE THREAD

**Issue by PatrickYoast** [Yoast/YoastSEO.js#1316]
## Description
- To explain the competing links check better we need to link it to a blog post that covers competing links more in depth.

## Miscellaneous
- This article still needs to be written.

**Comment by CarolineGeven** [comment]
@PatrickYoast Did you already let the content team know there has to be a blog post about this? We can't fix this issue until the article is there.

**Comment by PatrickYoast** [comment]
@CarolineGeven Yes, we did. Edwin has planned a post called _Why you should not use your focus keyword more than once._  for the December 18th.

**Comment by manuelaugustin** [comment]
This falls under the wider scope of this issue: https://github.com/Yoast/YoastSEO.js/issues/1389
