### ISSUE TITLE
Edge case: 70 character title

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/YoastSEO.js#132]
When a title is 71 (or above) characters long, the content analysis returns:
`The page title contains 71 characters, which is more than the viewable limit of 70 characters; some words will not be visible to users in your listing.`

When a title between 40 and 69 characters, the content analysis returns:
`The page title is more than 40 characters and less than the recommended 70 character limit.`

However, when a title is exactly 70 characters long, the content analysis currently returns:
`The page title is more than 40 characters and less than the recommended 70 character limit.`
This is technically incorrect, as the title isn't less than the character limit, but exactly at the limit.

**Comment by tacoverdo** [comment]
The same issue occurs when the title is exactly 40 characters long. The content analysis then returns:
`The page title is more than 40 characters and less than the recommended 70 character limit.`
This is technically incorrect, as the title isn't more than 40 characters.

**Comment by omarreiss** [comment]
Fixed in https://github.com/Yoast/YoastSEO.js/commit/70515ecc0cf007e537910c95dce7d356eb1f49bb#diff-ffb95bbad54882c7cac8c27d8d409913R325
