### ISSUE TITLE
Error: Cannot find module './js/bundledPlugins/previouslyUsedKeywords'

### ISSUE THREAD

**Issue by timberlands** [Yoast/YoastSEO.js#1321]
## What did you expect to happen?
Me to run the app provided in the README

## What happened instead?
I got an error: Error:` Cannot find module './js/bundledPlugins/previouslyUsedKeywords'`

## How can we reproduce this behavior?
2246  sudo npm init
2248  sudo npm install https://github.com/Yoast/YoastSEO.js#develop
2252  sudo nano index.js
2253  node index.js

**Comment by CarolineGeven** [comment]
Thank you for reporting this issue. We've confirmed that the build is not working properly. We'll fix this as soon as possible and update the readme.

**Comment by timberlands** [comment]
FWIW, I installed the package through `npm install yoastseo` and it seems to be working

**Comment by IreneStr** [comment]
@timberlands Sorry for this very late reply. `npm install yoastseo` should do the trick, indeed. I'm going to change the instructions it in the readme.
