### ISSUE TITLE
Incorrect Warning "Please create an SEO title." On Additional Keywords

### ISSUE THREAD

**Issue by amboutwe** [Yoast/YoastSEO.js#1330]
## What did you expect to happen?
Additional keywords would use the same SEO Title

## What happened instead?
Duplicate title test and conflicting messages.

## How can we reproduce this behavior?

1. Edit a page or post. I used the static front page and a post to reproduce the issue.
2. Add two or more focus keywords.
3. First keyword recognizes the SEO title exists.
4. Switch to second (or third, etc) keyword and get wrong title warning.

## Technical info

* Platform: WordPress
* Platform version: 4.9.1
* Yoast SEO version: 5.9.1 premium

![selection_292](https://user-images.githubusercontent.com/8060612/33789179-024ddf54-dc34-11e7-993c-65dd999ab67f.png)

![selection_291](https://user-images.githubusercontent.com/8060612/33789184-05ef4ddc-dc34-11e7-9d34-adac5b88360d.png)

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 273686 when this conversation has been closed.

**Comment by suascat** [comment]
Please inform the customer of conversation # 274779 when this conversation has been closed.

**Comment by CarolineGeven** [comment]
This bug is fixed in the latest release.

**Comment by suascat** [comment]
Issue reappeared while tested in the latest platforms:

TwentySeventeen: 1.6
Yoast SEO Premium: 7.6.1
WordPress: 4.9.6

**Comment by suascat** [comment]
Please inform the customer of conversation # 382455 when this conversation has been closed.

**Comment by CarolineGeven** [comment]
Closing as the issue mentioned is not the same as this issue. Please create a new issue.

**Comment by benvaassen** [comment]
New issue created here: https://github.com/Yoast/YoastSEO.js/issues/1532
