### ISSUE TITLE
Quit 'edit mode' of snippet preview by pressing enter

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/YoastSEO.js#134]
**Problem description**
The 'edit mode' of the title in the snippet preview can be entered by either clicking the title or going to the field by tab. This is superb.

However, the 'edit mode' of the title in the snippet preview can only be left by clicking outside of the input field or tabbing away. Pressing enter to save the changes feels more intuitive, but doesn't do anything at the moment.

**Possible solution**
Remove focus from the input field when pressing enter to give it a 'submit' feel.

**Tested versions**
WordPress 4.4-beta-2
Yoast SEO 3.0-beta-4

**Comment by atimmer** [comment]
The platform implementing YoastSEO.js can wrap the snippet editor in a form and the form will be submitted on enter.
