### ISSUE TITLE
Mark button is missing for the competingLinksAssessment result

### ISSUE THREAD

**Issue by andizer** [Yoast/YoastSEO.js#1340]
## What did you expect to happen?
A button for marking the competing links.

## What happened instead?
No button being shown.

## How can we reproduce this behavior?
Create two post with a link to each other. Then have for both posts the same keyword being set.

## Technical info
![edit_post_ _local_wordpress_dev_ _wordpress](https://user-images.githubusercontent.com/325040/34045184-2c17bc3c-e1a8-11e7-9572-41284323d60a.png)

![edit_post_ _local_wordpress_dev_ _wordpress](https://user-images.githubusercontent.com/325040/34045237-4d13d45c-e1a8-11e7-994c-4945151af69c.png)

* Platform: WordPress
* Platform version: 4.9
* Yoast SEO version: 5.9

**Comment by afercia** [comment]
First time looking into how this works so please bear with me if I'm missing something. Not sure if this is a bug or a feature request 🙂  As far as I see, the various assessments return an object that contains a score, a hasMarks property, and a text for the assessment. `PreviouslyUsedKeyword` returns just a score and text, there's no `hasMarks` so seems it's a "feature"?

**Comment by Xyfi** [comment]
The assessment described in the issue seems to be the `previouslyUsedKeywords` assessment and not the `competingLinksAssessment`.
