### ISSUE TITLE
Assessments containing Nan% are not considered errors

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#1344]
## What did you expect to happen?
Assessments with unintended results should be considered errors.

## What happened instead?
It's considered a consideration.
<img width="591" alt="schermafbeelding 2017-12-13 om 14 57 57" src="https://user-images.githubusercontent.com/17744553/34157401-ae2eb3c6-e4c1-11e7-8598-9a423472566f.png">

## How can we reproduce this behavior?
Pass something to the passive voice assessment that is NaN. We should investigate whether this incorrect classification happens for all assessments, or only the passive voice assessment.

## Technical info

* Platform: WordPress
* Platform version: develop
* Yoast SEO version: develop

**Comment by jcomack** [comment]
FYI: Just tested this with Video SEO and I got the same result. The only content in my post was a video (see screenshot).

<img width="739" alt="edit_post_ _acceptance_test_ _wordpress" src="https://user-images.githubusercontent.com/4181340/34942914-b5763b7a-f9f9-11e7-83a6-3b8c8e8cae2d.png">
