### ISSUE TITLE
site language related error in readability analysis

### ISSUE THREAD

**Issue by CarolineGeven** [Yoast/YoastSEO.js#1353]
Original bug report: https://github.com/Yoast/wordpress-seo/issues/8558

--

* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/wordpress-seo/blob/trunk/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

After last yoast update(or maybe 1 before), 2 error warnings appeared in the Analysis tool, in all posts of my site.

1st error message is in “keyword” section:

>    Errors(1)
    An error happened in ‘keywordDensity’ evaluation

This error message is after a grey point.
Previously I had green points followed by keyword data, due to proper keyword usage.

2nd error message is in “readability” section:

>    Errors(1)
    An error happened in ” ‘textSentenceLength’ evaluation

Previously I had green points followed by the data.

All other functions of the Analysis tool are in good order.

### Please describe what you expected to happen and why.
Troobleshooting results:
During troubleshooting process I found no plugin or theme conflict, but successfully localized the source of the problem at other fields.
I guess it is related to languages (maybe) using other letters than English.( i.e. ü,ö,ä, ect.)

The problem is strictly related to language setting of the WordPress site. (Checked on different sites.)

After last update a notice have appeared on the yoast panel “Readability” section,
stating the set language of the site:
“Your site language is set to Magyar.Change language”
Previously there was no such statement and the language of yoast evaluation was English.

So I also checked this new feature – as potential error source – and found the error.

If I switch my site language to English the errors disappear and all functions are OK.
If I switch it to my language (Hungarian) the error messages appear again.

Link in topic: https://wordpress.org/support/topic/analysis-error-keyworddensity-after-update/#post-9815426
### How can we reproduce this behavior?
1. Set the site language to Hungarian.
2. Above mentioned error message will appear on all previous posts.
3. Switch site language to English and errors will disappear.

### Technical info
* WordPress version:4.9.1
* Yoast SEO version: 6.0
* Relevant plugins in case of a bug: no plugin or theme conflict!
Tech data:
```
# SITE_URL:   https:/www....................hu
# IS MULTISITE :          No

# THEME | VERSION :       Hueman | v3.3.25
# WP VERSION :            4.9.1.
# PERMALINK STRUCTURE :   /%category%/%postname%/
# 9 ACTIVE PLUGINS :
                          - AdSense Integration WP QUADS (version 1.7.4)
                          - Akismet Anti-Spam (version 4.0.2)
                          - Exit Popup (version 1.6)
                          - Google Analytics Dashboard for WP (GADWP) (version 5.1.2.5)
                          - Hueman Addons (version 2.0.15)
                          - Limit Login Attempts (version 1.7.1)
                          - Super Socializer (version 7.9.7)
                          - WP-PageNavi (version 2.92)
                          - Yoast SEO (version 6.0)

# PHP Version:            5.6.32
# MySQL Version:          10.1.18-MariaDB
# Web Server Info:        Apache

# WordPress Memory Limit: 40MB
# PHP Memory Limit:       256M
# PHP Upload Max Size:    2M
# PHP Post Max Size:      8M
# PHP Upload Max Filesize:2M
# PHP Time Limit:         30
# PHP Max Input Vars:     1000
# PHP Arg Separator:      &
# PHP Allow URL File Open:Yes
# WP_DEBUG:               Disabled

# Show On Front:          posts
# Page On Front:          (#0)
# Page For Posts:         (#0)
```

**Comment by CarolineGeven** [comment]
For the developer working on this, there are several console errors related to the locale, for example:
```
index.es.js:670 [React Intl] Error formatting message: "content-analysis.highlight" for locale: "hu_HU", using default message as fallback.
Error: Locale data added to IntlMessageFormat is missing a `pluralRuleFunction` for :hu_HU
formatMessage @ index.es.js:670
index.es.js:670 [React Intl] Error formatting message: "content-analysis.language-notice" for locale: "hu_HU", using default message as fallback.
Error: Locale data added to IntlMessageFormat is missing a `pluralRuleFunction` for :hu_HU
formatMessage @ index.es.js:670
index.es.js:679 [React Intl] Missing message: "a11yNotice.opensInNewTab" for locale: "hu_HU", using default message as fallback.
```

**Comment by Xyfi** [comment]
If you want to select Hungarian as the site language, choose **Magyar** from the dropdown list.

**Comment by Xyfi** [comment]
The bug is caused by an incorrectly formatted translation on Glotpress. See https://translate.wordpress.org/projects/wp-plugins/wordpress-seo/stable/hu/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=4052125&filters%5Btranslation_id%5D=53274472.

I proposed an edit and have informed the editor for Hungarian.

**Comment by Surbma** [comment]
I see, that the text is modified, but it is still not correct. And there were other texts also, that needed correction. I'm done with all these texts, so please accept the new recommended translation by me!

I'm a Hungarian editor of the WooCommerce plugin, so please add me as an editor to your plugin also to help moving forward in these kind of situations.

Thank you!

**Comment by Xyfi** [comment]
@Surbma I've contacted our support lead (@tacoverdo) with the question to look into your request.

**Comment by Surbma** [comment]
@tacoverdo Thank you very much!

**Comment by keymakerfx** [comment]
Any news on this bugfix? The ‘keywordDensity’ evaluation error persists as of today.

**Comment by keymakerfx** [comment]
I finished the Hungarian translation, it is waiting for approval. Could you please check it to see if this solved the problem @tacoverdo ? Thanks, cheers.

**Comment by bentlor** [comment]
The bug still exists, wp version 4.9.5 and plugin version 7.3 - when I set the language to Hungarian (Magyar), the keyword density and sentenceLength are broken. If I set it to English, readability (obviously) gets very low, which I can live with but is not convenient, especially as this was not an issue ~ 6 months ago.
