### ISSUE TITLE
Analyses seem to conflict

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/YoastSEO.js#136]
**Problem description**
Two checks seem to be stating the opposite of each other.

**Example**
<img width="818" alt="edit_post_ _wpbeta_ _wordpress" src="https://cloud.githubusercontent.com/assets/5147598/10969766/9c309c3e-83ca-11e5-9651-9107025c97d7.png">

**Tested versions**
WordPress 4.4-beta-2
Yoast SEO 3.0-beta-7

**Comment by omarreiss** [comment]
Fixed in https://github.com/Yoast/YoastSEO.js/pull/144
