### ISSUE TITLE
Sub headings Distribution Too Long assessment marker doesn't mark anything

### ISSUE THREAD

**Issue by afercia** [Yoast/YoastSEO.js#1360]
Create a post and be sure to have:
- one or more sub headings
- each sub heading followed by more than 300 words

You will get a readability assessment result with message:

`1 subheading is followed by more than the recommended maximum of 300 words. Try to insert another subheading.`

or plural:

`2 of the subheadings are followed by more than the recommended maximum of 300 words. Try to insert additional subheadings.`

The assessment has a marker button.
Click on the button, nothing gets highlighted.

Aside: language specific notes:
- I guess "another" should be "an other" /cc @jcomack 
- not sure about the difference between "Try to insert another subheading." vs. "Try to insert additional subheadings."

**Comment by Pcosta88** [comment]
@afercia I think this issue report here: https://github.com/Yoast/YoastSEO.js/issues/1195 matches the marker button issue you found.

**Comment by afercia** [comment]
@Pcosta88 👋 oh yes, it's the same issue. Closing as duplicate of #1195

**Comment by Pcosta88** [comment]
@afercia The langauge specific notes you mentioned should be addressed. Can you create a new issue with those notes?

**Comment by afercia** [comment]
Reported on #1195
