### ISSUE TITLE
Focus keyword isn't recognized in the first paragraph

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#1380]
Copied from https://github.com/Yoast/wordpress-seo/issues/5803#issuecomment-357237159

### What did you expect to happen?
Did not expect to get this error message as the focus keyword IS in the first paragraph.

 ![yoast](https://cloud.githubusercontent.com/assets/22657366/19148527/75fa81dc-8bbd-11e6-8e4e-9fbc159701f0.jpg)

Using Version 3.6.1. Now you have mentioned the text view I'm thinking that having an image there is causing the problem. See attached. The keyword is underlined and is in the first paragraph of text but there is also an image, right aligned, which appears before the first paragraph when in text view. 
![yoast2](https://cloud.githubusercontent.com/assets/22657366/19234344/54471b6e-8eeb-11e6-95a5-96ef5a890cb6.jpg)

@terw-dan:
>My guess is the image is seen as the first paragraph, so the text with the focus keyword will be seen as the second paragraph. 
We'll have to look into this to see if there is a way to correctly check whether a paragraph only has an image and check for the first paragraph that contains text.

## Another report:
I have a similar issue. To get around storage capacity constraints on my server, I embed photos from SmugMug in my featured photos posts. The embed code is placed above the copy, so I always get the message "The focus keyword doesn't appear in the first paragraph of the copy. Make sure the topic is clear immediately." 

See the attached screenshot for an example from an upcoming post, where my keyword phrase is colored powder for Diwali.
<img width="795" alt="screen shot 2017-01-23 at 3 28 36 pm" src="https://cloud.githubusercontent.com/assets/7452599/22196634/bc1e28a8-e180-11e6-9798-835467144a27.png">

**Comment by IreneStr** [comment]
Please inform the customer of conversation # 180740 when this conversation has been closed.

**Comment by Dushanthi** [comment]
I had the same, my focus keyword was "pinkeltje"

```<strong>Heb jij als kind Pinkeltje gelezen? Volgens onderzoek naar taalniveau zou je dat helemaal niet kunnen. <em>Pinkeltje</em> is namelijk veel te moeilijk voor kinderen vanwege de lange zinnen. Maar klopt dat wel?</strong>

Volgens <a href="https://www.texamen.nl/" target="_blank" rel="noopener noreferrer">Texamen</a> zijn de lange zinnen in Dick Laans <em>Pinkeltje </em>geschreven op C1: het een-na-hoogste taalniveau. Dat betekent dat kinderen deze verhalen helemaal niet zouden kunnen lezen. Later herschreef Corrie Hafkamp de boekenreeks in kortere zinnen. Maar was dat nou echt nodig? Want bestaat er wel zoiets als ‘de ideale zinslengte’?

Een korte zoektocht op internet levert verschillende resultaten op. Volgens het ene blog is de ideale zin 10 woorden. Volgens het andere 25 woorden. Weer een andere site raadt aan: gebruik afwisselend zinnen tot 10 woorden en zinnen tot 40 woorden. En allemaal claimen ze dat dit de zinslengte is die je het best aan kunt houden. Maar waar komen deze vuistregels vandaan? En belangrijker: welke klopt?
<h2><strong>Even de boeken induiken</strong></h2>
Volgens het Referentiekader Taal (2009) en Siegfried Vögele is de ideale gemiddelde(!) zin 10 woorden lang. Leuk bedacht, maar hun uitspraken zijn nooit bewezen. <a href="https://www.diatoetsen.nl/onderzoek-ontwikkeling/publicaties/" target="_blank" rel="noopener noreferrer">Hacquebord en Lenting-Haan (2012)</a> deden wél wetenschappelijk onderzoek naar zinslengte. Hun conclusie is dat niet één, maar vier lengtefactoren een rol spelen om een tekst beter leesbaar te maken:
<ul>
 	<li>Kortere zinnen</li>
 	<li>Minder deelzinnen (alle delen van een zin met een werkwoord)</li>
 	<li>Minder woorden tussen het onderwerp en de persoonsvorm</li>
 	<li>Minder woorden tussen het lijdend voorwerp en de persoonsvorm.</li>
</ul>
Hartstikke duidelijk! Maar hoe zit het dan met variatie van zinslengtes? Achter deze vuistregel zit enige wetenschap. Bouman (2006) schrijft dat variatie in zinslengte belangrijk is. En volgens onderzoek van <a href="https://www.jstor.org/stable/811054?seq=1#page_scan_tab_contents" target="_blank" rel="noopener noreferrer">Wolfington (1963)</a> zou je per tien zinnen een verhouding van 2:6:2 aan moeten houden. Dat betekent:
<ul>
 	<li>Twee korte zinnen (tot 5 woorden)</li>
 	<li>Zes middellange zinnen (6-30 woorden)</li>
 	<li>Twee lange zinnen (meer dan 30 woorden).</li>
</ul>
<h2><strong>Zelf aan de slag</strong></h2>
Op zoek naar exacte richtlijnen? Naar <em>de</em> ideale zinslengte? Helaas, die bestaat niet. De beste lengte van een zin hangt af van het genre, de doelgroep en – niet onbelangrijk – de auteur. Zo zijn de zinnen van <a href="https://nl.wikibooks.org/wiki/Amerikaanse_literatuur/Nathaniel_Hawthorne" target="_blank" rel="noopener noreferrer">Nathaniel Hawthorne</a>, Jaaps favoriete schrijver, gemiddeld meer dan 36 woorden lang. Zou je hem daarom een belabberd schrijver noemen?

Het is dus niet mogelijk om eenduidig aan te geven hoeveel woorden de perfecte zin moet hebben. Dat betekent niet dat je zinslengte mag negeren. Er zijn enkele aspecten waar je zelf op kunt letten:
<ul>
 	<li><strong>Variatie is belangrijk.</strong> Zijn al jouw zinnen even lang? Of speel je een beetje met de lengte? Als je hierover onzeker bent, spreek je tekst dan eens hardop uit. Dan merk je direct of je tekst soepel loopt.</li>
 	<li><strong>Gebruik niet te veel woorden tussen het onderwerp of lijdend voorwerp en de persoonsvorm.</strong> Hiermee maak je je zin direct beter leesbaar.</li>
 	<li><strong>Pas je zinslengte aan je doelgroep aan.</strong> Hoe lager het taalniveau, hoe korter je zinnen gemiddeld zouden moeten zijn. Een voorbeeldje? Voor basisschoolleerlingen gebruik je wel veel korte zinnen, terwijl academici echt niet zitten te wachten op jip-en-janneketaal.</li>
</ul>
<h2>Laat los!</h2>
En tot slot: laat het idee los dat je alleen korte zinnen mag schrijven. Als je de juiste woorden kiest en let op de grammaticale structuur van een zin – bijvoorbeeld dat de lengte tussen onderwerp en persoonsvorm niet te lang is – kunnen ook lange zinnen best leesbaar zijn.

Want zeg nou zelf, de vorige zin was best goed leesbaar toch?```

**Comment by iamazik** [comment]
Please inform the customer of conversation # 327556 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 342617 when this conversation has been closed.

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/YoastSEO.js/issues/994

**Comment by iamazik** [comment]
Please inform the customer of conversation # 400534 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 404944 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 408736 when this conversation has been closed.

**Comment by laurasacco** [comment]
Please inform the customer of conversation # 413920 when this conversation has been closed.

**Comment by nataliashitova** [comment]
The first case was resolved in https://github.com/Yoast/YoastSEO.js/pull/1645. The fix will be available to the users together with the morphology.
