### ISSUE TITLE
Penalize image anchor text over-optimization 

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#1388]
Moved from https://github.com/Yoast/wordpress-seo/issues/7924#issuecomment-359184385

Yoast SEO looks for image anchor text and gives us a green bullet when there is 1 image that uses the focus keyword as an anchor text.

The problem is that there is no limit on how many images with that same anchor text you can use. This means that I could over-optimize my post easily by adding 10 images with the same anchor text without losing my green bullet.

Since a lot of images/screenshots are used in today's web, over-optimizing anchor text is something we need to prevent.

**Comment by manuelaugustin** [comment]
Update:
The check should be triggered when there are ≥5 images. The boundaries can be the same as for the keyword in subheadings assessment (min 30, max 75%).
