### ISSUE TITLE
YoastSEO.js with AngularJS 1.6.6 and summernote

### ISSUE THREAD

**Issue by abhisanand** [Yoast/YoastSEO.js#1396]
I've used YoastSEO with AngularJS 1.6.6 with summernote and it works smoothly until I upload an image, when an image is select the Whole browser freezes and crash, and work fine if i comment Yoast codes
* Platform: AngularJS 1.6.6 with summernote

**Comment by Xyfi** [comment]
Thanks for reporting this issue. 
Unfortunately we do not have enough information to reproduce this problem. Please follow [these guidelines](http://kb.yoast.com/article/180-how-to-write-a-good-bug-report) to improve your [bug report](http://kb.yoast.com/article/180-how-to-write-a-good-bug-report).

Also, it may help us a lot if you can provide a backtrace of the error encountered. [This gist](https://gist.github.com/jrfnl/5925642) will explain how to enable the backtrace in your website: https://gist.github.com/jrfnl/5925642

Thank you.
