### ISSUE TITLE
Support highlights in Visual Composer Classic mode and Backend Editor mode

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#1401]
## Classic mode
Currently, the highlights are not working in Visual Composer's Backend Editor mode.

### To reproduce
1. Install Visual Composer
2. Create a Page
3. Add blocks
4. Add Text. Be in Backend Editor Mode
5. Click an eye button. Nothing is marked.

![screen shot 2016-08-05 at 5 49 53 pm](https://cloud.githubusercontent.com/assets/8238074/17451474/1e70e680-5b35-11e6-8a81-e413681fb84f.png)

### To reproduce
1. Install Visual Composer
2. Create a Page
3. Add blocks
4. Add Text. Be in Classic Editor Mode
5. See that the preview icon picks-up text and Visual Composer Code

#### Current highlights
![screen shot 2016-08-05 at 5 54 36 pm](https://cloud.githubusercontent.com/assets/8238074/17451558/c1c4cf4a-5b35-11e6-89cb-96b3e72a366e.png)

#### Expected highlights
![screen shot 2016-08-05 at 5 55 36 pm](https://cloud.githubusercontent.com/assets/8238074/17451574/e4091fde-5b35-11e6-854a-03d80f525f4a.png)

## Original issue
The original bug report can be found here: https://github.com/Yoast/wordpress-seo/issues/5319. That issue shouldn't closed because of its large amount of please inform messages.

**Comment by tacoverdo** [comment]
@IreneStr Is this related to https://github.com/Yoast/YoastSEO.js/issues/1315?

**Comment by IreneStr** [comment]
Moved to the page builder overview issue https://github.com/Yoast/YoastSEO.js/issues/1315
/cc @tacoverdo
