### ISSUE TITLE
How can i create my custom language

### ISSUE THREAD

**Issue by tranleducduy** [Yoast/YoastSEO.js#1402]
I want to create my custom language,  but can't find how.
Pls help

* Platform:  Standalone

**Comment by manuelaugustin** [comment]
Hey! Thanks for your interest in helping us to improve Yoast SEO! We always appreciate help with the word lists we use for the internal linking feature. If you want you can add information about your language here: https://docs.google.com/forms/d/1jtny8kdpq9tNgifDAVjgc_nJr8o08h96_QiRdcJFPGY/edit

**Comment by tranleducduy** [comment]
I translated POT file. But how to apply to code?
thanks

**Comment by manuelaugustin** [comment]
If you want to help to translate the interface, you can have a look at https://translate.yoast.com/

**Comment by tranleducduy** [comment]
that means no way custom language?

**Comment by manuelaugustin** [comment]
To translate the interface, the only way to do this is the method described on  https://translate.yoast.com/
