### ISSUE TITLE
Refactor findTransitionWords researcher and assessment

### ISSUE THREAD

**Issue by igorschoester** [Yoast/YoastSEO.js#1408]
## What lead to this?
There are multiple issues with marks / highlights. When I started with Yoast/wordpress-seo#6525 I thought it would be an quick change. Instead I found the structure to implement this is not there right now. @atimmer, @IreneStr, @manuelaugustin and me talked about this and worked out the following as a first step to a solution.

## What is the issue?
The researcher will match according to 2 types of Transition Words: single and two part. Currently the whole sentence gets marked if a single or a two part transition is found. There are 2 problems with that:
1. The researcher does not return all the transition words.
2. The marking of a whole sentence is not clear enough for the user.

Currently the researcher returns:
```javascript
{
    totalSentences: 1,
    sentenceResults: [
        {
            sentence: "I don’t know whether it’s interesting because it’s big or it’s interesting because it’s beautiful.",
            transitionWords: [
                " whether it's interesting because it's big or "
            ]
        }
    ],
    transitionWordSentences: 1
}
```

## What do we want to mark?
When we take the sentence "I don’t know whether it’s interesting because it’s big or it’s interesting because it’s beautiful." the transition words are:
- Single: `"because"`
- Two part: `[ "whether", "or" ]`

The marked sentence should be: "I don’t know **whether** it’s interesting **because** it’s big
**or** it’s interesting **because** it’s beautiful.".

## What should the researcher return?
By keeping the index of each word we are exact. By differentiating between two parts and one part we have the option to treat them differently further down the process (assessment / marks).
The proposed format:
```javascript
[
    {
        sentence: "I don’t know whether it’s interesting because it’s big or it’s interesting because it’s beautiful.",
        transitionWords: [
            {
                words: [
                    {
                        context: "whether",
                        index: 14
                    },
                    {
                        context: "or",
                        index: 56
                    },
                ],
                type: "twoParts"
            },
            {
                word: {
                    context: "because",
                    index: 39
                },
                type: "onePart"
            },
            {
                word: {
                    context: "because",
                    index: 76
                },
                type: "onePart"
            }
        ]
    }
]
```

## What should the assessment change?
The Transition Words Assessment should adapt itself to be able to work with the above changes. This is the `getMarks` function currently called: `transitionWordsMarker`. Currently this returns an array with *Mark* objects. A *Mark* has original text and a marked text. There is room for improvement there, but let's take on the assessment itself first.

The proposed working of this function:
- Create an array containing *words* for every sentence:
    1. Split the twoParts into two.
        ```javascript
        {
            words: [
                {
                    context: "whether",
                    index: 14
                },
                {
                    context: "or",
                    index: 56
                },
            ],
            type: "twoParts"
        }
        ```
        becomes
        ```javascript
        [
            {
                context: "whether",
                index: 14
            },
            {
                context: "or",
                index: 56
            }
        ]
        ```

    2. Filter any double words out.
    3. Sort the index from high to low (the marks change the length of the text).
- Apply marks to each *word* in the sentence.

For our earlier example the result would look something like:
```javascript
[
    Mark {
        original: "I don’t know whether it’s interesting because it’s big or it’s interesting because it’s beautiful.",
        marked: "I don’t know <yoastmark>whether</yoastmark> it’s interesting <yoastmark>because</yoastmark> it’s big <yoastmark>or</yoastmark> it’s interesting <yoastmark>because</yoastmark> it’s beautiful."
    }
]
```

### Original whiteboard working
![refactor-transitionwords](https://user-images.githubusercontent.com/35524806/36097424-3e0ebd2e-0ffb-11e8-939a-0ea3fab1cae7.jpg)

# Needs decision
Do we change the data structure of the transition words researcher?

**Comment by jdevalk** [comment]
Yes. We do.

**Comment by igorschoester** [comment]
This is solved with the tree parser.
