### ISSUE TITLE
Eye marker in the analysis doesn't highlight anything on categories or tags

### ISSUE THREAD

**Issue by benvaassen** [Yoast/YoastSEO.js#1426]
## What did you expect to happen?
When I click the eye marker, I'd expect to see the issue highlighted. 

## What happened instead?
Instead, it doesn't highlight anything when I click the eye marker. 

## How can we reproduce this behavior?
1. Create a new category/tag or edit an existing category/tag
2. Write some text that triggers an eye marker. 
3. Click the eye marker and see nothing happens. 

![marker](https://user-images.githubusercontent.com/11910661/36839863-80087e18-1d43-11e8-87a7-41f94ced57ef.png)

Also happens for WooCommerce product categories. 

## Technical info
* WordPress version: 4.9.4
* Yoast SEO version: 6.3.1

**Comment by benvaassen** [comment]
Please inform the customer of conversation # 172794 when this conversation has been closed.

**Comment by benvaassen** [comment]
Please inform the customer of conversation # 173648 when this conversation has been closed.

**Comment by benvaassen** [comment]
Please inform the customer of conversation # 195758 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 342434 when this conversation has been closed.

**Comment by CarolineGeven** [comment]
Closing in favor of https://github.com/Yoast/wordpress-seo/issues/10564
