### ISSUE TITLE
[Feature Request] Show / make visible the SEO and Readability notifications/analysis in the Metabox accordion by default

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/YoastSEO.js#1428]
When a post or page is made and content added, the scores are show in an accordion. Users then need to open up the accordion to see the scores. 

Displaying the SEO and Readability scores by default makes easier and faster for a user to view and then optimize the content. It saves them additional clicks it takes to open up the accordion and see the notifications

![screen_shot_2018-03-02_at_1_43_44_pm](https://user-images.githubusercontent.com/8238074/36915844-1e9d0ea4-1e20-11e8-81d0-c5ab06bb9eb5.png)

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 317882 when this conversation has been closed.

**Comment by Djennez** [comment]
No longer relevant.
