### ISSUE TITLE
Recognize Bullet Points

### ISSUE THREAD

**Issue by ChrisWebAdmin** [Yoast/YoastSEO.js#1446]
## What did you expect to happen?

The plugin doesn't realize that the text is in a list and not consecutive sentences

## What happened instead?

It returns an error if the list has several items starting with the same word.

## How can we reproduce this behavior?

Create a bullet list with each item starting with the same word

## Technical info

* Platform: WordPress | Drupal | Standalone
* Platform version: 4.9.4
* Yoast SEO version: 7.0.3

See: **https://wordpress.org/support/topic/recognize-bullet-points-as-such/#post-10079385**

**Comment by atimmer** [comment]
Thank you for your bug report!

This is definitely something we want to do. We already have an issue to track this: https://github.com/Yoast/YoastSEO.js/issues/1190. Because we want to avoid duplicate issues I am going to close this one. Feel free to subscribe to the other issue.
