### ISSUE TITLE
How to install and use with laravel ?

### ISSUE THREAD

**Issue by phontuan** [Yoast/YoastSEO.js#1449]
## Technical info

* Platform: WordPress | Drupal | Standalone
* Platform version:
* Yoast SEO version:

**Comment by crgeary** [comment]
Hi @phontuan,

You'll need to make use of `Paper, SEOAssessor, ContentAssessor` from the package. You need to create an instance of the `Paper` object, which you would then pass into each of the 2 assessors (`SEOAssessor` and `ContentAssessor`).

I made a standalone demo of this which you can find here (https://github.com/crgeary/inspector), which is a bare minimum example showing how you can use the assessments.

I think the `titleWidth` property for the `Paper` object is the pixel width of the title on the Google search result, which I haven't implemented in my example. 

Hopefully this gets you on the right path. I would love to see this inside Laravel.

**Comment by Djennez** [comment]
As a answer has been supplied, (thank you @crgeary ) but no reply to that has been provided, I will close this thread.

**Comment by gokulmhegde** [comment]
this is now available in [https://github.com/gokulmhegde/Laravel-YoastSeo.git](url) which is a vue js package
