### ISSUE TITLE
Test Russian feature branch

### ISSUE THREAD

**Issue by nataliashitova** [Yoast/YoastSEO.js#1461]
We need to test the entire feature branch for Russian language readability analysis. 
In the following comments all (minor) issues concerning this branch will be mentioned.

**Comment by dariaknl** [comment]
Minor issue: add to timeWords "гг"

**Comment by nataliashitova** [comment]
(transition words) - Edit singleIntroWordsWithComma and multipleIntroWordsWithComma to account for somewhat improper punctuation

**Comment by nataliashitova** [comment]
(internal linking) - add `ru` to the list of languages available for internal linking

**Comment by nataliashitova** [comment]
All minor problems mentioned in this issue are fixed. No other issues were detected in testing approximately 40 Russian-language texts on various topics using a zip of WP-premium.
Internal linking suggestions (a Premium feature) will be implemented in #1697.
