### ISSUE TITLE
Improve the warning shown when no meta description has been specified

### ISSUE THREAD

**Issue by rmarcano** [Yoast/YoastSEO.js#1462]
When no meta description has been specified, the Yoast plugin will display an auto-generated description of 320 characters in the Snippet Preview. This can be confusing since users might think that this will be the meta description tag for the post.

We currently have a warning when no meta description has been specified: _"No meta description has been specified. Search engines will display copy from the page instead."_. It might be good to include an additional explanation that this autogenerated meta description will not be actually output to the page, possibly via a link to a KB article. 

![nometadesc](https://user-images.githubusercontent.com/1044883/38520304-6b64be9a-3c10-11e8-8aae-24b75e1f822c.png)

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 334694 when this conversation has been closed.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 350311 when this conversation has been closed.

**Comment by IreneStr** [comment]
Closed because we're dropping the generated metadescription altogether. See Yoast/wordpress-seo#9930
