### ISSUE TITLE
[Feature Request] Output Meta Description tag and text into source code even if none have been specified on a post/page

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/YoastSEO.js#1464]
**If a meta description has not been created for a post/page**

![screen shot 2018-04-11 at 4 54 18 pm](https://user-images.githubusercontent.com/8238074/38642863-62866b26-3da9-11e8-88a1-15523d486c64.png)

**It will not appear in the source code.** 

![screen shot 2018-04-11 at 4 53 42 pm](https://user-images.githubusercontent.com/8238074/38642871-6bf1408c-3da9-11e8-9884-4f44a1c4ac16.png)

We should output a meta description tag based on the first couple lines of the post/page even if no meta description has been specified. This will help improve user experience and expectations.

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/YoastSEO.js/issues/1462

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/YoastSEO.js/issues/387

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 335225 when this conversation has been closed.

**Comment by IreneStr** [comment]
Closed because we're dropping the generated metadescription altogether. See Yoast/wordpress-seo#9930
