### ISSUE TITLE
Incorrect 'linking to another page with the focus keyword' assessment

### ISSUE THREAD

**Issue by monbauza** [Yoast/YoastSEO.js#1489]
## What did you expect to happen?
The 'linking to another page with the focus keyword' to not appear when the anchor text of a link doesn't include the focus keyword.

## What happened instead?
The warning appears in the screnario described below.

## How can we reproduce this behavior?
1. Create a new post (Test page https://demo.yoast.com/support/wp-admin/post.php?post=1764&action=edit)
2. Switch the content editor to the Text view 
3. Copy/paste the sample text below
4. Set the focus keyword to 'Mandestrip'
5. Switch to the Visual view and save post
6. Note that the 'linking to another page with the focus keyword' appears in the keyword analysis (see image below)

**Sample text**
```
<aside>
<h3>Dragør, Egedal, Fredensborg, Frederikssund, Furesø, Gentofte, Gladsaxe, Gribskov, Halsnæs, Helsingør.</h3>
</aside>
<h5>mandestrip booking</h5>
<a href="https://my-domain.com">Holeby</a>
```

![image](https://user-images.githubusercontent.com/9658774/39745647-2a182a72-52a8-11e8-813b-473a85afe987.png)

## Technical info
* WordPress: 4.9.5
* Yoast SEO version: 7.4.2

**Comment by monbauza** [comment]
Please inform the customer of conversation # 357017 when this conversation has been closed.

**Comment by Pcosta88** [comment]
related https://github.com/Yoast/wordpress-seo/issues/6271

**Comment by Djennez** [comment]
Closing this in favor of https://github.com/Yoast/wordpress-seo/issues/6271

Customer conversation 357017 was moved there.
