### ISSUE TITLE
Wrongly displayed "Please create an SEO title" with multiple focus keywords

### ISSUE THREAD

**Issue by benvaassen** [Yoast/YoastSEO.js#1532]
## What did you expect to happen?
When adding a second focus keyword, that I don't get incorrectly listed problems in my analysis and that I don't see the warning when an SEO title is present.

## What happened instead?
I see the warning I should create an SEO title, while there is a title. 

## How can we reproduce this behavior?
1. Create a new post.
2. Add a focus keyword.
3. Add a tab to enter a second focus keyword.
4. Add a focus keyword existing of at least 2 words with a space in between them.
5. Save the post if the warning doesn't show yet. 
6. Navigate to the second keyword tab and see the warning.

The focus keyword from the first tab is selected it seems. See: 
<img width="761" alt="problem" src="https://user-images.githubusercontent.com/11910661/41229660-1a8f4faa-6d7d-11e8-8773-e163722e7107.png">

## Technical info

* Platform version: WordPress 4.9.6
* Yoast SEO version: 7.6.1

Regression: tested with 7.5.2 and was working.

**Comment by benvaassen** [comment]
Please inform the customer of conversation # 382455 when this conversation has been closed.

**Comment by PatrickYoast** [comment]
Please inform the customer of conversation # 383846 when this conversation has been closed.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 383269 when this conversation has been closed.

**Comment by michaelbriantina** [comment]
Please inform the customer of conversation # 382455 when this conversation has been closed.

**Comment by monbauza** [comment]
Note that the focus keyword that appears in the analysis results for the second focus keyword "test hosting" is the first keyword "test". The different checks (i.e. keyword in first parahraph, keyword density, etc.) for the second focus keywords seem to correspond to the first keyword. 

Related: https://github.com/Yoast/YoastSEO.js/issues/1333

**Comment by monbauza** [comment]
Please inform the customer of conversation #  385655 when this conversation has been closed.

**Comment by maybellyne** [comment]
Please inform the customer of conversation # 384080 when this conversation has been closed.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 383056 when this conversation has been closed.

**Comment by ahamaton** [comment]
Hi, I am experiencing this bug, so just joining the forum in order to keep up to date with developments.  Thanks

**Comment by amboutwe** [comment]
Related https://github.com/Yoast/wordpress-seo-premium/issues/1782

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 385820 when this conversation has been closed.

**Comment by ahamaton** [comment]
Thanks but I get a 404 error from this link ?

Kind regards

Andrew

Andrew Hamaton
Mallorca By Land, Air & Sea
Calle Can Baro 1/4B, Palma, 07014, Mallorca
+34 656 405 192

[Email with Air]

Copyright © Reg. No: 284691186, All rights reserved
Mallorca By Land & Sea (tm) is an International Trademark, OHIM 013872163
Data Protection:
This email contains confidential information, the content of this is protected by law. Any person different from the receiver is prohibited to reproduce, use to divulge or print all or part of the message if received by error. Notify immediately the sender of the original message together with any adjoining files. If you wish to exercise your right to access, rectify, cancel or oppose any of the established terms of the Ley Orgánica 15/1999, you may do so at the same address.
La información contenida en este mensaje de correo electrónico es confidencial y ha sido enviada con intención de que únicamente sea leída por la(s) persona(s) a la(s) que va dirigida. El acceso a este mensaje por otras personas no está autorizado. Si Vd. no es la persona a la que va dirigido, cualquier divulgación, copia o distribución de la información queda prohibida y puede ser ilegal. Si ha recibido este mensaje por error, por favor, notifíquelo inmediatamente al emisor y borre este mensaje. En cumplimiento de la LO 15/99 de 13 de diciembre, sobre Protección de Datos de Carácter Personal (LOPD), informamos que los datos de carácter personal que recoge son objeto de tratamiento automatizado y se incorporan a los ficheros correspondientes. El usuario o interesado puede, en todo momento, ejercitar los derechos reconocidos en la LOPD.
Diese E-Mail enthält vertrauliche Informationen, der Inhalt derselben wird durch das Gesetz geschützt. Jeder anderer Person als dem Empfänger ist es verboten diese zu reproduzieren, zu verwenden, oder zu drucken. Wenn Sie diese Nachricht irrtümlich erhalten haben, benachrichtigen Sie den Absender der ursprünglichen Nachricht zusammen mit angehängten Dateien. Wenn Sie ihre Rechte auf Auskunft, Berichtigung, Löschung und Widerspruch in den Begriffen des Gesetzes 15/1999 eingeführte Gebrauch machen möchten, können sie diese an die obige Adresse richten.

**Comment by maybellyne** [comment]
Please inform the customer of conversation # 388036 when this conversation has been closed.

**Comment by PatrickYoast** [comment]
Please inform the customer of conversation # 388375 when this conversation has been closed.

**Comment by ahamaton** [comment]
Hi, was this issue actually resolved ?
Thanks, Andrew

**Comment by igorschoester** [comment]
Yes @ahamaton it is resolved. It will be included in the next release.
