### ISSUE TITLE
Test feature/recalibration after a massive merge conflict

### ISSUE THREAD

**Issue by nataliashitova** [Yoast/YoastSEO.js#1581]
I just resolved a [massive merge conflict](https://github.com/Yoast/YoastSEO.js/commit/55418dad94fedee06e4700258c9825ac2b61759e) between develop (including synonyms + links to kb articles in all assessments) and feature/synonyms (including recalibrated assessments, assessments which were rewritten as classes and many changes to researches). 
This commit affected 98 files, including convoluted merge conflict in all SEO assessments, all SEO assessment specs and a few critical researches.

We need to test feature/recalibration to see if it still complies with the original specification and no functionality was lost in the merge conflict.

I also believe we should merge all assessments which were changed in feature/recalibration, but do not have user-facing changes (e.g., rewritten into class, improved specs) into develop. That will help to maintain a more stable version of feature/recalibration and not have to deal with merge conflicts. It will also allow to proceed with development for the Morphology project more smoothly. @omarreiss, what do you think?

**Comment by omarreiss** [comment]
To confirm our offline discussion. Go for it!

**Comment by nataliashitova** [comment]
The SEO assessments from feature/recalibration are being migrated in #1591 and #1592. 

Specific testing of feature/recalibration is not relevant any more, since the recalibration is now a part of a larger morpho-syno-recalibration project. Therefore, I am closing this issue.
