### ISSUE TITLE
Punctuation marks used in the keyword get stripped in slug

### ISSUE THREAD

**Issue by nataliashitova** [Yoast/YoastSEO.js#1608]
We need to improve recognition of the keyword in the URL. The problem is that the punctuation marks are stripped in slug, but not in the keyword.
In line with the upcoming changes to include morphological support and synonyms and smarter matching of keyphrase words in URL (see #1558), we should parse the words out of the keyword and out of the URL and compare the arrays. 
See examples in #1193 and #278.

This issue will be addressed together with the refactoring of the URLKeyword assessment within the #1558.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 207970 when this conversation has been closed.
