### ISSUE TITLE
Add check for optimal size for images on Facebook

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/YoastSEO.js#161]
**Problem description**
Facebook 'requires' specific image sizes for the various ways they display images for links. It's often unclear what size is required or optimal for Facebook.

**Possible solution**
Add checks for the optimal image sizes. An overview can be found on [developer.facebook.com](https://developers.facebook.com/docs/sharing/best-practices#images). 
![facebook_content_sharing_best_practices](https://cloud.githubusercontent.com/assets/5147598/11186065/423072ae-8c80-11e5-8c3f-a0741d380e60.png)

**Comment by CarolineGeven** [comment]
Closing as the social previews have been redone and moved to premium. There is already an issue open for this in the premium repository.

https://github.com/Yoast/wordpress-seo-premium/issues/1010
