### ISSUE TITLE
Outbound links all followed shows the wrong text

### ISSUE THREAD

**Issue by igorschoester** [Yoast/YoastSEO.js#1621]
## What did you expect to happen?

When a post has all outbound links followed, it should show a good result: This page has X outbound link(s). 

## What happened instead?

The good result: This page has 0 nofollowed outbound link(s) and X normal outbound link(s).
<img width="595" alt="outbound_links" src="https://user-images.githubusercontent.com/35524806/43073678-c0afe408-8e7a-11e8-89cc-a47aa2e5d481.png">

## How can we reproduce this behavior?

Add outbound links to a new post.

## Technical info

* Platform: WordPress
* Platform version: 4.9.7
* Yoast SEO version: trunk of 7.9.x

**Comment by manuelaugustin** [comment]
Fixed here https://github.com/Yoast/YoastSEO.js/pull/1824
