### ISSUE TITLE
Refactor seo assessments filenames and exports

### ISSUE THREAD

**Issue by igorschoester** [Yoast/YoastSEO.js#1625]
The SEO Assessments where refactored to classes. The older refactor did not change the filenames to match the classnames. The module.exports way is also used instead of the ES6 export default. Note that this will need adjustments in all the spots they are required too (use import there).

Please update the following (basically all lower cased files in assessments/seo):

- MetaDescriptionLengthAssessment
- OutboundLinksAssessment
- PageTitleWidthAssesment
- SubHeadingsKeywordAssessment
- TextImagesAssessment
- TextLengthAssessment
- UrlLengthAssessment

Ignore the following as they will get removed through the recalibration feature:
- keywordHasStopWordsAssessment
- taxonomyTextLengthAssessment
- urlHasStopWordsAssessment

**Comment by Kingdutch** [comment]
This currently breaks webpack builds because it doesn't support mixing `import` with `module.exports`: https://github.com/webpack/webpack/issues/4039#issuecomment-273804003
