### ISSUE TITLE
Replace Flesch Reading ease with a more meaningful check

### ISSUE THREAD

**Issue by manuelaugustin** [Yoast/YoastSEO.js#1632]
The Flesch Reading Ease score has several drawbacks. Most importantly, it's not very actionable. But there are also some other cons, see https://github.com/Yoast/research/wiki/Flesch-Reading-Ease.

Since the Flesch Reading Ease test is based on the complexity of words and sentences, we should address those two factors directly. For sentence length, we already have an assessment. For word complexity, we should look into reviving the old word complexity assessment. A quick solution would be to use the existing syllable data to make an estimate for complexity. A more sophisticated approach would be to make use of lexical frequency. However, this would require additional data.

**Comment by nataliashitova** [comment]
Some insights from a recent readability workshop: https://github.com/Yoast/research/wiki/More-potential-measures-of-readability

**Comment by manuelaugustin** [comment]
Closed in favor of https://yoast.atlassian.net/browse/LIN-498
