### ISSUE TITLE
Process the text in the worker: removeHtmlBlocks

### ISSUE THREAD

**Issue by igorschoester** [Yoast/YoastSEO.js#1673]
**Please branch from**: `feature/webworker`.

Use `removeHtmlBlocks` on the text in the worker (which is `stringProcessing/htmlParser.js`). Just like the `App` does now.
Note: The processed text needs to be the one that gets compared later.

**Comment by nataliashitova** [comment]
The parser is added in #1679. The comparison of input papers so that the analysis is rerun if the paper has changed will be implemented in #1558.
