### ISSUE TITLE
RegisterAssessment should be ported to work with importScripts

### ISSUE THREAD

**Issue by igorschoester** [Yoast/YoastSEO.js#1680]
**Please branch from**: `feature/webworker`.

The current `App` has functionality around `Pluggable` to be able to add your own assessments. Due to the assessments now running inside the worker, this will no longer work. We need to recreate this functionality through the use of `importScripts`.

Check `stories/web-worker-test` for some test code [[link](https://github.com/Yoast/wordpress-seo/compare/stories/web-worker-test)].

All our own add-ons that add a custom assessment need to be changed to accommodate this change. Add-ons that have a custom assessment: `video`, `local`, `woo`, `previouslyUsedKeywords`. *These are separate issues.*

## Tasks
- Create a command / action in the Worker & Wrapper to trigger `importScripts`.
- We need to prepend the base URL of the site to make importScripts a bit safer. By default, importScripts allows any URL, even from third parties.
- The script that is imported can then use an API that is provided by the code in the worker using for example `self.publicMethod = () => {}`.

**Comment by atimmer** [comment]
Closed in #1705.
