### ISSUE TITLE
Local: Adapt custom assessment to importScripts version

### ISSUE THREAD

**Issue by igorschoester** [Yoast/YoastSEO.js#1682]
**Please branch from**: `feature/webworker`.

See the `importScripts` issue https://github.com/Yoast/YoastSEO.js/issues/1680 for context on how and why. 

Adapt custom assessment to importScripts version in local.

**Comment by manuelaugustin** [comment]
Closed via https://github.com/Yoast/wordpress-seo-local/pull/1193
