### ISSUE TITLE
PreviouslyUsedKeywords: Adapt custom assessment to importScripts version

### ISSUE THREAD

**Issue by igorschoester** [Yoast/YoastSEO.js#1684]
**Please branch from**: `feature/webworker`.

See the `importScripts` issue https://github.com/Yoast/YoastSEO.js/issues/1680 for context on how and why. 

Adapt custom assessment to importScripts version in previouslyUsedKeywords.

**Comment by atimmer** [comment]
Closed in #10689

**Comment by atimmer** [comment]
Closed in #10689.
