### ISSUE TITLE
Bullet changes status/color twice

### ISSUE THREAD

**Issue by PatrickYoast** [Yoast/YoastSEO.js#1688]
## What did you expect to happen?
I expected the bullet to load as normal

## What happened instead?
I did read about the bullet being grey at first but after testing some more it turns out they can also change color after it looks to be loaded. 

In this example after a refresh the focus keyword bullet is grey, then red and finally turns yellow after 1-2 seconds

## How can we reproduce this behavior?
Create a category called `duplicate content`. In the description paste the contents of https://yoast.com/what-is-duplicate-content/.

After saving the issue should occur on every refresh.

![weird bullet behavior](https://user-images.githubusercontent.com/14159618/43827385-01fdd948-9afa-11e8-8f8d-f3b2dc542dfa.gif)

@hedgefield Is working on builder a loader for this so that the bullets are not shown until fully loaded. He will use this issue for the designs for that

**Comment by hedgefield** [comment]
We will have to get to the bottom of why the smiley changes color twice, that's strange. But for the initial loading aspect, replace the bullet with a spinner icon until the analysis is fully loaded.

![loading 1](https://user-images.githubusercontent.com/6073772/43835481-672bf0bc-9b12-11e8-9b1c-1ae01c264831.png)

## HTML
```
<svg class="spinner" width="16px" height="16px" viewBox="0 0 66 66" xmlns="http://www.w3.org/2000/svg">
   <circle class="path" fill="none" stroke-width="8" stroke-linecap="round" cx="33" cy="33" r="28"></circle>
</svg>
```

## CSS
```
$offset: 187;
$duration: 1.4s;

.spinner {
  animation: rotator $duration linear infinite;
}

@keyframes rotator {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(270deg); }
}

.path {
  stroke-dasharray: $offset;
  stroke-dashoffset: 0;
  transform-origin: center;
  animation:
    dash $duration ease-in-out infinite, 
    colors ($duration*4) ease-in-out infinite;
}

@keyframes colors {
	0% { stroke: #64a60a; }
  100% { stroke: #64a60a; }
}

@keyframes dash {
 0% { stroke-dashoffset: $offset; }
 50% {
   stroke-dashoffset: $offset/4;
   transform:rotate(135deg);
 }
 100% {
   stroke-dashoffset: $offset;
   transform:rotate(450deg);
 }
}
```

**Comment by afercia** [comment]
Two quick considerations about the SVG:
- all the SVGs used as icons must have the attributes `role="img" aria-hidden="true" focusable="false"`
- ideally, all the SVGs icons should have the same viewBox. We can workaround through code but it would be great to standardize the SVG icons code. This `0 0 66 66` value is totally new comparet to the existing icons

See also https://github.com/Yoast/wordpress-seo/issues/10591

**Comment by hedgefield** [comment]
I'm not sure what the viewbox does, or why it is 66 here, it was in the example code. If it can be adapted to work with our standard value that would be great.

**Comment by boblinthorst** [comment]
I've worked with @dutchmartin on a fix for this. We ended up not addressing the flickering score, but we did address the proposed design. So I'm extracting the design part to a seperate issue.
