### ISSUE TITLE
Investigate possibilities to deprecate separate locale configuration for ContentAssessor

### ISSUE THREAD

**Issue by nataliashitova** [Yoast/YoastSEO.js#1691]
Right now the ContentAssessor calls Flesch reading assessment and Sentence Length assessment with a combined configuration that allows language-specific values (i.e., boundaries, scores) to be passed. In practice, this configuration locale is always the same as the paper locale. It might be possible to not really have to use this combined config in the content assessor and to spare the use of this additional configuration locale by using paper locale instead.
We need to investigate possibilities to assign paper locale to the configuration of the assessment within the assessment itself.

**Comment by igorschoester** [comment]
Closing, not important anymore
