### ISSUE TITLE
Change the plugin to use the markings in the results (from the store).

### ISSUE THREAD

**Issue by igorschoester** [Yoast/YoastSEO.js#1692]
**Please branch from**: `feature/webworker`.

Change the plugin to use the markings in the results (from the store).

Currently, the plugin passes a marker function to the app (in `wp-seo-post-scraper.js` and `wp-seo-term-scraper.js`). We want the plugin to be responsible for marking the text, not `app.js` in YoastSEO.js. Therefore, all the marking functionality should take place on the plugin side. YoastSEO.js will pass the marks as an array of mark objects.

**Comment by manuelaugustin** [comment]
Adding the array of mark objects in YoastSEO.js is done in https://github.com/Yoast/YoastSEO.js/pull/1694. The marking functionality in the plugin still needs to be added.
