### ISSUE TITLE
Fix app usages that were not backfilled

### ISSUE THREAD

**Issue by igorschoester** [Yoast/YoastSEO.js#1714]
**Please branch from**: `feature/webworker`.

Search and replace the usages of the global `YoastSEO.app`. Where it gets passed search further.

I found a couple so far:
- In `components/contentAnalysis/Results` the function `removeMarkers` uses `contentAssessor` on the app.
- In `wp-seo-tinymce` the function `tinyMceEventBinder` uses `disableMarkers` on the app.
- In `getAnalysisData` uses `config.locale` still. Could be replaced now.
- In `getIndicatorForScore` the functions `hasPresenter` and `getPresenter` both use `seoAssessorPresenter` and `contentAssessorPresenter`.

**Comment by nataliashitova** [comment]
Moving to `blocked` now, because 
- In `components/contentAnalysis/Results` the function `removeMarkers` uses `contentAssessor` on the `app`
depends on https://github.com/Yoast/YoastSEO.js/issues/1703
