### ISSUE TITLE
Backfill app usages in AssessorPresenters

### ISSUE THREAD

**Issue by nataliashitova** [Yoast/YoastSEO.js#1716]
We need to replace global app usages in seoAssessorPresenter and contentAssessorPresenter

- In `wp-seo-tinymce` the function `tinyMceEventBinder` uses `disableMarkers` on the `app`.
- In `getIndicatorForScore` the functions `hasPresenter` and `getPresenter` both use `seoAssessorPresenter` and `contentAssessorPresenter`.

**Comment by igorschoester** [comment]
Part of already existing issue: https://yoast.atlassian.net/browse/LIN-170
