### ISSUE TITLE
Premium: relevantWords research does not work

### ISSUE THREAD

**Issue by igorschoester** [Yoast/YoastSEO.js#1720]
In premium, there are keyword suggestions. With the web worker, the `research.getResearch` is no longer available.

<img width="1163" alt="screen shot 2018-08-22 at 10 37 27" src="https://user-images.githubusercontent.com/35524806/44452658-65e7df00-a5f7-11e8-9fe9-c830fb3cc8e5.png">

Please find a solution for this.

related #1721

**Comment by atimmer** [comment]
Closed in https://github.com/Yoast/wordpress-seo-premium/pull/1954.
