### ISSUE TITLE
Premium: related keywords do not have mark icons

### ISSUE THREAD

**Issue by igorschoester** [Yoast/YoastSEO.js#1723]
While working on https://github.com/Yoast/YoastSEO.js/issues/1703 I noticed there are no mark buttons for the related keywords. Please fix.

**Comment by atimmer** [comment]
In the past we've decided not to enable markings for related keywords, we have no time to investigate now so we'll keep them disabled until we can investigate.

**Comment by igorschoester** [comment]
No longer the case
