### ISSUE TITLE
AnalysisWebWorker error

### ISSUE THREAD

**Issue by manuelaugustin** [Yoast/YoastSEO.js#1727]
An AnalysisWebWorker error occurs on taxonomy pages in Chrome and on taxonomy pages and posts in Firefox. 

<img width="530" alt="schermafbeelding 2018-08-22 om 16 12 47" src="https://user-images.githubusercontent.com/27805437/44469829-9f850e00-a628-11e8-81cf-1d97080e613b.png">

**Comment by moorscode** [comment]
The following commit fixes this problem: https://github.com/Yoast/wordpress-seo/commit/b6ea18d78a3f6da2e23c682ac7d45f4281aa668f
