### ISSUE TITLE
Additional keyword error

### ISSUE THREAD

**Issue by dariaknl** [Yoast/YoastSEO.js#1733]
## How can we reproduce this behavior?
1. Create post with text:

> Pellentesque a interdum ante, commodo pulvinar lacus some more words.
> 
> elit, vulputate sit amet blandit et, tempor nec ante. Etiam condimentum nibh odio, vitae laoreet mauris commodo maximus et. Aenean ultricies neque ut molestie vestibulum. Praesent vulputates aliquet ex consequat placerat bibendum. Donec sed purus at urna consequat tempor eu sed lectus. Nullam sed tincidunt lectus. Vestibulum consectetur orci nec laoreet dictum.
> 
> Pellentesque a interdum ante, commodo pulvinar lacus some more words.
> elit, sit amet blandit et, tempor nec ante. Etiam condimentum nibh odio, vitae laoreet mauris maximus et. Aenean ultricies neque ut molestie vestibulum. Praesent aliquet ex consequat placerat bibendum. Donec sed purus at urna consequat tempor eu sed lectus. Nullam sed tincidunt lectus. Vestibulum consectetur orci nec vulputates  laoreet dictum.
> 
> Pellentesque a interdum ante, commodo pulvinar lacus some more words.
> 
> Elit, vulputate sit amet blandit et, tempor nec ante. Etiam condimentum nibh odio, vitae laoreet mauris commodo maximus et. Aenean ultricies neque ut molestie vestibulum. Praesent aliquet ex consequat placerat bibendum. Donec sed purus at urna consequat tempor eu sed lectus. Nullam sed tincidunt commodo lectus. Vestibulum consectetur orci nec laoreet dictum. Pellentesque a interdum ante, commodo pulvinar lacus some more words.
> 
> Pellentesque a interdum vulputate ante, commodo pulvinar lacus some more words.
> 
> elit, vulputate sit amet blandit et, tempor nec ante. Etiam condimentum nibh odio, vitae laoreet mauris commodo maximus et. Aenean vulputates ultricies neque ut molestie vulputate vestibulum. Praesent aliquet ex consequat placerat bibendum. Donec sed purus at urna consequat tempor eu sed lectus. Nullam sed tincidunt commodo lectus. Vestibulum consectetur orci nec laoreet dictum. Pellentesque a interdum ante, commodo pulvinar lacus some more words. 

2. Add Focus keyword "vulputate" and Additional keyword "Nullam".

3. Check Additional keyword Analysis:

<img width="503" alt="screen shot 2018-08-27 at 10 40 13" src="https://user-images.githubusercontent.com/19681708/44649935-9cea3600-a9e5-11e8-8947-f858309c7589.png">

And console error:
```
TypeError: Cannot read property 'split' of null
    at a.exports (wp-seo-analysis-worker-81-RC3.min.js:13)
    at a.exports (wp-seo-analysis-worker-81-RC3.min.js:1)
    at e.value (wp-seo-analysis-worker-81-RC3.min.js:1)
    at x.f.executeAssessment (wp-seo-analysis-worker-81-RC3.min.js:1)
    at t (wp-seo-analysis-worker-81-RC3.min.js:1)
    at i (wp-seo-analysis-worker-81-RC3.min.js:1)
    at x.f.assess (wp-seo-analysis-worker-81-RC3.min.js:1)
    at wp-seo-analysis-worker-81-RC3.min.js:13
```
  
Reproduced with classic editor and Gutenberg.

## Technical info

* Platform: WordPress 
* Platform version: 4.9.8
* Yoast SEO version: 8.1 RC3 Premium

**Comment by manuelaugustin** [comment]
Closed in https://github.com/Yoast/wordpress-seo-premium/pull/1960
