### ISSUE TITLE
<br/> tags adjacent to the focus keyword prevent the keyword from being recognized.

### ISSUE THREAD

**Issue by boblinthorst** [Yoast/YoastSEO.js#1776]
## What did you expect to happen?
For the keyword to be recognised and counted for the keyword density assessment.

## What happened instead?
The keyword was not recognised and not counted.

## How can we reproduce this behaviour?
1. Create a new post
2. Toggle to Text view for the post.
3. Paste the following content in the content: 
```
<p>Ooh<br/>You can dance<br/>You can jive<br/>Having the time of your life<br/>Ooh, see that girl<br/>Watch that scene<br/>Dig in the dancing queen Friday night and the lights are low<br/>Looking out for a place to go<br/>Where they play the right music<br/>Getting in the swing<br/>You come to look for a king<br/>Anybody could be that guy<br/>Night is young and the music's high<br/>With a bit of rock music<br/>Everything is fine<br/>You're in the mood for a dance<br/>And when you get the chance You are the dancing queen<br/>Young and sweet<br/>Only seventeen<br/>Dancing queen<br/>Feel the beat from the tambourine, oh yeah<br/>You can dance<br/>You can jive<br/>Having the time of your life<br/>Ooh, see that girl<br/>Watch that scene<br/>Dig in the dancing queen You're a teaser, you turn 'em on<br/>Leave 'em burning and then you're gone<br/>Looking out… If you change your mind, I'm the first in line<br/></p>
```
4. Toggle back to visual view.
5. add `dance` as the focus keyword.
6. Check the keyword density assessment. It was found 0 times for me.

## Technical info

* Platform: WordPress
* Platform version: 4.9.8.
* Yoast SEO version: release branch 8.2
* The Gutenberg plugin was active, but tested on the classic editor.

**Comment by Djennez** [comment]
Reproducing these steps in WP 5.0.3 with Yoast 9.5 and I am unable to get these results. The keyphrase density correctly counts 3 instances of the word `dance`. I will close the issue for now, but if it's still relevant please let me know.
