### ISSUE TITLE
Polish readability check give unexpected results.

### ISSUE THREAD

**Issue by PatrickYoast** [Yoast/YoastSEO.js#1780]
## What did you expect to happen?
When using the example given in [this](https://docs.google.com/document/d/1fjGgDGIOHx2DrmxMcJLhDHZP8fOOeyHynPNJWfYS9zQ/edit?usp=sharing) document I expect the results of the readability checks to reflect to percentages in the document.

_FYI The eye markers are also not working._

## What happened instead?
In the classic editor:
<img width="683" alt="edytuj_wpis_ _test_com_ _wordpress" src="https://user-images.githubusercontent.com/14159618/45085585-5097a800-b101-11e8-9f59-258fd842b50a.png">

In Gutenberg:
<img width="262" alt="edytuj_wpis_ _test_com_ _wordpress" src="https://user-images.githubusercontent.com/14159618/45085648-7cb32900-b101-11e8-9657-e43bb1face4d.png">

## How can we reproduce this behavior?
Use the tekst from the document and see the results

## Technical info

* Platform: WordPress
* Platform version: 4.9.8
* Yoast SEO version: 8.2 RC3

**Comment by manuelaugustin** [comment]
Closed because this issue was due to some formatting problems that appeared when copying text from Google Docs to WordPress.
