### ISSUE TITLE
Flesch Reading Ease for German (other) language

### ISSUE THREAD

**Issue by Trike27** [Yoast/YoastSEO.js#179]
Hello,

with this post I refer to my topic in the wordpress community: https://wordpress.org/support/topic/flesch-reading-ease-for-german-other-language?replies=2

________________________________

I just have the question if you consider to integrate Flesch Reading Ease for German language? The equation differs a bit to the english one.

Flesch Reading Ease English = 206,835 - (1,015 * ASL) - 84,6 * ASW)
Flesch Reading Ease German = 180 - ASL - (58,5 * ASW)
(source: Wikipedia)

To be fair it would be great if you could insert the differing equations for other languages as well.

Thank you in advance!

Kind regards

Martin

**Comment by carletto0282** [comment]
Hi guys,
just wanna add a +1 for this request

In my case I'd like to ask Flesch Reading Ease for italian language that would be
Flesch index english = 206,835 - (0,864 * S) - (1,015*P)
Flesch index italian = 206 - (0,65 * S) - P

where

S = number of syllabs in a sample text of 100 words
P = average number of words in a sentence
(source: Wikipedia https://it.wikipedia.org/wiki/Formula_di_Flesch)

Even better for italian language would be the Gulpease index

Gulpease = 89 + { [ (300 * F) - (10 * L) ] / P }

where

F = number of sentences
L = number of letters
P = number of words

(source: Wikipedia https://it.wikipedia.org/wiki/Indice_Gulpease)

Thanks in advance
Best regards
Carlo

**Comment by e-anima** [comment]
i agree. the module could then be used on a  page that is not english. thx.

**Comment by atimmer** [comment]
Duplicates #267
