### ISSUE TITLE
Analysis tool not working properly for Greek language

### ISSUE THREAD

**Issue by monbauza** [Yoast/YoastSEO.js#180]
![greek-language](https://cloud.githubusercontent.com/assets/9658774/11267447/b32f3a8a-8eab-11e5-99a0-687e24d6e8d9.jpg)

The focus keyword is not detected in the first paragraph 
The keyword density is always 0%
The focus keyword is not detected in the URL

**Comment by monbauza** [comment]
Please inform the customer of conversation # 84806 when this issue has been closed.

**Comment by AskKim** [comment]
User in # 85046 reports this behavior is also affecting Arabic

Please inform the customer of conversation # 85046 when this issue has been closed.

**Comment by atimmer** [comment]
This has been fixed in 1.1
