### ISSUE TITLE
Load morphology data from URL

### ISSUE THREAD

**Issue by manuelaugustin** [Yoast/YoastSEO.js#1809]
For Premium, we need to load morphology data from MyYoast. For this, we need to add functionality that loads a JSON file from a URL. This request should return the a `200` with the JSON file when it succeeds and a `403` with an error message in case it fails.

For testing purposes, we can load the file from the `YoastSEO.js-premium-configuration` repo.

**Comment by igorschoester** [comment]
### Plugin JS
- Query MyYoast for the JSON file (URL will probably be this: `https://my.yoast.com/api/Downloads/file/morphology-list?site=BASE_URL`).
- Handle any responses. On error the user needs to get a message stating what happend.
  - 401 placeholder: `Hey, it looks like you haven't activated WordPresss SEO Premium on my.yoast.com! This means you currently don't have access to premium features like our morphology analysis! You can read more about activating your site here ( KB link ).`
- On success, the morphology object should get passed to the worker.

### YoastSEO.js
- The worker & wrapper need to get an action that accepts the morphology data object via `addResearchDataProvider`.
- The worker needs to call `addResearchDataProvider` on the researcher with `morphology` and the morphology data object.
