### ISSUE TITLE
Use Gini coeffecient to measure uniformness of keyword distribution.

### ISSUE THREAD

**Issue by hansjovis** [Yoast/YoastSEO.js#1819]
## Summary
We advise users to [distribute their keywords evenly throughout the text](https://yoast.com/yoast-seo-7-8/). The [Gini coefficient](https://en.wikipedia.org/wiki/Gini_coefficient) can be used to measure the uniformness of a distribution. In our case, it can measure the uniformness of the distances between keyword instances. This will be a more accurate keyword distribution measure.

## Explanation
We are measuring the uniformness by checking if the distance between any two keywords does not exceed a percentage of the total nr. of characters. This is currently set to 40%.
This, however, has the disadvantage that it does not capture all instances where the distances between keywords are not evenly distributed.
The Gini coefficient however has been developed to measure inequality in a distribution (specifically income inequality) so it would better reflect the notion of a uniform keyword distribution.

E.g.:
### 1. Uniform distribution. No inequality. Gini coef. of 0.
<img width="493" alt="screen shot 2018-09-25 at 12 12 14" src="https://user-images.githubusercontent.com/10195175/46008973-80155100-c0be-11e8-915c-e74379fb0d4a.png">

### 2. One outlier. Triggers "okay" score on assessment. Gini coef. of 0.228.
<img width="482" alt="screen shot 2018-09-25 at 12 12 21" src="https://user-images.githubusercontent.com/10195175/46009106-cec2eb00-c0be-11e8-9224-2de0e9de99e1.png">

### 3. Keywords non-uniformly distributed. Triggers "good" score. Gini coef. of 0.28.
<img width="491" alt="screen shot 2018-09-25 at 12 12 27" src="https://user-images.githubusercontent.com/10195175/46010587-835f0b80-c0c3-11e8-850a-1ebb5c12a48b.png">

**Comment by hansjovis** [comment]
Note: @nataliashitova had a valid critique in that this should play nice when you have multiple keywords in your key phrase. In that case the "distance between keywords" gets ill-defined.
If we implement this, we have to find a solution.

**Comment by manuelaugustin** [comment]
Closed as we actually adopted the Gini coefficient as a metric for keyword distribution (see https://github.com/Yoast/YoastSEO.js/pull/1789).
