### ISSUE TITLE
Readability Fails to Highlight Text in Gutenberg Editor

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/YoastSEO.js#1821]
## What did you expect to happen?
To highlight text in the GB editor

## What happened instead?

It did not

## How can we reproduce this behavior?

**1.Use Text Editor and see ability to highlight**

<img width="953" alt="screen shot 2018-09-25 at 2 06 38 pm" src="https://user-images.githubusercontent.com/8238074/46033573-8ca0a600-c0cc-11e8-8892-9011cc325417.png">

**2. See text get highlighted**
 
<img width="1044" alt="screen shot 2018-09-25 at 2 06 28 pm" src="https://user-images.githubusercontent.com/8238074/46033588-92968700-c0cc-11e8-818e-b36c1503f6a9.png">
 

**3.Switch to Gutenberg** 

<img width="996" alt="screen shot 2018-09-25 at 2 05 52 pm" src="https://user-images.githubusercontent.com/8238074/46033640-a9d57480-c0cc-11e8-940f-cf49c0424e86.png">

**4. and see no highlight ability appears**

<img width="992" alt="screen shot 2018-09-25 at 2 05 57 pm" src="https://user-images.githubusercontent.com/8238074/46033643-ac37ce80-c0cc-11e8-982c-254b68c93b65.png">

## Technical info

* Platform: WordPress  
* Platform version: 498
* Yoast SEO version: 8.3
*GB: 3.9.0

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 428617 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 429587 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 452433 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 452208 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 452681 when this conversation has been closed.

**Comment by maybellyne** [comment]
Please inform the customer of conversation # 453256 when this conversation has been closed

**Comment by iamazik** [comment]
Please inform the customer of conversation # 461343 when this conversation has been closed.

**Comment by moorscode** [comment]
We have greatly improved highlighting in Gutenberg since this issue has been created.
I'm closing this as reports should include a better description of what exactly is not being highlighted.
