### ISSUE TITLE
[Feature Request] Output notification if a post or page lacks an h1 heading tag

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/YoastSEO.js#1827]
It has been recommended that a post/page have at least one h1 tag/ heading: https://www.youtube.com/watch?v=GIn5qJKU8VM and https://yoast.com/headings-use/.

**If a post/page lacks subheadings we output a warning:**

<img width="832" alt="screen shot 2018-09-27 at 9 25 08 am" src="https://user-images.githubusercontent.com/8238074/46148972-3f8d1300-c237-11e8-8af7-131875d01384.png">

**Yoast does not output a specific notification if a post/page lacks an h1 heading/tag/. This may also mean that Yoast needs to scan the Title Field to figure out if that field is an h1 header**

<img width="844" alt="screen_shot_2018-09-27_at_9_26_44_am" src="https://user-images.githubusercontent.com/8238074/46149095-824eeb00-c237-11e8-9a24-f9cddc099089.png">
 

**Adding notification will improve both the Content SEO and Technical SEO of the post/page.**

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/YoastSEO.js/issues/1298

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 427137 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 433582 when this conversation has been closed.

**Comment by Djennez** [comment]
There's already a notification for one H1 header (in the beginning of you text)
