### ISSUE TITLE
 Error occurred in the 'YoastWooCommerce-productTitle' assessment

### ISSUE THREAD

**Issue by monbauza** [Yoast/YoastSEO.js#1835]
## What did you expect to happen?
No assessments errors to appear in the keyword analysis.

## What happened instead?
When editing a WooCommerce product, the error below shows up in the keyword analysis, if the Text editor is enabled and the Yoast SEO WooCommece plugin is activated.

`An error occurred in the 'YoastWooCommerce-productTitle' assessment when `

Switching to the Visual editor (and saving the page) or deactivating Yoast SEO WooCommerce fixes the error.

## How can we reproduce this behavior?
1. Make sure Yoast SEO, WooCommerce and Yoast SEO Woocommerce are installed and activated
2. Create a WooCommerce product
3. Switch to the Text editor and save the page
4. Note that the aforementioned error shows up 

![image](https://user-images.githubusercontent.com/9658774/46471402-02e28e00-c7da-11e8-9fe5-4d1dd6703695.png)

## Technical info

* Platform: WordPress 4.9.8
* Yoast SEO version: 8.3
* WooCommerce version: 3.4.5
* Yoast SEO Woocommerce version: 8.3

**Comment by monbauza** [comment]
Please inform the customer of conversation # 431009 when this conversation has been closed.

**Comment by CarolineGeven** [comment]
Probably the issue lies that on page load we do not detect properly if the visual editor or the text editor is active.

**Comment by priscillamc** [comment]
Please inform the customer of conversation # 437024  when this conversation has been closed.

**Comment by monbauza** [comment]
Closing. Duplicate of https://github.com/Yoast/wpseo-woocommerce/issues/286
