### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dgettext' of undefined

### ISSUE THREAD

**Issue by kristoffeys** [Yoast/YoastSEO.js#1855]
## What did you expect to happen?
For YoastSEO to run without errors. When intializing snippet first and afterwards the app (as in the readme example)

## What happened instead?
Got "Uncaught TypeError: Cannot read property 'dgettext' of undefined"

## How can we reproduce this behavior?
```
var snippetPreview = new SnippetPreview({
    targetElement: document.getElementById( "snippet" )
});

var app = new App({
    snippetPreview: snippetPreview,
    targets: {
        output: "output"
    },
    callbacks: {
        getData: function() {
            return {
                keyword: focusKeywordField.value,
                text: contentField.value
            };
        }
    }
});
```

## Technical info

* Platform: Standalone
* Platform version: /
* Yoast SEO version: 1.40.0

The problem seems to be that i18n in SnippetPreview doesn't get initialized. This happens because in app.js _i18n gets filled in instead of i18n. itself.

I'll add a PR with a fix. I'm not sure if this fix is completely correct since i'm not really home in the YoastSEO.js code.

**Comment by igorschoester** [comment]
Closing issue, see PR #1856
