### ISSUE TITLE
Keyphrase in subheading check is broken

### ISSUE THREAD

**Issue by jdevalk** [Yoast/YoastSEO.js#1859]
## What did you expect to happen?
The keyphrase in subheading check to recognize my keyphrase in the subheading.

## What happened instead?
It gave me a red bullet.

## How can we reproduce this behavior?
Use this text: [keyphrase-subheading-broken.txt](https://github.com/Yoast/YoastSEO.js/files/2471999/keyphrase-subheading-broken.txt)

Keyphrase: `keyword research mistakes`

## Technical info

* Platform: WordPress
* Platform version: 9.0RC

**Comment by nataliashitova** [comment]
As per https://github.com/Yoast/YoastSEO.js/wiki/Scoring-SEO-analysis#5-keyword-in-subheadings and https://github.com/Yoast/YoastSEO.js/issues/1558 the subheadings is considered to reflect the topic of the copy if more than half of content words are found in it. If between 30 and 70% of subheadings reflect the topic, the assessment returns a green bullet. From what I see only the first and the last subheadings in the copy reflect the topic (they use the words "keyword" and "research".  Two subheadings out of 8 make 25%. Therefore, a red bullet.

**Comment by jdevalk** [comment]
[keyword-research-ultimate-guide.txt](https://github.com/Yoast/YoastSEO.js/files/2472066/keyword-research-ultimate-guide.txt)

One more. Keyphrase "keyword research"

**Comment by jdevalk** [comment]
I honestly think that if those don't match our boundaries then we need to change our boundaries.

**Comment by manuelaugustin** [comment]
New rule: one subheading with a match is enough for a green bullet.

The matching mechanism can stay the same.

**Comment by nataliashitova** [comment]
@hansjovis The last copy sent by Joost has no subheading tags, you can use this one with the subheadings recovered.
[keyword-research-ultimate-guide copy.txt](https://github.com/Yoast/YoastSEO.js/files/2472247/keyword-research-ultimate-guide.copy.txt)
