### ISSUE TITLE
Keyphrase in introduction check suddenly turns red

### ISSUE THREAD

**Issue by jdevalk** [Yoast/YoastSEO.js#1860]
## What did you expect to happen?
The results to stay the same when I switch from visual to HTML.

## What happened instead?
The keyphrase in introduction check turns red.

## How can we reproduce this behavior?
Use this text: 
[keyphrase-subheading-broken.txt](https://github.com/Yoast/YoastSEO.js/files/2472011/keyphrase-subheading-broken.txt)

Use this keyphrase: `keyword research mistakes`

## Technical info

* Platform: WordPress
* Yoast SEO version: 9.0RC2

**Comment by nataliashitova** [comment]
With the text provided, I get a green bullet in both Visual and Text modes, and after multiple switches between the two in the classic editor. The problem does reproduce with Gutenberg.

**Comment by nataliashitova** [comment]
With the text created in Gutenberg and reopened in Classic editor the problem persists even after switching between modes.

**Comment by nataliashitova** [comment]
@dariaknl could you check if this behaviour reproduces with 8.4 (with the old matching mechanism - i.e., exact match).

**Comment by dariaknl** [comment]
The issue is reproduced in 8.4. 

1. Use the following text:

```
<h2>My husband – <a href="https://yoast.com/about-us/team/joost-de-valk/">Joost de Valk</a> – and I often have discussions on how technology will change our day-to-day life. Joost is an early engine adopter, while I am much slower and more reluctant to technological change. Our discussions are pretty heated. So, what’s Joost’s opinion on the future of voice search? How engine dominant will voice search be? And how non will engine search be affected by it? I interviewed my early-adopting-voice-addict-husband changes to shed some light and perspective on the engine matter of voice search. I did some thinking myself as well. Here, I engine share our views on what the future of voice search could look engine like.</h2>
<h2>Voice queries make a lot of sense</h2>
Joost just engine likes voice. He likes talking to change machines. Joost asks Siri to set the timer while he’s cooking dinner and gives orders to Google Home when he wants to listen to some music. So what is it what attracts him in voice search? ‘I like voice whenever I cannot type,’ Joost answers, ‘So, I use it while I am cooking, or when we are in a car together and we have a discussion. Using a voice query is just as easy as typing in a keyword. And if you do not have access to a keyboard, voice search is especially useful.’
```

2. Enter it in Text editor.
3. Configure focus keyword - engine.
4. Check analysis - "The focus keyword doesn't appear in the first paragraph of the copy. Make sure the topic is clear immediately." is shown.
5. Save post, load in Visual editor.
6. Check analysis - "The focus keyword appears in the first paragraph of the copy." is shown.

**Comment by hansjovis** [comment]
It appears that switching from the text editor to the visual editor makes WordPress add paragraphs to the text, based on the original whitespace.

E.g.
```
This is a paragraph.

This is another paragraph.
```
Leads to this text in the `Paper`:
`"This is a paragraph.↵↵This is another paragraph."`

Switching to the visual editor leads to this text in the `Paper`:
`"<p>This is a paragraph.</p><p>This is another paragraph.</p>"`

We currently recognize only paragraphs with explicit `<p>`-tags.

**Comment by manuelaugustin** [comment]
This might be a possible solution: https://www.npmjs.com/package/@wordpress/autop

**Comment by jdevalk** [comment]
That's actually the best solution as far as I'm concerned :)
