### ISSUE TITLE
Don't show feedback if no keyword was set for related keywords

### ISSUE THREAD

**Issue by manuelaugustin** [Yoast/YoastSEO.js#1869]
The keyphrase length assessment should show no feedback for related keyphrases when no keyphrase is set. This is the specific feedback string:

`No focus keyphrase was set for this page. Set a keyphrase in order to calculate your SEO score.`

Note: We still want to show feedback when the keyphrase is too long. 

Some possible ways to achieve this: Ideally we should find a way to pass parameters in the related keywords assessor that will make sure that this condition isn't triggered. If that's not possible, we might need to consider to split up the assessments so that there is a specific assessment when there is on keyphrase vs. when the keyphrase is too long.

**Comment by nataliashitova** [comment]
Clarified  specification:
The feedback string of the keyphrase length assessment should keep being shown for additional keyphrases, when the keyphrase gets erased. But it should not say `focus keyphrase` anymore, but just `keyphrase`.

**Comment by manuelaugustin** [comment]
Acceptance 🚧

The sentence `No keyphrase was set for this page.`
 shouldn't be shown for related keywords. Sorry for this extra bit of confusion, my bad 🙈
