### ISSUE TITLE
Increase upper keyword density boundary by 0.5% in Premium

### ISSUE THREAD

**Issue by manuelaugustin** [Yoast/YoastSEO.js#1870]
The upper keyword density boundary should be increased by 0.5% in Premium. This will result in the following new boundary: `maximum: 3.0`

**Comment by manuelaugustin** [comment]
@jdevalk We've discussed the implementation of this, and we think it would make sense to also take the language into account. So then we'll only change the boundary if you have premium _and_ your language is English (because that's the only language in which we have word forms at the moment). Please let us know if that is acceptable.

**Comment by jdevalk** [comment]
👍🏻
