### ISSUE TITLE
Webworker should be able to pass parameters to assessors

### ISSUE THREAD

**Issue by manuelaugustin** [Yoast/YoastSEO.js#1875]
We want the webworker to be able to pass parameters to the assessors, which then should pass them to the assessments.

Specifically, we need the webworker to pass a string with information concerning tracking (see https://github.com/Yoast/wordpress-seo/issues/11254). This information then needs to be passed to the assessments. Each assessment needs to append this information to its short links. See https://github.com/Yoast/YoastSEO.js/issues/1876

**Comment by hansjovis** [comment]
Closed in favor of #1877 . Passing the parameters to the assessments will be solved in that PR, using a 'global' singleton class.
