### ISSUE TITLE
[Feature Request] Improve Word Count Related To Shortcodes

### ISSUE THREAD

**Issue by amboutwe** [Yoast/YoastSEO.js#188]
We know the common structure of shortcodes but don't properly account for shortcode options when counting words in a post. This causes an inflation of words which causes other analysis to return inaccurate.

**Example**
`[text]This is some text that appears in a shortcode with no options.[/text]
[button option="large" option2=""]This is a button[/button]`

**Word Count**
Actual: 16
Yoast SEO: 21

The difference is caused by:
`.` = 1 word
`option="large"` = 2 words
`option2=""` = 2 words

User's example:
The page has around 550 words but now the plugin is seeing 1596 words due to shortcode options thus causing the keyword density to be incorrectly calculated.

**Comment by AskKim** [comment]
Please let user in ticket # 91114 know when this is closed.

**Comment by AskKim** [comment]
Please inform the customer of conversation # 93418 when this conversation has been closed.

**Comment by atimmer** [comment]
Shortcodes should be handled by de shortcode plugin in Yoast SEO.
