### ISSUE TITLE
Featured image affects keyword distribution check

### ISSUE THREAD

**Issue by monbauza** [Yoast/YoastSEO.js#1891]
## What did you expect to happen?
The featured image of a post wouldn't affect the keyword distribution check.

## What happened instead?
When a featured image is added to a post, there are cases where the keyword distribution check changes from `Your keyword is distributed evenly throughout the text. That's great.` to `Some parts of your text do not contain the keyword. Try to distribute the keyword more evenly.`

## How can we reproduce this behavior?

1. Create a new post
2. Fill in a focus keyword, i.e. _Lorem ipsum_
3. Add some text and make sure the focus keyword is distributed evenly (sample text below)
4. Note that the keyword distribution check is green
5. Add a featured image to the post 
6. Save the post
6. Note that the keyword distribution check changes to orange

![image](https://user-images.githubusercontent.com/9658774/47150662-8ec6e080-d2d7-11e8-857d-f4010cabdfc7.png)

## Sample text

> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas a eros nec lectus accumsan pharetra vitae a erat. Duis egestas tellus eget massa imperdiet malesuada. Donec in lacinia magna. Etiam pulvinar, eros sed pulvinar cursus, odio dolor egestas risus, eu imperdiet mauris nibh rutrum justo. Maecenas id fermentum tellus. Mauris in dolor ante. Suspendisse tempor vitae leo porta auctor. Donec auctor vehicula neque, sed tincidunt augue hendrerit id. Curabitur hendrerit dolor ac nulla tempus, a iaculis leo pellentesque. Donec ornare, mauris non finibus pretium, eros metus aliquet tortor, eget consequat neque velit id nulla.
> 
> Lorem ipsum duis id interdum felis, vitae porttitor ex. Nulla in fringilla leo. Morbi in convallis justo, sit amet viverra nisl. Pellentesque eu velit eleifend, pellentesque tellus vulputate, dignissim mauris. Aenean mattis finibus neque a mattis. Phasellus lobortis libero vel ipsum consequat tempor. Maecenas quis massa vitae purus rutrum cursus.
> 
> Lorem ipsum maecenas pulvinar ultricies posuere. Maecenas tincidunt nisi leo, id pretium mi dignissim eget. Nulla a libero dictum, eleifend urna vitae, placerat justo. Sed ultricies lorem sit amet tortor iaculis, a tristique nisl consectetur. Quisque commodo orci porttitor orci dignissim, at fringilla tortor aliquet. Morbi congue mi ac erat posuere, a blandit nisl accumsan. Nulla ornare aliquam orci id cursus.
> 
> Lorem ipsum integer placerat eu quam vel porta. Ut tincidunt dolor nec accumsan consequat. Morbi dictum est in nibh molestie, sollicitudin cursus erat efficitur. Mauris ut nibh ultrices, sollicitudin sem eget, ultrices diam. Sed quis porta nisi. Donec consequat ante quis pulvinar tincidunt. Ut ante est, hendrerit vitae porta et, laoreet sit amet purus. Vivamus tristique elementum nulla, vestibulum tempus lectus fringilla suscipit.

## Technical info
* Platform: WordPress v4.9.8
* Yoast SEO Premium version: 8,4

**Comment by monbauza** [comment]
Please inform the customer of conversation # 434924 when this conversation has been closed.

**Comment by benvaassen** [comment]
No longer happens with 9.0.3. Therefore, closing.
