### ISSUE TITLE
Update Readme with tests API and plugin init docs

### ISSUE THREAD

**Issue by omarreiss** [Yoast/YoastSEO.js#190]
Including WP specific plugin info.

**Comment by stramel** [comment]
Would love to have a nice example and better documentation on how to get going.

**Comment by amboutwe** [comment]
From a premium user

>A simple solution which I'm trying to get to is to have a piece of JQuery that pulls off the html from an id or a class on a page and passes that to the SEO analysis. That would work for me, and I think it would work for the vast majority of other people, this would be simple to implement, and simple to understand.

**Comment by beatelite** [comment]
Completely agree with all of this. We need better documentation to do a basic task like analyze a string from an id or class. I am very familiar with Js and can't even get basic analysis going. 

help!

**Comment by Djennez** [comment]
Closing this as a duplicate of / in favor of https://github.com/Yoast/YoastSEO.js/issues/181 (that thread is older and has some additional info, even though it's probably outdated).
