### ISSUE TITLE
Grunt get-premium-configuration

### ISSUE THREAD

**Issue by igorschoester** [Yoast/YoastSEO.js#1904]
There is a Grunt task `get-premium-configuration`, this clones the premium configuration repo.

- The command fails when someone does not have access to the repo. This should fail more gracefully.
- When the command failed the tests that need the configuration (currently: where the `morphologyData.json` is imported) should not be run.

**Comment by moorscode** [comment]
To better state the problem: this blocks external contributors from creating PR's as the Travis builds will fail all tests.

**Comment by igorschoester** [comment]
This is fixed by having Travis run the grunt task (through `install-ci`).
