### ISSUE TITLE
YoastSEO.js Example: KeyphraseDistribution toggle does not update the results

### ISSUE THREAD

**Issue by nataliashitova** [Yoast/YoastSEO.js#1908]
KeyphraseDistribution toggle does not trigger the re-analysis. Only toggle + refresh results in a new set of results. 

We need to make sure switching the keyphrase distribution on and off results in reanalysis of results.

**Comment by igorschoester** [comment]
I do not have this problem, though I did see it on your computer. There is something else going on probably.

**Comment by igorschoester** [comment]
Closing, see https://github.com/Yoast/YoastSEO.js/pull/1853#issuecomment-432997781 for more info.
