### ISSUE TITLE
Recalibration beta phase: overview

### ISSUE THREAD

**Issue by manuelaugustin** [Yoast/YoastSEO.js#1913]
## Context
When rolling out the code from recalibration, we want initially do that in a beta phase. In this beta phase, users should be able to switch back and forth between the recalibrated version and the old version. We want to be able to make changes to the new recalibration code and make this code available to users immediately. 

## Specs
**Team Lingo**
- New `recalibratedSEOAssessor` + all related assessors (`relatedKeyphrasesAssessor` etc.)
- Duplicate all assessments and researches that need to diverge from existing ones and that cannot be reused in their current shape.
- Have a way to conditionally load `recalibratedSEOAssessor` instead of `SEOAssessor`.

**Team Plugin**
- Plugin team should provide the condition, which will need to be set based on toggle, that switches an option on and off.
- Add a notification to point to the feature toggle 

**Team Platform**
- Platform team should provide an endpoint where the JavaScript can be downloaded.
- Together with platform team figure out a way to automatically deploy changes to the JavaScript.
- The JavaScript download will not be authenticated (unlike the premium config). Users don’t need a Yoast account. Downloads should be cached in Cloudflare.

**Comment by nataliashitova** [comment]
Question about code reduplication to @omarreiss 

If we only need to be able to adjust assessment boundaries or add|remove assessments from assessor, this can simply be done within one configuration file. Duplicating all assessments and assessors will be so difficult to maintain!
If we also want to have access to two versions of researches at the same time, we could pass a version value (`regular` or `recalibration`) to the `researcher` and make sure all researches return the same type of data no matter which version of the research code is used.

Are there other reasons why reduplication is necessary?

**Comment by omarreiss** [comment]
If the behavior of two assessments diverges from the current implementation to the recalibration, then it makes sense to duplicate. If only the config differs, then you can solve it in the config layer. I don't mind the implementation so much. I'm just saying don't be afraid to maintain two versions of something as long as we are in beta.

**Comment by manuelaugustin** [comment]
This project has been completed.
