### ISSUE TITLE
Snippet editor shows wrong URL on Front Page

### ISSUE THREAD

**Issue by monbauza** [Yoast/YoastSEO.js#192]
It always displays domain/example-post/ whereas it should read just the domain

![image](https://cloud.githubusercontent.com/assets/9658774/11360939/5c9dec7a-9289-11e5-88bf-5727d0c7316a.png)

**Comment by monbauza** [comment]
Please inform the customer of conversation # 89617 when this issue has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 89183 when this issue has been closed.

**Comment by AskKim** [comment]
Although this is probably a YoastSEO.js issue, this ticket may be a duplicate of this other one: https://github.com/Yoast/wordpress-seo/issues/3370

**Comment by atimmer** [comment]
This has been fixed in Yoast SEO 3.1, which corresponds to YoastSEO.js 1.1.
