### ISSUE TITLE
Export to npm with a normal build and an ES6 build

### ISSUE THREAD

**Issue by atimmer** [Yoast/YoastSEO.js#1930]
## What did you expect to happen?

I expect to be able to consume an ES6 project if my toolchain supports it, but I don't want to run babel on all of YoastSEO.js.

## What happened instead?

I have to run babel on all of YoastSEO.js or I can't use ES6 modules.

## Technical details

For an example of how this could work you could look at [Gutenberg](https://github.com/wordpress/gutenberg). They build to a `build` folder and a `build-module` folder. `build` is then specified as the `main` entry point in the `package.json`. `build-module` is specified as `module` entry point in the `package.json`. In both builds all other ES6 syntax is transpired down to ES5.

**Comment by omarreiss** [comment]
Will come up again during audit.
