### ISSUE TITLE
Images keyphrase: check how many matches there are

### ISSUE THREAD

**Issue by manuelaugustin** [Yoast/YoastSEO.js#1938]
Currently we give a green bullet when at least one image has an alt text with the keyword.

The boundaries of this check should change. The check should be triggered when there are ≥5 images. The boundaries can be the same as for the keyword in subheadings assessment (min 30, max 75%).

For more context/a previous implementation of this, see https://github.com/Yoast/YoastSEO.js/issues/1388 (+ related PR).

**Comment by nataliashitova** [comment]
From [this PR](https://github.com/Yoast/YoastSEO.js/pull/1527/files) I understand that the assessment should **still be triggered** if there are less than 5 images, but the scoring schema should be different then.

> When there less than 5 images, including an alt tag with the keyword at least once will always result in a green bullet. There is no upper limit. When there are exactly five images, 2-4 alt tags with keywords will result in a green bullet. This has been hard-coded since it's on the border between the less strict and the stricter condition. When there are 6 or more keywords, the number of alt tags with the keyword should be between 30% & 75% of all images.
