### ISSUE TITLE
Disable marker for "subheading followed by..." assessment

### ISSUE THREAD

**Issue by moorscode** [Yoast/YoastSEO.js#1956]
As this is a marker that fails more often than it works, we need to disable it first.

Alternative approaches:
- marking the subheading
- mentioning the subheadings that are being affected in the assessment result

The effort that would be required needs to be determined.
_The HTML Parser should provide a solid way of marking this assessment as it is currently meant to work._

Related https://github.com/Yoast/YoastSEO.js/issues/1195

**Comment by moorscode** [comment]
Note: "html parser" label has been added for context on that label, it does not require the parser to be implmented.

**Comment by hansjovis** [comment]
I looked at the current implementation, and it is better to disable the markers for now.

The current implementation replaces the headers in the text with pipe characters (`|`) and then splits on these characters. Reworking the code to keep information about the headers would take to much effort in this small time frame.
