### ISSUE TITLE
Weight prominent words by TF-IDF score.

### ISSUE THREAD

**Issue by hansjovis** [Yoast/YoastSEO.js#1960]
## Summary
The prominent words check looks at the most prevalent terms in the article. However, it only looks at the raw term count. This leads to words that naturally occur more to have an undeserved place on the list. 

We already counteract this effect for a language as a whole by filtering out the most common function words. 

However, we can counteract this for terms that occur often **on the blog** as well. 

We can do this by penalizing prominent terms based on how often they occur on the website as a whole (e.g. by using Term Frequency - Inverse Document Frequency (TF-IDF) weights).

It will (hopefully) also lead to better internal linking suggestions, since this is implemented by looking at the overlap between prominent words in articles.

## Explanation
Let's say Julie has a blog about dancing shoes. She writes an article on dancing shoes for kids. The fact that the term "dancing shoes" occurs often in the article does not add any meaningful information, since the whole website is about this subject. However, the term "kid(s)" does have meaning. By giving "kid(s)" more weight than "dancing shoes", it increases the chances of it being in the prominent word list, even if it occurs less frequent in the article.

Moreover, Julie would get articles suggested that are specifically about kids, since "dancing shoes" will not be on the most prominent word list (or given less weight, depends on the implementation).

## Technical details
[Term Frequency - Inverse Document Frequency](https://en.wikipedia.org/wiki/Tf%E2%80%93idf) (TF-IDF) is the most commonly used weighting scheme for this sort of thing. It is scientifically well studied and works well.

We would need to compute the document frequencies for each term on the website regularly, to keep it up to date.

**Comment by omarreiss** [comment]
This seems fixed with improved internal linking.
