### ISSUE TITLE
Error in the German transition words list

### ISSUE THREAD

**Issue by rmarcano** [Yoast/YoastSEO.js#2004]
A user has reported an error in the German transition words list:

> The word combination [ "je", "umsto" ] is incorrect. The correct spelling is [ "je", "umso" ]

This affects the two part transition words list:
https://github.com/Yoast/YoastSEO.js/blob/develop/src/researches/german/twoPartTransitionWords.js

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 445481  when this conversation has been closed.

**Comment by SergeantRaccoon** [comment]
["je", "desto"]
