### ISSUE TITLE
Analyse content on the generated page instead of only on the editor content

### ISSUE THREAD

**Issue by Betoniara** [Yoast/YoastSEO.js#201]
This solution is totally wrong.
To include only the content entered in wordpress editor.
In my opinion it would be best to put up an iframe with a generated page
and analyze the whole (header, footer, sidebar and content), then it will be meaningful and sensible.

**Comment by stramel** [comment]
I can see where you are coming from on this. I have a template that adds in a lot of default structure to the HTML that is important to the page. (ie h1,h2, p, aside, etc). I have to manually add that to the post content in the plugin.

**Comment by atimmer** [comment]
This is a great idea! Keeping this open as a reminder to make this possible someday.

Historically the content analysis has evolved to only analyze the content entered in the WordPress. This is the easiest way to do content analysis, analysing on the front end is a whole different task.

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/wordpress-seo/issues/6641

**Comment by Pcosta88** [comment]
related https://github.com/Yoast/wordpress-seo/issues/6122

**Comment by monbauza** [comment]
Please inform the customer of conversation #  541877 when this conversation has been closed.

**Comment by Pcosta88** [comment]
related https://github.com/Yoast/wordpress-seo/issues/7960

**Comment by Pcosta88** [comment]
related https://github.com/Yoast/YoastSEO.js/issues/985

**Comment by Pcosta88** [comment]
related https://github.com/Yoast/wordpress-seo/issues/7498

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 546682 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 548046 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 553828 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 555135 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 559984 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 565325 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 573852 when this conversation has been closed.

**Comment by Pcosta88** [comment]
User says

> Within its complexity, I think that this would be easier than it seems, your plugin would not have to render anything, it would be to put a special button on the top wordpress bar, the one that is displayed on the front-end, said button would show a window with the suggestions for this page and with the possibility of varying different parameters.

**Comment by Pcosta88** [comment]
Moved to https://github.com/Yoast/featurerequests/issues/710
