### ISSUE TITLE
The wordboundary regex is broken with consecutive keywords

### ISSUE THREAD

**Issue by terw-dan** [Yoast/YoastSEO.js#203]
The wordboundary regex we use isn't working when keywords are used consecutively in a sentence. 
This issue was also present in 2.3.5

The phrase "a keyword and a keyword" will match keyword twice (as it should)
When using "a keyword keyword keyword" will match the keyword only twice, in stead of 3 times. 

This is due to the fact the regex matches the whitespaces around the keyword as well. This screenshot taken from regexr shows it how it is matched. 
<img width="563" alt="screen shot 2015-12-15 at 15 13 44" src="https://cloud.githubusercontent.com/assets/11272096/11812903/e3fde8f8-a33e-11e5-847e-e443db257fae.png">

Only the first and third occurence of the keyword is matched, not the second one.

**Comment by stramel** [comment]
What about doing something like `/(^|[\s\n\r\t\.,'\(\)\"\+;!?:\/<>])keyword($|[\s\n\r\t\.,'\(\)\"\+;!?:\/<>]*?)/gm` Where you make the last one match zero+ times but make it lazy.
![Lazy Regex](http://i.imgur.com/4ko5CuN.png)

**Comment by atimmer** [comment]
This can be solved with a positive lookahead in the word boundary after the word.
