### ISSUE TITLE
Cornerstone TextLength assessment returns suboptimal feedback

### ISSUE THREAD

**Issue by nataliashitova** [Yoast/YoastSEO.js#2032]
## What did you expect to happen?

The plugin to return a good feedback string for a 400-word cornerstone text.

## What happened instead?

<img width="645" alt="screen shot 2018-11-28 at 10 50 39" src="https://user-images.githubusercontent.com/36954173/49143791-143ca800-f2fc-11e8-8f2c-a300405d1523.png">

## How can we reproduce this behavior?
Enter a text which contains 401 words and observe the result.

## Technical info

* Platform: WordPress
* Platform version: 4.9.8
* Yoast SEO version: 9.3.1

**Comment by nataliashitova** [comment]
I suggest to raise the OK boundary for cornerstone articles up to 650. A text that is 401 words long will then get a bad score and _"This is below the recommended minimum"_. Does it make sense from the SEO perspective @jdevalk?

Currently, we have the following boundaries and feedback strings for this assessment

|boundaries|regular/cornerstone content|regular/corenersone score|feedback string|
|---|---|---|---|
|recommended minimum|300/900|9|_Good job_|
|slightly below minimum|250/**400**|6|_This is slightly below the recommended minimum_|
|below minimum|200/300|3|_This is below the recommended minimum_|
|veryFarBelowMinimum|100/100|-10/-20|_This is far below the recommended minimum_|
|||||-20|_This is far below the recommended minimum_|

For cornerstone, this gives a text that is 401 words long an orange bullet and a feedback _"This is slightly below the recommended minimum"_, although the user still needs to write more than twice as much content to get to the green point.

**Comment by jdevalk** [comment]
I'm fine with upping, just want _some_ rationale for the number we choose :)
