### ISSUE TITLE
Focus Keyword with '-' Not Recognized

### ISSUE THREAD

**Issue by amboutwe** [Yoast/YoastSEO.js#206]
*Sample Text* - Doctor has extensive experience in the provision of medico-legal reports for various chronic pain syndromes following personal or occupational injuries and complex regional pain syndrome.

*Focus Keyword* - medico-legal

*Analysis Warning* - The focus keyword doesn't appear in the first paragraph of the copy. Make sure the topic is clear immediately.

If you change "medico-legal" to "medico legal" in the text and keyword, the message changes to "The focus keyword appears in the first paragraph of the copy."

**Versions**
WP 4.4
Yoast SEO 3.0.6
Theme: Twenty Fifteen

**Comment by stramel** [comment]
In issue #203 I posted a regex that seems to work when I run it on the provided text and keyword.

![regex](http://i.imgur.com/sjHuy7F.png)

**Comment by AskKim** [comment]
Please inform the customer of conversation # 93136 when this conversation has been closed.

**Comment by AskKim** [comment]
Please inform the customer of conversation # 93418 when this conversation has been closed.
