### ISSUE TITLE
YoastSEO 1.44.0 breaks yoast-components in IE11

### ISSUE THREAD

**Issue by afercia** [Yoast/YoastSEO.js#2086]
While working on yoast-components on a PR for https://github.com/Yoast/wordpress-seo/issues/11935 I faced some errors in IE11.

This morning, the yoast-components standalone demos worked in IE11 for me, but in the afternoon they stopped working. Blank page. Turns out I was working on yoast-components `develop` not updated with latest changes. 

After some investigation, `git bisect` told me the offending commit was `8903ccf Merge remote-tracking branch 'origin/release-yoast-seo/9.4' into Add-Courses-Cards` which changed, among other things, the yoastseo version.

To reproduce:
- use IE11
- on yoast-components, run `yarn` to make sure everything is updated
- run `yarn start` and go to the standalone demos on http://localhost:3333/
- open the IE11 console (press F12)
- note that the IE11 console needs to be open, this is a pre-existing issue: without opening the console you won't see anything
- even with the console open, you will get a blank page
- see a couple of cryptic JS errors in the console: one of them seems related to the relevant words

Once you've reproduced the blank page:
- stop the demos with `Ctrl+C`
- edit the yoast-components `package.json`
- revert yoastseo to `"yoastseo": "^1.43.0"`
- run `yarn`
- run `yarn start` and check the standalone demos on http://localhost:3333/ now work in IE11

**Comment by afercia** [comment]
I'm not sure this is the only reason, but to start with, `startsWith` 😆used by fbjs is not supported by IE11. It needs a polyfill.
Tried to use `babel-polyfill` like we're doing in yoast-components, and here's the webpack example running in IE11:

![screenshot 170](https://user-images.githubusercontent.com/1682452/50635139-3b1c7880-0f51-11e9-9b96-4bcf9098c8d4.png)

However, I've then tried to yarn-link yoastseo to yoast-components and it fails: `Module build failed: Unknown plugin react-hot-loader/babel specified in base.env.development at 0, attempted to resolve relative to {local YoastSEO.js path here}`. This could be related to paths on Windows maybe, also not sure if it has ever worked.

**Comment by hansjovis** [comment]
I installed a Win7-IE11 Virtual Machine and am able to reproduce both issues*, so I can test it on my own machine. I am now investigating further!
  
*: _The cryptic error message relating to `fbjs` using `startsWith` which is not possible in IE11, and the `Module build failed: Unknown plugin react-hot-loader/babel specified` error in the IE11 console after adding `babel-polyfill`._

**Comment by hansjovis** [comment]
Progress! 🙂 

Adding the development dependencies (on top of `babel-polyfill`) in `yoastseo.js`:
* `babel-plugin-styled-components`
* `react`
* `react-dom`
* `react-hot-loader`

Fixes it:
<img width="1317" alt="screen shot 2019-01-08 at 11 35 56" src="https://user-images.githubusercontent.com/10195175/50825796-3a615900-133a-11e9-9785-76509cef9df2.png">

**Comment by hansjovis** [comment]
We (team Lingo, @moorscode and @atimmer) decided to first implement a decent Windows + IE11 / Edge test environment before picking this one up again.
Having one will make (regression) testing functionality in IE11 that much easier and faster during development.
