### ISSUE TITLE
Add word form recognition for German - overview issue

### ISSUE THREAD

**Issue by manuelaugustin** [Yoast/YoastSEO.js#2095]
We should add word form recognition in German.

The basic functionality should encompass the following:
- [x] Noun morphology #2049 
- [x] Adjective morphology #2127 
- [x] Verb morphology #2132 
- [x] Move German morphology data into a separate file #2145

Stretch goals:
- Improve our predictions regarding word sort, e.g. only add regular noun suffixes when we recognize that a word is most likely a noun.
- Recognizing diminutives (e.g. _Hund_ - _Hündchen_)
- Recognizing gender forms for role nouns (e.g. _Student_ - _Studentin_)

**Comment by dariaknl** [comment]
QA feedback:
* the feature is to be tested by native speaker paying attention to goals mentioned in the issue
* as German morphology would be brought as a new feature, the current German translation of our premium plugin was checked. The following points are worth mentioning:

1. Only few analysis strings from both Readability and Keyphrase analysis are translated into German.
2. Our metabox is inconsistently translated, for example a word "Keyphrase" is translated differently 3 times:
<img width="375" alt="screenshot 2019-03-06 at 09 26 48" src="https://user-images.githubusercontent.com/19681708/53866570-23657d00-3ff2-11e9-8a0b-afa213c465d1.png">
These translations are coming from both free plugin translations and premium plugin translations. Discussed this issue with Christina Arntz (as she is going be this feature "native speaker" acceptance tester), she points out that these translations can influence the user experience with German morphology feature.

**Comment by manuelaugustin** [comment]
German word form recognition is complete. Stretch goals moved to https://yoast.atlassian.net/browse/LIN-577
