### ISSUE TITLE
Grunt build recalibration task isn't working

### ISSUE THREAD

**Issue by manuelaugustin** [Yoast/YoastSEO.js#2100]
The `grunt webpack:recalibration` task doesn't correctly build the analysis files as described here: https://github.com/Yoast/YoastSEO.js/wiki/How-to-test-Recalibration-locally%3F. This currently makes it impossible to test recalibration-related changes locally without using the dev server.

The solution to this is probably to make the following changes in `wordpress-seo/grunt/config/webpack.js/`:
```
	buildDev: () => webpackConfig( { environment: "development" } ),
	buildProd: () => webpackConfig(),
	recalibrationDev: () => webpackConfig( { environment: "development", recalibration: "enabled" } ),
	recalibration: () => webpackConfig( { recalibration: "enabled" } ),
```

**Comment by igorschoester** [comment]
Superseded by https://github.com/Yoast/wordpress-seo/pull/12085
