### ISSUE TITLE
Previously used keyphrase: You've used this keyphrase once before. Do not use your keyphrase more than once fails to show display render when keyword is a related keyphrase secondary keyword

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/YoastSEO.js#2105]
## What did you expect to happen?

When a previously used keyword is in the secondary keyword spot, Yoast would show the warning

## What happened instead?

It did not

## How can we reproduce this behavior?

1.Create a post

2.Add a previous used keyword in the first spot

3.See the warning  show

<img width="843" alt="screen shot 2019-01-25 at 8 54 43 am" src="https://user-images.githubusercontent.com/8238074/51750022-e3b88680-207e-11e9-8ac3-43a97387d79f.png">

4.Remove keyword from first spot and add it to second and see warning fail to show

<img width="1170" alt="screen shot 2019-01-25 at 8 55 37 am" src="https://user-images.githubusercontent.com/8238074/51750080-00ed5500-207f-11e9-980f-85d9f6f59a74.png">

## Technical info

* Platform: WordPress 
* Platform version: 5.0.3
* Yoast SEO version: 9.5

**Comment by monbauza** [comment]
Please inform the customer of conversation # 487608 when this conversation has been closed.

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 532864 when this conversation has been closed.

**Comment by Djennez** [comment]
Closing per https://github.com/Yoast/bugreports/issues/834
