### ISSUE TITLE
Implement TreeAssessor

### ISSUE THREAD

**Issue by atimmer** [Yoast/YoastSEO.js#2123]
A `TreeAssessor` should be able to analyze a `Paper` in combination with the `Tree` that has been generated from the text inside the `Paper`.

Unlike the current `Assessor` we will not have the `extends` mechanism for all the different types of assessors. I've identifier two differences between the different assessors:

* They have different assessments: We can solve this by providing the assessment in the constructor to the `TreeAssessor`.
* They have a different algorithm to calculate the overall score: We can solve this by using the [strategy pattern](https://en.wikipedia.org/wiki/Strategy_pattern)

So the `TreeAssessor` will have the following methods (`async` means the function returns a `Promise`):

* `constructor( options = { i18n, scoreAggregator, researcher, assessments = [] } )`, i18n, overallScoreStrategy and researcher are required.
* `getAvailableAssessments`, returns all the assessments that are available.
* async `isApplicable( assessment )`, the same as the current `isApplicable`, except that it should be async.
* async `assess( paper, node )`, same as the current `assess`, except that is returns the results instead of saving them to the object. It should also return the overallScore. It also doesn't have to check if there is a researcher, because that is a required constructor argument in the `TreeAssessor`.
* async `doAssessment( assessment, paper, node )`, same as current `executeAssessment`. Should execute single assessment, should be used in `assess` like it is used now. We don't need any logic for marks, however, because we are going to solve that in a different way.
* async `calculateOverallScore( results )`, this method calculates the overall result based on the given `results`. It uses the given `scoreAggregator` to do this.
* `addAssessment( name, assessment )`, same as the current `addAssessment`.
* `removeAssessment( name )`, same as the current `removeAssessment`.
* `getAssessment`, same as the current `getAssessment`.
* `getApplicableAssessments` can be written (copied), to make writing `assess` easier/DRY.

I will create issues for creating an `SEOScoreAggregator` and a `ReadabilityScoreAggregator`. So this isn't in scope for this issue, but you are going to need an aggregator to write unit tests (create a mock aggregator). So the API of the aggregator looks like this:

* async `aggregate( results )`, returns the overallScore based on the given results.`

Parent #1903

**Comment by hansjovis** [comment]
I have decided to not implement `isApplicable` on the `TreeAssessor` but only rely on the `isApplicable` method of the `Assessment`. In the current `Assessor` implementation, the only thing this method does is to call the same method on the assessment given to it as a parameter. We can skip this step completely by calling `Assessment.isApplicable` directly.
