### ISSUE TITLE
Load morphology data based on language

### ISSUE THREAD

**Issue by manuelaugustin** [Yoast/YoastSEO.js#2145]
At the moment, the recalibration data for German and English are in the same file. The data needs to be separated into language-individual files. Subsequently, we need to load the right file for the specific locale of the user.

Parent #2095
Parent https://github.com/Yoast/YoastSEO.js-premium-configuration/issues/11

Requires #2156

**Comment by igorschoester** [comment]
## Overview
### Premium
* Add language to the request.
### Premium configuration
* Determine the structure of the new files.
### MyYoast
* Send the requested language file back instead.

## Implementation
### Premium
* Add the (user) language to `MorphologyDataProvider`.
    * As class variable in the constructor.
    * As variable when initializing the `MorphologyDataProvider` class (in `metabox.js`)
    * As variable of the `retrieveData` function.
    * Pass it to the `retrieveData` call in the `injectMorphologyData` function.
    * As `language` key in the `data`, which is send in the request, inside `retrieveData`.
### Premium configuration
* Create a folder inside the `data` folder called `morphology`.
* Move / rename the current `morphologyData.json` to `morphology/en.json`.
* Adapt the `scripts/deploy.sh` to something that is discussed with the platform team.
    * Thinking about package morphology folder before sending it.
### MyYoast
* For platform to decide 🙂
