### ISSUE TITLE
Quotes in related keyphrase causes unexpected token in JSON error

### ISSUE THREAD

**Issue by monbauza** [Yoast/YoastSEO.js#2158]
## Description of the problem
In [this post](https://yoast.com/yoast-seo-9-0/), we explain that Yoast SEO filters function words by default and that you can force an exact match result by adding your focus keyphrase in quotes, i.e. "The Who". This works fine with the (main) focus keyphrase, however, when the quotes are used in related keyphrases, the error below appears in the browser's console. After saving the post, the related keyphrases are no longer shown in the Yoast metabox.

![image](https://user-images.githubusercontent.com/9658774/53157737-74bd4780-35c2-11e9-87c3-e2cca969e37d.png)

Note: Once the problem occurs, the WordPress database needs to be edited to fix it (in particular, the `_yoast_wpseo_focuskeywords` field in the `wp_postmeta` table) 

## How can we reproduce this behavior?

1. Install Yoast SEO Premium
2. Create a new post
3. Add a focus keyword and a related keyword that includes quotes (see screenshot below)
4. Save the post and reload the page
5. note that the aforementioned error appears in the browser's console and that it's no longer possible to add/edit related kephrases

![image](https://user-images.githubusercontent.com/9658774/53158501-0aa5a200-35c4-11e9-87b1-541d8aba313a.png)

## Technical info

* Platform: WordPress 5.0.3
* Platform version: Yoast SEO Premium 9.6.1
* Yoast SEO version:

**Comment by monbauza** [comment]
Please inform the customer of conversation # 475729 when this conversation has been closed.

**Comment by Djennez** [comment]
Bug confirmed. Seems like the normal keyphrase gets saved as a single instance with which quotes do not break. The related keyphrases get saved in the database as json arrays and break on double quotes:

![keyphrase](https://user-images.githubusercontent.com/34372510/53163784-26fb0c00-35cf-11e9-9109-1013979cf991.png)
