### ISSUE TITLE
[Enhancement] Do not Count the Bullet point or dot or other special characters as part of the Consecutive Sentences Warning

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/YoastSEO.js#2177]
## What did you expect to happen?

The bullet character would not be counted as part of the consecutive sentences warning

## What happened instead?

It Was

## How can we reproduce this behavior?

**1. Create sentences on new lines**

**2. On each new line preface it with a bullet**

**3. See Yoast pick-up the bullet point and count it as a consecutive sentence**

<img width="1209" alt="screen_shot_2019-02-27_at_11_19_32_am" src="https://user-images.githubusercontent.com/8238074/53505556-0d037280-3a82-11e9-8507-ffe74625987f.png">

**NOTES:**
The highlight tool is expected to highlight the bullet points

## Technical info

* Platform: WordPress
* Platform version: 5.1, Gutenberg
* Yoast SEO version: 9.7

**Comment by Djennez** [comment]
The analysis is correct, but the question is: do we want to count symbols and non-alphanumeric words and characters towards the consecutive sentence score? @manuelaugustin ?

Besides that question I think that this use-case is kind of an edge case. How often do bullets get freehanded instead of lists? It isn't practical and not very SEO friendly.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 589308 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation #622792 when this conversation has been closed.

**Comment by mmikhan** [comment]
@Djennez isn't it a duplicate of https://github.com/Yoast/YoastSEO.js/issues/1190?

**Comment by fabien-corail** [comment]
Has this been fixed ?

**Comment by rumejan** [comment]
Please inform the customer of conversation #643303 when this conversation has been closed.

**Comment by rumejan** [comment]
Please inform the customer of conversation #650710 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 650767 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 667603 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 667829 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 667179 when this conversation has been closed.

**Comment by Pcosta88** [comment]
related https://github.com/Yoast/featurerequests/issues/719

**Comment by michaelbriantina** [comment]
Please inform the customer of conversation # 677801 when this conversation has been closed.

**Comment by michaelbriantina** [comment]
Please inform the customer of conversation # 699934 when this conversation has been closed.

**Comment by josh-yoast** [comment]
Please inform the customer of conversation # 710783 when this conversation has been closed.

**Comment by michaelbriantina** [comment]
Please inform the customer of conversation # 765412 when this conversation has been closed.

**Comment by Djennez** [comment]
Closing this. For real lists, refer to this issue: https://github.com/Yoast/wordpress-seo/issues/17326 . For manually adding symbols at the start of a sentence... Well, it is theoretically still consecutive sentences starting with the same character / word.
