### ISSUE TITLE
Create `keyphrases` tree research

### ISSUE THREAD

**Issue by atimmer** [Yoast/YoastSEO.js#2193]
## Explanation

Create a `keyphrases` tree research that returns all the keywords in the ParsedPaper based on the Tree. 

The `keyphrases` research should return `Keyphrase` objects. The `Keyphrase` object should contain:

* References to the `Word` objects.
* A reference to the `Sentence` object.
* Start and end positions relative to the text container.

## Technical decisions

The `KeyphraseResearch` class should extend the [`Research` class](https://github.com/Yoast/YoastSEO.js/blob/develop/src/tree/research/researches/Research.js).

Given this input:

```js
let input = Paragraph( "There is a time and place for everything. When I find these times and places, I am happy." );
let keyphrase = "time and place";
```

Expected output for a node:

```js
let output = [
	{
		words: [
			Word( "time" ),
			Word( "and" ),
			Word( "place" )
		],
		sentences: [
                    Sentence( "There is a time and place for everything." ),
                ],
                isSynonym: false,
		startIndex: 11,
		endIndex: 25
	},
	{
		words: [
			Word( "times" ),
			Word( "and" ),
			Word( "places" ),
		],
		sentences: [
                    Sentence( "When I find these times and places, I am happy." ),
                ],
                isSynonym: false,
		startIndex: 60,
		endIndex: 76
	}
];
```

The indexes are relative to the containing text container. The objects are not new objects, but the objects that are already in the tree.

### FAQ

* Keyphrase twice in a sentence: It should be listed twice in the array with the same reference to the sentence.
* On the tree root level we just want a flat array of all keyphrase occurences.

### Product questions

* Should key phrases be able to span across sentences?

## Notes
- Is dependent on linguistic tree

See https://github.com/Yoast/YoastSEO.js/issues/2078 for decisions

**Comment by manuelaugustin** [comment]
@atimmer & @nataliashitova will have a second look at the spec of this issue. The goal is to make sure that the output produced by this research fulfills the requirements of the assessments.

**Comment by nataliashitova** [comment]
This issue is closed in favor of https://github.com/Yoast/javascript/issues/428.
