### ISSUE TITLE
transition words not recognized? 

### ISSUE THREAD

**Issue by cbernet** [Yoast/YoastSEO.js#2197]
## What did you expect to happen?

Transition words to be all recognized.

## What happened instead?

Some of them are not :

<img width="628" alt="image" src="https://user-images.githubusercontent.com/4138171/54067562-bb0cda80-4241-11e9-9d55-a8d4310b0b70.png">

As a consequence, yoast consistently ranks me low on transition words (~12%), while I use a lot of transition words.

## How can we reproduce this behavior?

I'm not sure you can, sorry.

## Technical info

* Platform: WordPress
* Platform version: 5.1
* Yoast SEO version: 9.7

Which browser is affected (or browsers): 
- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Other 

If relevant, which editor is affected (or editors): 
- [ ] Classic Editor
- [x] Gutenberg
- [ ] Classic Editor plugin

**Comment by Djennez** [comment]
Hi @cbernet , can you provide us with a text that is marked wrongly according to you? The image example you provided seems to be marked correct. Before and therefore are the only transition words in the beginning of sentences.

**Comment by cbernet** [comment]
Hi, thanks! From your answer, I now understand that in the case of transition words, the sentences that are marked are the ones which do contain a transition word. I wrongly assumed that the sentences that would be marked are the one that do not contain a transition word. Now, I'm getting the feeling that some sentences that contain a transition word are not marked. If that's indeed the case, I will file another bug report.  Sorry for bothering.

**Comment by Djennez** [comment]
No problem, we are aware that the marking is not very user-friendly at his moment and we're working on a revision that would invert the highlighting. There is not ETA for that yet unfortunately.
