### ISSUE TITLE
More transition words German

### ISSUE THREAD

**Issue by SereniTeaTime** [Yoast/YoastSEO.js#2200]
## What did you expect to happen?
Yoast to correctly recognize all transition words for German.

## What happened instead?
https://github.com/Yoast/YoastSEO.js/blob/develop/src/researches/german/twoPartTransitionWords.js:
https://github.com/Yoast/YoastSEO.js/blob/develop/src/researches/german/transitionWords.js

Ungeachtet dessen
Derweil 
Gleichzeitig
Zugleich
Nun
... and others are missing. Some exist in similar combos, not accounting for variety.

Let's add some!

## How can we reproduce this behavior?
Create any longer German text and observe transition word density changes when using the words above.

## Technical info

* Platform: WordPress 
* Platform version: 5.1
* Yoast SEO version: 9.7 (free)

Which browser is affected (or browsers): 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

If relevant, which editor is affected (or editors): 
- [ ] Classic Editor
- [ ] Gutenberg
- [ ] Classic Editor plugin

**Comment by Djennez** [comment]
Hi @SereniTeaTime and thank you for your request / suggestion. I've labelled this thread accordingly and someone from the linguistics team will investigate this further.
