### ISSUE TITLE
[Feature Request] Keywords which consist of two words separated by an exclamation mark or other ending-sentence-grammar mark fail should be detected

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/YoastSEO.js#2208]
Keywords which consist of two words separated by an exclamation mark or other ending-sentence-grammar mark fail should be detected by Yoast.

**1. Add a keyword with an exclamation mark in it like: Fritz!App through out the text**

<img width="716" alt="Screen_Shot_2019-03-26_at_2_08_27_PM" src="https://user-images.githubusercontent.com/8238074/55022311-b16ccc00-4fd0-11e9-854f-4541108bbed8.png">

**2.Keyword not detected**

<img width="1051" alt="Screen Shot 2019-03-26 at 2 04 56 PM" src="https://user-images.githubusercontent.com/8238074/55022321-b7fb4380-4fd0-11e9-87af-c9218c3895ce.png">

**3.Remove the second word of the keyword so it becomes: Fritz! and see Yoast detect it**

<img width="540" alt="Screen Shot 2019-03-26 at 2 09 49 PM" src="https://user-images.githubusercontent.com/8238074/55022386-d82b0280-4fd0-11e9-802c-3309754dc7c8.png">

**This will help improve the UX and Content SEO of the page.**

## Technical info

* Platform: WordPress  
* Platform version: 5.1.1.
* Yoast SEO version: 10.0.1

**Comment by Djennez** [comment]
Can you check if putting quotes (") around the keyphrase solves this?

**Comment by andizer** [comment]
I have a similar case with: `Bier! magazine` as keyphrase. Surrounding it by quotes doesn't seem to fix it.

**Comment by Djennez** [comment]
Duplicate of https://github.com/Yoast/YoastSEO.js/issues/2219
