### ISSUE TITLE
Not recognizing H1 headings

### ISSUE THREAD

**Issue by NegarKaviani** [Yoast/YoastSEO.js#2210]
Although I'm using H1 headings , in Seo Site Checkup headings are not recognized.
Is it necessary to buy yoast premium making Seo Site Checkup recognize these headings?

* Platform: WordPress | Drupal | Standalone
* Platform version:
* Yoast SEO version:

Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

If relevant, which editor is affected (or editors): 
- [ ] Classic Editor
- [ ] Gutenberg
- [ ] Classic Editor plugin

**Comment by Djennez** [comment]
There is no analysis for H1 headings in the plugin because there should only be one H1 heading in your page: the title of the post. Use H2 headings for the subheadings to make sure that the analysis works.
