### ISSUE TITLE
how to add H1 heading on main page

### ISSUE THREAD

**Issue by NegarKaviani** [Yoast/YoastSEO.js#2213]
Some websites show this error that there is no H1 heading on Home Page. 
for example: 
SeoSiteCheckup.com :
Your webpage does not contain any H1 headings. H1 headings help indicate the important topics of your page to search engines. While less important than good meta-titles and descriptions, H1 headings may still help define the topic of your page to search engines.

I'm using **free** yoast version and it doesn't have the accessibility to define H1 , H2 , ... headings on Home Page. 

Does Yoast Seo Premium give access to defining H1,H2, etc?

**Comment by Djennez** [comment]
Hi @NegarKaviani, please note that this is not a support forum.

We do not decide if your website does or does not use H1 or other heading tags, we just check if they are present in a post. You yourself are in charge of using heading tags in your texts and your theme is usually the part of your website that creates H1 tags.

Closing this as it is not Yoast related.

**Comment by NegarKaviani** [comment]
Thanks for your support. I just wanted to know more about yoast premium. 
Anyway, thanks for answering.
