### ISSUE TITLE
[Enhancement] When Flesch Reading Score ease is red or orange do not output a green Sentence Length: Great notification

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/YoastSEO.js#2217]
If you have a poor reading score that asks you to make shorter sentences, in some circumstances users may also get a green mark for having good sentence length. 

![Screen_Shot_2019-04-19_at_1_33_11_PM](https://user-images.githubusercontent.com/8238074/56436235-1acabc80-62a9-11e9-91d6-c7f2992a3527.png)

This seems inconsistent. What should users do?

Should they try to make shorter sentences even though their sentence length is already great?

Therefore to improve the analysis we should when Flesch Reading Score ease is red or orange do not output a green Sentence Length: Great notification.

This would help improve Content SEO and UX

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 496424 when this conversation has been closed.

**Comment by jdevalk** [comment]
I disagree with this. These two are related, but not the same.

**Comment by MinaMal** [comment]
I encounter this problem most of the time!
What is the difference between these two issues?
![image](https://user-images.githubusercontent.com/58623450/91639986-dd3c7e80-ea1a-11ea-9cc3-117121b1cfae.png)
