### ISSUE TITLE
Content analysis warnings inconsistent

### ISSUE THREAD

**Issue by jcomack** [Yoast/YoastSEO.js#222]
Currently when creating a post, the content analysis wil also check for a page title.
Because the SEO-title can be auto-filled by a template, I'd expect that the content analysis would consider this valid and not warn me that there's no page title. Perhaps it's a good idea to have the defined template function as a default value instead of a placeholder text?

Looking into this further, I noticed the content analysis warning regarding the 'missing' page title is slightly confusing, seeing as a **post** title was added. Also, the warning isn't as descriptive as the meta description warning which may lead to (some) confusion.

**Comment by Pcosta88** [comment]
**To update: The Yoast SEO warnings calls the SEO Title a "Page Title"**

![screen_shot_2017-04-04_at_4_28_10_pm](https://cloud.githubusercontent.com/assets/8238074/24677255/2a43b054-1954-11e7-8cb8-12a4bfe80089.png)


![2](https://cloud.githubusercontent.com/assets/8238074/24677272/3d681418-1954-11e7-853b-53a76f0fa505.png)

**Comment by CarolineGeven** [comment]
We cannot reproduce this issue with the current version of Yoast SEO, therefore this issue will be closed.
