### ISSUE TITLE
[Enhancement] If Keyword contains an ending punctuation like period exclamation point or question mark be able to find it in Meta Description

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/YoastSEO.js#2220]
If my keyword has an ending punctuation, Yoast considers it the ending of a sentence. This can affect the keyword analysis.

**1.Have keyword with an ending mark like FRITZ!App WLAN**

<img width="569" alt="Screen Shot 2019-04-24 at 8 32 07 AM" src="https://user-images.githubusercontent.com/8238074/56659590-86c37100-666b-11e9-9b89-0cddc4586468.png">

**2.Add it to the meta**

<img width="568" alt="Screen Shot 2019-04-24 at 8 46 38 AM" src="https://user-images.githubusercontent.com/8238074/56660423-7d3b0880-666d-11e9-9ec7-5f4841dffb29.png">

**3.But outputs notification that it cannot find the keyword:  Keyphrase in meta description: The meta description has been specified, but it does not contain the keyphrase. Fix that!
**

<img width="746" alt="Screen Shot 2019-04-24 at 8 45 13 AM" src="https://user-images.githubusercontent.com/8238074/56660400-73b1a080-666d-11e9-8e7f-1adf39a86598.png">

 

**Therefore, If Keyword contains an ending punctuation like period exclamation point or question mark be able to find it in Meta Description**

**This can help improve UX and Content SEO**

**Comment by Pcosta88** [comment]
related https://github.com/Yoast/YoastSEO.js/issues/2219

**Comment by Pcosta88** [comment]
related https://github.com/Yoast/YoastSEO.js/issues/2218

**Comment by Pcosta88** [comment]
related https://github.com/Yoast/wordpress-seo/issues/2163

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 496015 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 569063 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 626340 when this conversation has been closed.

**Comment by jdevalk** [comment]
This is fixed.
