### ISSUE TITLE
[Enhancement] If Keyword contains an ending punctuation like period exclamation point or question mark be able to find it in Subheading

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/YoastSEO.js#2221]
If my keyword has an ending punctuation, Yoast considers it the ending of a sentence. This can affect the keyword analysis.

**1.Have keyword with an ending mark like FRITZ!App WLAN**

<img width="569" alt="Screen Shot 2019-04-24 at 8 32 07 AM" src="https://user-images.githubusercontent.com/8238074/56659590-86c37100-666b-11e9-9b89-0cddc4586468.png">

**2.Add it in a subheading**

 
<img width="281" alt="Screen Shot 2019-04-24 at 8 50 35 AM" src="https://user-images.githubusercontent.com/8238074/56660686-0a7e5d00-666e-11e9-8c40-4cc8af57f91f.png">

**3.But outputs notification that it cannot find the keyword:  Keyphrase in subheading: Use more keyphrases or synonyms in your higher-level subheadings!
**

<img width="558" alt="Screen Shot 2019-04-24 at 8 49 08 AM" src="https://user-images.githubusercontent.com/8238074/56660658-f9cde700-666d-11e9-9ede-590909b10cc0.png">

**Therefore, If Keyword contains an ending punctuation like period exclamation point or question mark be able to find it in a subheading**

**This can help improve UX and Content SEO**

**Comment by Pcosta88** [comment]
related https://github.com/Yoast/YoastSEO.js/issues/2220

**Comment by Pcosta88** [comment]
related https://github.com/Yoast/YoastSEO.js/issues/2219

**Comment by Pcosta88** [comment]
related https://github.com/Yoast/YoastSEO.js/issues/2218

**Comment by Pcosta88** [comment]
related https://github.com/Yoast/wordpress-seo/issues/2163

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 496015 when this conversation has been closed.

**Comment by jdevalk** [comment]
Closing.
