### ISSUE TITLE
Meta description template isn't being used

### ISSUE THREAD

**Issue by jcomack** [Yoast/YoastSEO.js#223]
After adding a meta description template in the Titles & Metas, I'd expect this to show up in the snippet editor. Currently, this is not the case and it defaults to the placeholder text.

**Comment by tacoverdo** [comment]
**Example**
![titles___metas_-_yoast_seo_ _clean_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/12512521/1a2c2f96-c119-11e5-822a-1edc3903dc42.png)

![edit_post_ _clean_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/12512528/2b8089a4-c119-11e5-9916-0d077e4708ec.png)
