### ISSUE TITLE
"Please create a page title." while page title exists

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/YoastSEO.js#236]
**Problem description**
Analysis says `Please create a page title.` when a page title exists.

**Steps to reproduce**
1. Create a new post
2. Enter a title

**Example**
![add_new_post_ _clean_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/12512050/2694755c-c116-11e5-9c7d-840d3b72dcec.png)

![add_new_post_ _clean_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/12512075/48d2fa9e-c116-11e5-977f-8823f6cde6ae.png)

**Tested versions**
WordPress 4.4.1
Yoast SEO 3.1-beta-4

**Comment by tacoverdo** [comment]
Also reported in https://github.com/Yoast/wordpress-seo/issues/3752.

**Comment by terw-dan** [comment]
duplicate with https://github.com/Yoast/YoastSEO.js/issues/225
