### ISSUE TITLE
"focus keyword was found undefined times"

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/YoastSEO.js#237]
**Problem description**
Check for occurance of focus keyword says `undefined times`.

**Steps to reproduce**
1. Create a new post
2. Enter a focus keyword
3. Enter any text long enough to trigger the check for the occurance of the focus keyword

**Examples**
![add_new_post_ _clean_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/12512204/30d48c68-c117-11e5-94d5-0065dc82365c.png)

![add_new_post_ _clean_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/12512210/3ce9fa92-c117-11e5-98ae-3f0e908b01ca.png)

**Tested versions**
WordPress 4.4.1
Yoast SEO 3.1-beta-4

**Comment by terw-dan** [comment]
Duplicate with https://github.com/Yoast/YoastSEO.js/issues/227
