### ISSUE TITLE
%%sep%% %%sep%% shows just one separator character in SEO title

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/YoastSEO.js#239]
**Problem description**
Entering `%%sep%%` as page title results in a single separator (e.g. `-`), which is correct. However, entering `%%sep%% %%sep%%` also results in a single separator (e.g. `-`).

Changing the title to `%%sep%% %%sep%% %%sep%%` shows two separators (e.g. `- -`), etc etc.

**Steps to reproduce**
1. Create a new post
2. Enter `%%sep%%` as SEO title
3. See the result
4. Change the SEO title to `%%sep%% %%sep%%`

**Example**
![edit_post_ _clean_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/12512884/13fc7836-c11b-11e5-90ec-61a101cddda4.png)

**Tested versions**
WordPress 4.4.1
Yoast SEO 3.1-beta-4

**Comment by terw-dan** [comment]
This is intended use. Double seperators are stripped to 1 seperator if they are seperated by a whitespace. So %%sep%% %%sep%% is replaced with a single - .
This is the same as in 2.3.5
