### ISSUE TITLE
Change in UX, can we make this more clear?

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/YoastSEO.js#241]
**Problem description**
In Yoast SEO 3.0.7, when I click the title in the snippet editor, I can immediately change it. In Yoast SEO 3.1, I'm "jumping" to an input field. After people had to get used to the in-line editing, changing this UX again might be confusing without clear call-to-actions.

## 3.0.7
**Default state**
![add_new_post_ _wp41_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/12553565/82e34806-c378-11e5-8bf3-f7d29d30591a.png)

**On hover**
![add_new_post_ _wp41_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/12553691/1c42319c-c379-11e5-999f-accaf99e71e2.png)

**On click**
![add_new_post_ _wp41_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/12553718/46f4f258-c379-11e5-9db9-26c75cc074d5.png)

**Entering text**
![add_new_post_ _wp41_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/12553770/82db97fe-c379-11e5-9b54-98b44a2c4bcc.png)

## 3.1
**Default state**
![edit_post_ _clean_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/12553790/983f0996-c379-11e5-9ca7-9406ea5d1e7c.png)

**On hover**
![edit_post_ _clean_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/12553799/ad904184-c379-11e5-9278-03a379a02f35.png)

**On click**
![edit_post_ _clean_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/12554124/4ff80276-c37b-11e5-9ec7-ce004af9b572.png)

**On entering text**
![edit_post_ _clean_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/12554179/8ffa27d2-c37b-11e5-90d5-738ce43285f4.png)

## Possible issues
Both 3.0.7 and 3.1 look pretty much the same in the default and on hover state, entering text states. The one that differs the most and may be less intuitive at first is the 'on click' state, as the snippet preview looks exactly the same as the 'on hover' state.

@omarreiss, can we change this to make the state change more clear?

**Comment by atimmer** [comment]
This should be fixed by the improved snippet editor design.
