### ISSUE TITLE
Converted Danish characters not recognized in slugs

### ISSUE THREAD

**Issue by GSAdev** [Yoast/YoastSEO.js#247]
When a Danish title is converted to a slug in WordPress, WordPress follows the convention that æ, ø and å is converted to ae, oe and aa. As far as I know, Google knows that. But if we have a SEO keyword and a title with one or more of these letters and the corresponding converted value in the slug, Yoast SEO/SEO Premium says that the keyword is not found in the slug/URL. E.g.:

SEO keyword: bedstemors opskrift på æblegrød (meaning: grandma's recipe for stewed apples)
Title: "Bedstemors opskrift på æblegrød"
Slug: "bedstemors-opskrift-paa-aeblegroed"

Usually, I just ignore the warning that "The focus keyword does not appear in the URL for this page. If you decide to rename the URL be sure to check the old URL 301 redirects to the new one!"

Nevertheless, is the WordPress community's understanding wrong, or should the warning be rephrased or perhaps dropped (which might not be an easy task, I know, as one must take language and language conventions into account)?

**Comment by atimmer** [comment]
Great idea!

We want to support this, see: #293. We'll be tracking this feature there.
