### ISSUE TITLE
Remove stopwords check for focus keyword

### ISSUE THREAD

**Issue by jdevalk** [Yoast/YoastSEO.js#250]
This check:

"The focus keyword for this page contains one or more stop words, consider removing them. Found 'of, the'."

Should become a grey bullet without a score. It should have the following text:

"Your focus keyword contains one or more stop words. This may or may not be wise depending on the circumstances. Read <a href="https://yoast.com/handling-stopwords/">this article</a> for more info."

If no stop words are founds within the focus keyword, nothing should be shown.

**Comment by jcomack** [comment]
Made the changes as per your request.

@jdevalk Only question I still have regarding this issue, is where you want the grey bullet to show up in the list of bullets.

**Comment by jdevalk** [comment]
Up top :)
