### ISSUE TITLE
Problem with some characters

### ISSUE THREAD

**Issue by user67x** [Yoast/YoastSEO.js#260]
My target keyword is French: "Création de logotype". Yoast seems to ignore the "é" and believes that the keyword is not present in title, description, etc.

The led is red for :
The focus keyword 'création de logotype' does not appear in the page title.
seo score badA meta description has been specified, but it does not contain the focus keyword.
seo score poorThe images on this page do not have alt tags containing your focus keyword.

Thx for a patch.

The problem has reporter to : https://www.drupal.org/node/2640906#comment-10827124

**Comment by mcariatm** [comment]
i have same problem with romanian diacritical marks.

**Comment by atimmer** [comment]
This has been fixed in the latest version of YoastSEO.js, the drupal module has yet to be updated. I've updated the Drupal ticket with this information.
