### ISSUE TITLE
Text analyses unignored quotes

### ISSUE THREAD

**Issue by moorscode** [Yoast/YoastSEO.js#269]
There are a lot of quotes that are not ignored which resolves in keywords not being found in text.

Double quotes:
http://www.fileformat.info/info/unicode/char/search.htm?q=%E2%80%9C&preview=entity
http://www.fileformat.info/info/unicode/char/search.htm?q=%E2%80%9D&preview=entity

Single quotes:
http://www.fileformat.info/info/unicode/char/search.htm?q=%E2%80%98&preview=entity
http://www.fileformat.info/info/unicode/char/search.htm?q=%E2%80%99&preview=entity

Chinese quotes:
http://www.fileformat.info/info/unicode/char/search.htm?q=%E3%80%8E&preview=entity
http://www.fileformat.info/info/unicode/char/search.htm?q=%E3%80%8F&preview=entity
http://www.fileformat.info/info/unicode/char/search.htm?q=%E3%80%8C&preview=entity
http://www.fileformat.info/info/unicode/char/search.htm?q=%E3%80%8D&preview=entity

Low quotation mark:
http://www.fileformat.info/info/unicode/char/search.htm?q=%E2%80%9A&preview=entity
http://www.fileformat.info/info/unicode/char/search.htm?q=%E2%80%9E&preview=entity

For a summary of quotes used in different languages:
https://en.wikipedia.org/wiki/Quotation_mark#Summary_table_for_all_languages

Overview of codes and different types:
https://en.wikipedia.org/wiki/Quotation_mark#Unicode_code_point_table

**Comment by monbauza** [comment]
Please inform the customer of conversation # 156705 when this conversation has been closed.

**Comment by moorscode** [comment]
This approach is too broad to be practical. Lingo will analyze new languages to see what special characters need to be implemented/added.
