### ISSUE TITLE
Focus keyword highlighting not applied to all occurrences

### ISSUE THREAD

**Issue by moorscode** [Yoast/YoastSEO.js#270]
When the keyword is repeated after itself, every second item is not highlighted.

![screen shot 2016-02-10 at 10 35 20](https://cloud.githubusercontent.com/assets/2005352/12944620/8dfcd62c-cfe8-11e5-8f98-680b7785b930.png)

**Comment by terw-dan** [comment]
duplicate with https://github.com/Yoast/YoastSEO.js/issues/203
