### ISSUE TITLE
Auto-fillled slug is not applied to snippet preview

### ISSUE THREAD

**Issue by moorscode** [Yoast/YoastSEO.js#271]
When the slug has been empty to be auto-filled from title, the generated slug is not applied to the snippet preview.

After doing this, editing and saving the slug does not fix the problem, a change in the text needs to be made to make it appear again.
Removing a character and typing it again is not enough!

How to reproduce:
1. Go to a new or existing post
2. Make sure there is a title and slug
3. Edit the slug and remove the text
4. Apply empty slug

**Comment by atimmer** [comment]
Closed via #3918
