### ISSUE TITLE
Focus keyword "common" special characters inconsistent representation

### ISSUE THREAD

**Issue by moorscode** [Yoast/YoastSEO.js#272]
Entering the following focus keyword special characters result in the inconsistent displaying of the keyword.

![screen shot 2016-02-10 at 14 48 40](https://cloud.githubusercontent.com/assets/2005352/12948914/690017d6-d005-11e5-8816-19bbe3e7943b.png)

```
Raw:    !@#$%^&*()_+{}[];’:”\|<>?,./`~±§-=
Parsed: !@# % &   _     ;':"  <> ,. `~±§-=
```

These are the characters on a default latin language keyboard.
Some of the characters are stripped but many aren’t.

In the feedback the focus keyword is displayed as it is used in analysis, but the input field and tab name have the unparsed version.

Expected:
The most logical situation would be to display the raw input on feedback
"The focus keyword '!@#$%^&*()_+{}[];':"|<>?,./`~±§-=' does not appear in the page title."

Question:
Should more (or all) of these special characters be filtered out?

**Comment by moorscode** [comment]
The most logical situation would be to display the raw input on feedback
"The focus keyword '!@#$%^&*()_+{}[];':"\|<>?,./`~±§-=' does not appear in the page title."

**Comment by Djennez** [comment]
It seems that this issue has been fixed in the meantime. Using the character string from OP I was able to generate an exact replica in the output. Closing this issue as solved.
