### ISSUE TITLE
HTML tags in copy cause snippet visualisation problem

### ISSUE THREAD

**Issue by moorscode** [Yoast/YoastSEO.js#274]
When HTML tags are present in the text displayed in the snippet preview, they are replaced by spaces.
This happens in the title and description texts.

Because of this, the focus keyword is no longer found when a word contains a HTML tag.

The analyses of the text works properly.

![snippet-description-html-tags](https://cloud.githubusercontent.com/assets/2005352/12951133/1d9e704c-d011-11e5-81cf-bb686cd8f1ce.png)

**Comment by jcomack** [comment]
There is no real good fix for this issue. Will look into this again if this issue resurfaces in the future.
