### ISSUE TITLE
RTL hostname and slug are not connected

### ISSUE THREAD

**Issue by moorscode** [Yoast/YoastSEO.js#276]
When a RTL language is active, the slug and hostname are separated.

![screen shot 2016-02-11 at 09 45 46](https://cloud.githubusercontent.com/assets/2005352/12972311/623dd7a4-d0a4-11e5-9780-a23fbc3b572b.png)

Should be fixed in https://github.com/Yoast/wordpress-seo/issues/2693

**Comment by atimmer** [comment]
Fixed by https://github.com/Yoast/wordpress-seo/pull/5478
