### ISSUE TITLE
Analyses does not recognise &amp; as &

### ISSUE THREAD

**Issue by moorscode** [Yoast/YoastSEO.js#278]
When using a focus keyword with an "&" the analysis is broken on the following elements:
- Title
- Slug
- Paragraphs
- Headings

It works on the alt tags in images.

Tested using the focus keyword `pooch & mutt`.
Confirmed this is an issue still present in RC 3.1

**Comment by CarolineGeven** [comment]
This issue is fixed for paragraphs and headings, still occurs for title and slug.

Slightly related to https://github.com/Yoast/YoastSEO.js/issues/856

**Comment by nataliashitova** [comment]
Tested in RC 7.8, only reproduces in slug.
