### ISSUE TITLE
Descriptive keyword analysis

### ISSUE THREAD

**Issue by omarreiss** [Yoast/YoastSEO.js#29]
Currently, our keyword analysis is mainly directive.

I think it could also be really helpful to have more descriptive keyword analysis.

Maybe some piece of content I've written is actually very good or useful as is. It might be quite optimized for different keywords than the one I've thought of.

As a writer, I would then like to gain insight into what my currently written text is good for.

Based on the content I've written, I can imagine it would be interesting to know:
- Top keywords
- Keyword groups (which keywords often appear in the same sentence)
- Top keywords based only on headers, links and first sentences of paragraphs. That might add some indication about the quality of the main message contained inside the text.

We could also tag a post with its top keywords or we could save it as a postmeta. The data could be used for keyword suggestion or could be sent to GA as a custom dimension.

**Comment by omarreiss** [comment]
Could also be great for doing related posts or link suggestions. If every post would have top keywords, we could even create an interface for doing global link and keyword suggestions. Only challenge would be getting all content indexed. We might need some PHP for that after all.

**Comment by omarreiss** [comment]
Could be interesting to know per top keyword what its respective SEO score would be

**Comment by omarreiss** [comment]
We've decided to build the analysis functions needed for this into YoastSEO.js. To start with, we need to be able to generate the following data sets:

- Most used relevant words
  - This is a relatively simple operation. We'd need a list of words per language to exclude from the text before tokenizing, counting and ordering the relevant words that remain. We'll strip out all words that have only one occurrence and maximize the word list to 100 words.
- Most used relevant wordcombinations of X words.
 - For this we'll need to traverse the sentences to collect all word combinations.
 - We will count occurrences of word combinations, sort descending, strip out all the ones that have only one occurrence.
 - Then we will strip out all word combinations that do not contain at least one word from the top 100 words and maximize the list to 100 word combinations.

Collecting wordPairs would be on a per sentence basis and would look something like this:
```JS
var sentence = "This is a sentence"
var wordCombinationSize = 2

getWordCombinationsFromSentence( sentence, wordCombinationSize ); 
//=> [ "This is", "is a", "a sentence" ]
```

Now comes the tricky part. Let's say we collect all the words, all 2-word combinations and all 3-word combinations, then we might want to have a way to mix those datasets and order the unified dataset by relevance. A 2-word combination should have more weight than a single word in terms of relevance, since it likely is a more unique expression. We should experiment with this.

Let's start out with the following weights and finetune once we've got something working:

| Set  | Weight  |
|---|---|
| Single words  | 1  |
| 2-word combinations  | 2  |
| 3-word combinations  | 2,5  |

To put this into words:
- _A combination "WordPress SEO" occuring 4 times will be considered more relevant to the text than a word "SEO" occuring up to 8 times._
- _A combination "Yoast Local SEO" occuring 4 times will be considered more relevant to the text than a word "SEO" occuring up to 10 times._
- _A combination "Yoast Local SEO" occuring 5 times will be considered more relevant to the text than a word "WordPress SEO" occuring up to 6 times._

The aim of all this is to create a sensible list of words and word-combinations ordered by relevance, based on which we could do focus keyword suggestions, tag suggestions, internal linking suggestions and more. 

@IreneStr will come up with a list of exclusion words (signal words, stopwords etc.) for English which can be used to base the code on. Once the code is in place, she will also run some tests to finetune the algorithm and the weights.

**Comment by omarreiss** [comment]
So, we've found out that the weight given to a word combination is not only determined by the size of the combination, but also by the amount of relevant words in the combination. Also, it seems the size of the combination (amount of words) is more important than we previously thought. We've come to the following formula:

`relevance` = (`1` + `combination size bonus` * `Relevant words percentage`) * `occurences`

Where:

`relevance` is the calculated relevance.
`1` is the basemultiplier. Every word is at least as relevant as 1 time its occurences.
`combination size bonus` is the maximum bonus added to the multiplier for the size of the wordcombination.
`Relevant words percentage` is the percentage of words in the combination that are part of the top 100 single relevant words in a text (see definition in comment above).

Based on our current algorithm, we'd get something like this:

| Word combination | Category  | Occurences | Combi Size Bonus  | Relevant words perc | Relevance |
|---|---|---|---|---|---|
| "foo" | Single word  | 1 | 0  | 100% | 1 |
| "the bar" | 2-word combination  | 1 | 2  | 50% | 2 |
| "foo bar" | 2-word combination  | 1 | 2  | 100% | 3 |
| "of the bar" | 3-word combination  | 1 | 4  | 33% | 2,32 |
| "the foo bar" | 3-word combination  | 1 | 4  | 67% | 3,67 |
| "foo bar baz" | 3-word combination  | 1 | 4  | 100% | 5 |

**Comment by IreneStr** [comment]
The weigths have been changed to:

| Set  | Weight  |
|---|---|
| Single words  | 3  |
| 2-word combinations  | 6  |
| 3-word combinations  | 9  |

**Comment by IreneStr** [comment]
Other decisions/findings:
- All one-syllable single words are removed from the list (after they are included in the relevance calculation for multiword combinations containing these single words). The most frequently used words tend to be the shortest, making one-syllable single words bad focus keywords.
- If two keyword combinations have the same relevance, the longest (most words) will rank the highest. 
- A title/heading bonus does not seem to improve the suggestions.
- An entity bonus could be included in a later stage.
