### ISSUE TITLE
Add subheading presence assessment

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#335]
We recommend the use of subheadings in every text. We should count the number of subheadings in the text, and come up with a score. To score the presence of subheadings, the following criteria should be met: 

Recommended minimum number of subheadings = 1

**Calculate score:**

No subheadings present: `score = 3`
At least 1 subheading present: `score = 9`

**Add feedback:**

`score == 3`: “The text does not contain any subheadings. Add at least one subheading.”
`score == 9`: “The text contains %1$d subheading, which is great.” || “The text contains %1$d subheadings, which is great.”

**Comment by IreneStr** [comment]
Update current textSubheadingsAssessment

**Comment by CarolineGeven** [comment]
Acceptance 👍
