### ISSUE TITLE
Focus Keyword Containing An Internal Number Triggers Stop Word Warning

### ISSUE THREAD

**Issue by AskKim** [Yoast/YoastSEO.js#353]
When keyword 'spa8i' is used as a focus keyword, the 8 makes the stop word checker split the i by itself. 

Angelia replicated this one for me on her testing site. 

<img width="1053" alt="edit_post_--_berita_semasa_--_wordpress_and_untitled" src="https://cloud.githubusercontent.com/assets/5900222/13902879/1973578c-ee2d-11e5-8818-e95f75312a25.png">

This seems to be a bug although perhaps there's an intentional reason for it. 

Yoast SEO/Premium 3.1.2
WP 4.4.2

**Comment by AskKim** [comment]
Please inform the customer of conversation # 107925 when this conversation has been closed.

**Comment by atimmer** [comment]
I can still reproduce this.

**Comment by manuelaugustin** [comment]
This assessment has been deprecated in Yoast SEO 9.0, see https://github.com/Yoast/YoastSEO.js/pull/1836
