### ISSUE TITLE
Refactor how grey circles are created

### ISSUE THREAD

**Issue by jcomack** [Yoast/YoastSEO.js#359]
Currently whenever an assessment shouldn't return a score of some sorts, a string is passed instead of a  number.
This string is then evaluated in the `AssessmentResult` class. As this leads to two value types on a single parameter, there could be said that this is an indication of code smell.

Advice: Refactor the way grey circles need to be created and introduce a separate method and specialistic value for this grey indicators.

**Comment by atimmer** [comment]
This has been fixed by #385
