### ISSUE TITLE
Create assessment for keyword doubles

### ISSUE THREAD

**Issue by terw-dan** [Yoast/YoastSEO.js#370]
Create an assessment for keyword doubles

This assessment doesn't really belong  in the YoastSEO.js since it doesn't assess the paper, but uses a wordpress specific array with keywords to see if they are use before.
It might be better to include this in wordpress-seo as an extra wordpress specific assessment.

**Comment by terw-dan** [comment]
The current specs for the keyword doubles. Since usedKeywords is used with wordpress, it would be better to move it as an external assessment. 
var keywordDoubles = require( "../../js/analyses/checkForKeywordDoubles.js" );
var usedKeywords = { "keyword": [1], "test": [2,3,4] };
describe( "checks for keyword doubles", function(){
	it("returns array with keyword", function(){
		expect( keywordDoubles( "keyword", usedKeywords ).count).toBe(1);
		expect( keywordDoubles( "keyword", usedKeywords ).id).toBe(1);
		expect( keywordDoubles( "test", usedKeywords ).count).toBe(3);
		expect( keywordDoubles( "test", usedKeywords ).id).toBe(0);
		expect( keywordDoubles( "not-used", usedKeywords ).count ).toBe( 0 )
	});
});

**Comment by atimmer** [comment]
We can solve this by bundling a plugin that can be used from any platform to create a keywordDoubles assessment.
