### ISSUE TITLE
Way to analyze custom metabox?

### ISSUE THREAD

**Issue by rahilwazir** [Yoast/YoastSEO.js#386]
I have a metabox with `Subtitle` and I want the `Focus Keyword` to match either the post title or post subtitle to suppress this warning:

> The focus keyword 'any-title' does not appear in the page title.

I couldn't find any API in the docs, care to provide any example to pass custom metabox value through Page Analyzer?

**Comment by rahilwazir** [comment]
@atimmer ping

**Comment by rahilwazir** [comment]
I'm using the following plugin [snippet] (https://gist.github.com/rahilwazir/6026cbe1bca7cb6c75553cc198a4b20c)

I debugged into `wp-seo-post-scraper-320.js` file and realize that it adds appended data to `rawData.title` property, but to suppress the page analyzer test it needs to be also appended to `rawData.pageTitle` property as well.

Is it even possible?

**Comment by atimmer** [comment]
You could make this possible is by using the `title` modification. Before analyzing the title it is put through `applyModifications( 'title' )`. So if you add a modification to the title you can add your own data to it.

In WordPress, the following should work if you have already registered a plugin:
```js
YoastSEO.app.registerModification( 'title', function( oldTitle ) {
    var newTitle = oldTitle + 'extra title';
    
    return newTitle;
}, 'yourPluginName' );
```

**Comment by rahilwazir** [comment]
@atimmer Thanks for your reply, but I think you didn't understand what I'm trying to say. Have you looked at my [snippet] (https://gist.github.com/rahilwazir/6026cbe1bca7cb6c75553cc198a4b20c)?

In the following I have done exactly what you are talking but it just doesn't work.

What I was trying to say in my above point was that, my custom metabox data gets appended to the title and modification also applies (inside JS, when I set breakpoints) but the analyzer checks against the `pageTitle` property and `pageTitle` has no data appended to it, instead `.title` has the appended data.

So the warning

> The focus keyword 'custom value' does not appear in the page title.

does not suppress.

If I hack the `wp-seo-post-scraper-320.js` file and replace `title` over `pageTitle` it works and the error also suppressed.

Please comment.

**Comment by atimmer** [comment]
I see, I've put this in scheduled.
