### ISSUE TITLE
Add automatic meta description generation

### ISSUE THREAD

**Issue by atimmer** [Yoast/YoastSEO.js#387]
When you don't specify a description to Google in your meta fields Google will generate a description of your site based on there it has found the keyword in your page.

The PHP version and early versions of YoastSEO.js had a system to simulate this. We should bring this back. There is #265, but that implementation doesn't work. It's better to rethink and rebuild.

**Comment by IreneStr** [comment]
Closed because we're dropping the generated metadescription altogether. See https://github.com/Yoast/wordpress-seo/issues/9930
