### ISSUE TITLE
Cannot set property 'textContent' of null

### ISSUE THREAD

**Issue by rahilwazir** [Yoast/YoastSEO.js#388]
### What did you expect to happen?
I'm trying to register a plugin, I also tried the following [example](https://github.com/Yoast/YoastSEO.js/blob/8720168cad79085bd6664a8648e51c048293def4/examples/standalone/example-plugin-test.js) snippet

### What happened instead?
But I got an error saying:

```
Uncaught TypeError: Cannot set property 'textContent' of null
  YoastSEO.App.updateLoadingDialog @ yoast-seo-310.min.js?ver=3.1.2:formatted:869
  YoastSEO.Pluggable._registerPlugin @ yoast-seo-310.min.js?ver=3.1.2:formatted:1629
  YoastSEO.App.registerPlugin @ yoast-seo-310.min.js?ver=3.1.2:formatted:1605
  addPlugin @ my-script.js?ver=0.1.32:71
  (anonymous function) @ my-script.js?ver=0.1.32:66
```

### How can we reproduce this behavior?

- Use latest version of this plugin
- Create JS file and copy the [example](https://github.com/Yoast/YoastSEO.js/blob/8720168cad79085bd6664a8648e51c048293def4/examples/standalone/example-plugin-test.js) snippet
- Enqueue script to admin post edit screen, with `array('jquery', 'yoast-seo')` dependencies and last parameter `$in_footer => true`
- Check your developer console.

### Technical info
* Platform: WordPress
* Platform version: 4.4.2
* Yoast SEO version: 3.1

**Comment by jcomack** [comment]
Tried to reproduce this, but I don't get see any errors arise.
Quite possibly your custom plugin might work better with version 3.2. I attached a release candidate for you. Could you please test it and report back?

[wordpress-seo-RC.zip](https://github.com/Yoast/YoastSEO.js/files/219166/wordpress-seo-RC.zip)

**Comment by rahilwazir** [comment]
@jcomack Sorry but the issue persists. Even updated to the latest `v3.2.3`

Please have a look at my [plugin script] (https://gist.github.com/rahilwazir/6026cbe1bca7cb6c75553cc198a4b20c).

I had setup breakpoints to `wp-seo-post-scraper-320.js#8676` file on the method `updateLoadingDialog` and it hit the breakpoint 4 times, with the local variable `dialog` set to `#YoastSEO-plugin-loading` node.

But after page fully loads the method runs again and this time `#YoastSEO-plugin-loading` node couldn't be found and returns `null`.

**Comment by rahilwazir** [comment]
I have fixed the above error, by updating my [snippet](https://gist.github.com/rahilwazir/6026cbe1bca7cb6c75553cc198a4b20c).

I have replaced this

```
addEventListener('load', function() {
    // Wait for YoastSEO to be loaded
    setTimeout(function() {
        module.load();
    }, 0);
});
```
with
```
jQuery(window).on('YoastSEO:ready', module.load);
```

Now my plugin registered successfully, without any errors. I think it was causing because of the `load` handler or `setTimeout` function, in-between.

Please let me know if this issue needs to be close.

**Comment by omarreiss** [comment]
We should improve the docs, as per #117 but this issue can indeed be closed.
