### ISSUE TITLE
Refactor Assessment score calculations

### ISSUE THREAD

**Issue by jcomack** [Yoast/YoastSEO.js#401]
Currently there's a distinct difference between how the overall score and the score per Assessment, are being calculated.

The overall score is using a 0 - 100 scale whereas the Assessment scale is based on a 0 - 10 scale.
Seeing as the overall score is the value that gets saved in the database, it might be a good idea to alter the Assessment score values to use the same scale. 

This will both lead to less code (thus less maintenance) and will allow for a more refined scoring within the various Assessments.

**Comment by Djennez** [comment]
Assessments have been drastically revamped in the meantime and scoring is done with a different scale. Closing this thread.

**Comment by Djennez** [comment]
@igorschoester pointed out to me that this has, in fact, not been changed in the underlying structure. However, a new issue was created recently with a suggestion on how to improve this. So I will keep this issue closed in favor of https://github.com/Yoast/YoastSEO.js/issues/2185
