### ISSUE TITLE
Title length seo scoring

### ISSUE THREAD

**Issue by diedexx** [Yoast/YoastSEO.js#410]
Google only has room for 512px for the title of a search result. At this time we check for an amount of characters used in the SEO title (I believe the bar underneath the input field turns red after 55 or 66 characters, but i'm not sure). However, not all characters are equal. I'd suggest checking for the width instead of the character count.

### What did you expect to happen?
I expect the seo score and the bar underneath the input field to be red once the title does not fit in the 512 pixels google gives us.

### What happened instead?
I have altered some of the CSS in order to help me illustrate this issue. (I removed the 512px width and changed `display:block` to `inline` on  `.snippet_container .title`.) Even though the seo score tells me that the title is fine, the title does not fit in the 512 pixels given by Google.
![nieuw_bericht_toevoegen_ _local_wordpress_dev_ _wordpress](https://cloud.githubusercontent.com/assets/5352634/14229065/6650b7a0-f929-11e5-9843-c972b0c6c5a3.png)

### Possible solution
Using `display:inline` on the title text in the snippet preview allows us to find out the width required to print the title.
![nieuw_bericht_toevoegen_ _local_wordpress_dev_ _wordpress](https://cloud.githubusercontent.com/assets/5352634/14229084/b2212624-f929-11e5-90a0-9267247d9391.png)
(This is the width required to print the title as shown in the image above. way more than 512.)
As long as we use the same font/size as Google does, I believe this will be way more accurate than our current measurements.
However, using `display:inline` causes the title to be able to exceed its boundaries. I have not yet tried to find a way to prevent this.

### Technical info
* Platform: WordPress
* Platform version: 4.4.2
* Yoast SEO version: 3.1.1 trunk

**Comment by atimmer** [comment]
This has been fixed in 1.4. Relevant PR: https://github.com/Yoast/YoastSEO.js/pull/753.
