### ISSUE TITLE
Missing page title focus keyword check

### ISSUE THREAD

**Issue by CarolineGeven** [Yoast/YoastSEO.js#423]
### What did you expect to happen?
I expect the title is checked to see if the focus keyword is in it.

### What happened instead?
There is no such message. In 3.1 there is such a message. See screenshot.

<img width="1307" alt="schermafbeelding_2016-04-07_om_11_41_04" src="https://cloud.githubusercontent.com/assets/8614579/14347091/8079f436-fcb5-11e5-8944-11dd361e6a21.png">

### How can we reproduce this behavior?
Set focus keyword and place the focus keyword in the title as well.

### Technical info
* Platform: WordPress
* Platform version: 4.4.2 
* Yoast SEO version: Yoast SEO 3.2 beta 2

**Comment by terw-dan** [comment]
Unable to reproduce
