### ISSUE TITLE
Text analysis strings not translated anymore

### ISSUE THREAD

**Issue by CarolineGeven** [Yoast/YoastSEO.js#425]
### What did you expect to happen?
In Yoast SEO 3.1 most (if not all) text analysis strings were at least translated to Dutch. I would expect this would still be the case in 3.2, as it seems like the strings aren't changed.

### What happened instead?
A few strings are not properly translated anymore. See print screen.
<img width="1307" alt="schermafbeelding_2016-04-07_om_11_41_04" src="https://cloud.githubusercontent.com/assets/8614579/14348080/8baeb4ae-fcba-11e5-9593-d2f8fc33f9b2.png">

### How can we reproduce this behavior?
Set language to (for example) Dutch, create a post with content and check the text analysis.

### Technical info
* Platform: WordPress
* Platform version: 4.4.2
* Yoast SEO version: Yoast SEO Beta 3.2-2

**Comment by terw-dan** [comment]
This is due to updated textstrings (ie `2$s%` was replaced by `1$s%`), or updated strings that now have a single or plural form. This will be fixed with new translations.
