### ISSUE TITLE
Create content assessor

### ISSUE THREAD

**Issue by terw-dan** [Yoast/YoastSEO.js#447]
Currently we have an assessor for SEO for running SEO assessments. We need one for content too.

**Comment by CarolineGeven** [comment]
### Acceptance
The following errors are thrown in the console:
> GET YoastSEO.js/dist/yoast-seo.min.css net::ERR_FILE_NOT_FOUND

> GET YoastSEO.js/examples/browserified/example-browserified.js net::ERR_FILE_NOT_FOUND

When running `grunt build:js` the following error is thrown:
> example-browserified.js:2312 Uncaught MissingArgumentError: `targets.output` is a required App argument, `targets.output` is not a string.
