### ISSUE TITLE
Adding custom content to content analysis tool

### ISSUE THREAD

**Issue by aml-group** [Yoast/YoastSEO.js#458]
### What did you expect to happen?

I expected as a test for my string to be added to to the word count of the post.

### What happened instead?

An error stating: Cannot set property 'textContent' of null was shown from the Yoast SEO script: yoast-seo307.min.js?ver=3.0.7:formatted:726. This was a result of my script calling the pluginReady method prior to registering the modification.

I think the reason for this error is because the showLoadingDialog method is not executed to create the div prior to line 780 being executed.

### How can we reproduce this behavior?

I found the Yoast SEO.js example did not work. I looked around online and found an implementation here: https://return-true.com/adding-content-to-yoast-seo-analysis-using-yoastseojs/

My implementation closely follows this script.

### Technical info
* Platform: WordPress
* Platform version: 4.5
* Yoast SEO version: 3.0.7

**Comment by atimmer** [comment]
Duplicates #388
