### ISSUE TITLE
Add translator fix with % to new assessments

### ISSUE THREAD

**Issue by terw-dan** [Yoast/YoastSEO.js#459]
If a string contains a single % it breaks in Jed (returns huh?). We've escaped this with a second %, but this could go wrong in translations (where a translator accidentally omits one of the %'s). 

We should add % to the replacementvariables, so this cannot break anymore for the new assessments that don't have this fix yet.
Also update the translator comments if necessary

**Comment by jcomack** [comment]
As far as I can see, there are no remaining strings with the `%%` present.

Is it safe to close this issue now, @terw-dan? :)

**Comment by atimmer** [comment]
Is already fixed.
