### ISSUE TITLE
Make helper of formula in assessments for paragraph length and heading distribution

### ISSUE THREAD

**Issue by andizer** [Yoast/YoastSEO.js#468]
I think we should make a helper of the formula in the paragraph length and the heading distribution. See pulls: #452, #454 and #464

The calculation of the scores in both are almost the same, but using other input values: 
In #452 it is:
`var score = 9 - Math.max( Math.min( ( 0.06 ) * ( paragraphsLength[ 0 ] - 117 ), 6 ), 0 );`

in #464 it look likes:
`var score = 9 - Math.max( Math.min( ( 0.06 ) * ( subheadingTextsLength[ 0 ] - 267 ), 6 ), 0 );`

in pull #454
`var score = 9 - Math.max( Math.min( ( 6 / 10 ) * ( percentage - 6.7 ), 6 ), 0 );`

Probably it can be replaced by a helper like this:
```
function calculateScoreOrGiveItAnotherName( text, threshold  ) {
    var calculatedScore = ( 0.06 ) * ( text - treshhold );
    return 9 - Math.max( Math.min( calculateScore, 6 ), 0 );
```

It is possible there are more location of the same formula. It would be nice to look in the codebase when this optimization will be applied.

**Comment by atimmer** [comment]
This is no longer relevant because we aren't using these formulas anymore.
