### ISSUE TITLE
Separate keyword and content score

### ISSUE THREAD

**Issue by omarreiss** [Yoast/YoastSEO.js#484]
Requirements:

- Traffic light needs to be replaced by a new widget with two traffic lights labeled "content" and "keyword".
- App needs to have two assessors, one for content, one for keyword and needs to be able to trigger updates for the corresponding scores.

**Comment by omarreiss** [comment]
Please consult Marieke to figure out which assessments belong in which assessor.

**Comment by atimmer** [comment]
I discussed with Marieke and change only one thing.
