### ISSUE TITLE
Tables used for non-tabular data

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/YoastSEO.js#49]
![developer_tools_-_https___yoast_com_research_real-time-content-analysis___and_yoast_seo_content_analysis](https://cloud.githubusercontent.com/assets/5147598/8479172/30eec588-20d6-11e5-9339-77587a19dd78.png)

We shouldn't use tables for non-tabular data. As discussed with @jdevalk earlier today, using a `list` is semantically probably the best option.

**Comment by terw-dan** [comment]
The analyzer uses ul - li now in stead of tables.
