### ISSUE TITLE
Conflict With WD Oswad Market theme

### ISSUE THREAD

**Issue by amboutwe** [Yoast/YoastSEO.js#494]
### What did you expect to happen?

Run analysis
### What happened instead?

Warning: Unresponsive script
![ioehhlekmkkkkaef](https://cloud.githubusercontent.com/assets/8060612/15166683/894fe2d0-16de-11e6-9347-ae4a54f2b0b2.png)
### How can we reproduce this behavior?

Use WD Oswald Market Theme, Yoast SEO Premium and WooCommerce.
Warning occurs only when editing the shop page.
### Technical info

WordPress 4.5.2
Yoast SEO Premium 3.2.5
### Other Details

WooCommerce 2.5.5
WD Oswad Market theme 1.2.2

Chrome Console
![selection_149](https://cloud.githubusercontent.com/assets/8060612/15166603/aeaddbc8-16dd-11e6-85c6-7a06af4e928f.png)

FireFox Console
![selection_148](https://cloud.githubusercontent.com/assets/8060612/15166606/b5a254c2-16dd-11e6-86d8-95d38507b8b7.png)

Note: Theme developer and WooCommerce have been contacted by the user.

**Comment by Djennez** [comment]
This issue is about 3 years old and not reproducible on our end without the relevant theme. I will close this thread for now, but if this issue still persists on the latest versions of all involved components, please let me know.
