### ISSUE TITLE
Fatal error when updateLoadingDialog element cannot be found

### ISSUE THREAD

**Issue by lucprincen** [Yoast/YoastSEO.js#552]
### What did you expect to happen?

I expected to see a fallback where the rest of my javascript just kept running
### What happened instead?

YoastSEO produced this error:

```
Uncaught TypeError: Cannot set property 'textContent' of null 
u.updateLoadingDialog @ wp-seo-post-scraper-320.min.js?ver=3.2.3:6 
j._registerPlugin @ wp-seo-post-scraper-320.min.js?ver=3.2.3:7 
u.registerPlugin @ wp-seo-post-scraper-320.min.js?ver=3.2.3:6 
initYoastSupport @ Builder.js?ver=4.5:308 
init @ Builder.js?ver=4.5:30 
```

it seems to come from there not being an element with the ID "YoastSEO-plugin-loading" and comes from this function:
`
App.prototype.updateLoadingDialog = function( plugins ) {
    var dialog = document.getElementById( "YoastSEO-plugin-loading" );
    dialog.textContent = "";
`

If I manually add a div with id "YoastSEO-plugin-loading", it works fine.
### How can we reproduce this behavior?

I have no idea how this error popped up. Some of my html output might not be getting closed properly, but a simple check if the element exists should do the trick in stopping JS propagation completely...
### Technical info
- Platform: WordPress
- Platform version: WP 4.5.2
- Yoast SEO version: 3.2.5

**Comment by Djennez** [comment]
This issue was addressed in commit https://github.com/Yoast/YoastSEO.js/commit/7331f297e673068d916df9fc663bc35e9909dd7e and should therefore be fixed at the moment. I will close this issue.
