### ISSUE TITLE
Incorrect feedback string for sentence length variation in very specific cases

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#560]
When the unrounded sentence length variation is between 2.995 and 2.99999..., it is rounded to 3.00. This will result in the incorrect feedback string `The sentence length variation score is 3.00, which is less than the recommended minimum of 3.00. Try to alternate more between long and short sentences.`

We cannot change this string to `The sentence length variation score is 3.00, which is less than or equal to the recommended minimum of 3.00. Try to alternate more between long and short sentences.`, because the other feedback string is `The sentence length variation score is [score], which is more than or equal to the recommended minimum of 3.00. Try to alternate more between long and short sentences.` (because that would imply a score of 3.00 is both good and bad).

**Comment by atimmer** [comment]
Isn't this fixed by #569 ?

**Comment by Djennez** [comment]
This check has been removed from the plugin, therefore this issue is no longer relevant and will be closed.
