### ISSUE TITLE
Fix documentation regarding scores.

### ISSUE THREAD

**Issue by terw-dan** [Yoast/YoastSEO.js#592]
In app.js the scores aren't documented correctly. 

line 612
``\* Negative scores result in a red circle
- Scores 1, 2, 3, 4 and 5 result in a orange circle
- Scores 6 and 7 result in a yellow circle
- Scores 8, 9 and 10 result in a red circle
  *``

line 628
`` \* Scores 0, 1, 2, 3 and 4 result in a red circle
- Scores 6 and 7 result in a yellow circle
- Scores 8, 9 and 10 result in a green circle``

The should be updated, 8,9 and 10 result in a green circle and 5 is orange (is ommitted in the second comment. 
Please check if the other documentation is still correct.

**Comment by Djennez** [comment]
Lies have been changed in the meantime. 

There are 2 functions with these comments, one function is depricated but the comments are correct:
https://github.com/Yoast/YoastSEO.js/blob/9e578cf2581a6f29439c29f8db99dcbf1f941bf0/src/app.js#L962-L980

The other function is still in use but does miss:
* The 5 on the scoring scale
* The color orange of the scoring scale:

https://github.com/Yoast/YoastSEO.js/blob/9e578cf2581a6f29439c29f8db99dcbf1f941bf0/src/app.js#L897-L916
