### ISSUE TITLE
Sentence detection should capture multiple delimiters

### ISSUE THREAD

**Issue by terw-dan** [Yoast/YoastSEO.js#612]
If you use multiple sentence delimiters they aren't captured with a sentence. 

If you have a sentence like:
`This is very nice!!!!!!` It will capture `This is very nice!` as the found sentence, however, I would expect it to be `This is very nice!!!!!!`. The current capturing isn't really wrong, but it would be nicer if all delimiters are marked when we use marks with these sentences.

**Comment by Djennez** [comment]
This seems to be implemented, the following text has the exclamation delimiters included in the marking correctly:

```
Wow, I really need to create a extremely boring, lengthy and long sentence to traverse the maximum of twenty words threshold!!!! This sentence is just to check the marking location.
```

Closing this thread.
