### ISSUE TITLE
Content check green on empty post

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/YoastSEO.js#613]
![add_new_post_ _clean_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/15854156/9ef1275e-2ca8-11e6-89de-ed1a02960631.png)

Without adding any content, the content check shows green. This seems incorrect because there's no content.

### Technical info
* Platform: WordPress
* Platform version: 4.5.2
* Yoast SEO version: 3.3-beta3

**Comment by rensw90** [comment]
This only seems to be the problem when the post is empty and the metadata (in the snippet editor) is not empty. The mete data gets a green score and the content score turns green.

**Comment by rensw90** [comment]
After further research I found some other things:
1. The content score is empty and the keyword score is `Na`, this is inconsistent:
![edit_post_ _local_wordpress_dev_ _wordpress](https://cloud.githubusercontent.com/assets/7293908/15857724/1d7445a2-2cbd-11e6-937f-036f25e4c8e7.jpg)

2. When the post is empty and the focus is on the content tab, the keyword tab seo score is red:
![edit_post_ _local_wordpress_dev_ _wordpress](https://cloud.githubusercontent.com/assets/7293908/15857755/554bf416-2cbd-11e6-9b00-3d05bef3de42.jpg)
When the focus is changed to the keyword tab, the seo score turns grey.
![edit_post_ _local_wordpress_dev_ _wordpress](https://cloud.githubusercontent.com/assets/7293908/15857797/7b7d81f4-2cbd-11e6-849a-3635db8509bf.jpg)

3. When no focus keyword is present the content analysis is already executed:
![edit_post_ _local_wordpress_dev_ _wordpress](https://cloud.githubusercontent.com/assets/7293908/15857815/996a069c-2cbd-11e6-918f-3badd6a8a725.jpg)

**Comment by rensw90** [comment]
At last, this most definitely is a wordpress-seo plugin problem, not a YoastSEO.js problem

**Comment by rensw90** [comment]
Empty content score part fixed with: #648

**Comment by rensw90** [comment]
Created this branch: fix-score-keywordtab-on-empty-post. Empty score is fixed, but there are still some other issues present. The keyword tab seo doesn't update when switching to the content tab

**Comment by rensw90** [comment]
Found related a bug while testing premium-beta-5, seo score displayed by the trafficlight in the metabox, adminbar and publish box, do not update when entering a focus keyword. The score in the keyword tab does.
