### ISSUE TITLE
Disable checks for short content

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/YoastSEO.js#618]
# Problem description

When a text is (super) short, some of the checks do not seem to make sense. 
### Problem description

Checking sentence length variation when there's only one sentence doesn't make sense.
![add_new_post_ _clean_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/15855875/5cf3c384-2cb2-11e6-9334-289ec47a11fe.png)
### Steps to reproduce
- Create a new post.
- Add exactly one sentence to the content.
- The check will show in red as shown above.
### Possible solution

Determine a minimal required number of sentences/words before this check is shown.
### Problem description

If a text contains only one word, it doesn't seem to make sense to require 20% sentences with transition words. 
### Example

![add_new_post_ _clean_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/15856004/58538d18-2cb3-11e6-9b26-82bff9a0507c.png)
### Possible solution

Determine a minimal required number of sentences/words before this check is shown.
### Technical info
- Platform: WordPress
- Platform version: 4.5.2
- Yoast SEO version: 3.3-beta3

**Comment by Djennez** [comment]
The relevant lines have either been removed, fixed or changed, which makes this issue obsolete in my view. Closing it for now.
