### ISSUE TITLE
Incorrect marking of repeated sentence beginnings

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#619]
### What did you expect to happen?
The marker to mark all sentences starting with the same word (in case of 3 consecutive sentences or more).

### What happened instead?
The marker only marked the first and second sentence with repeated sentence beginnings:
![schermafbeelding 2016-06-07 om 13 22 30](https://cloud.githubusercontent.com/assets/17744553/15856025/79dc0ef6-2cb3-11e6-9479-da38f354a150.png)

### How can we reproduce this behavior?
Start 3 consecutive sentences with the same word (not the/a/those/that/that/these/one/.../ten), with a `<p>` and `</p>` between the second and third sentence. 

### Technical info
* Platform: WordPress 
* Platform version: 4.5.2
* Yoast SEO version: trunk

**Comment by tacoverdo** [comment]
Using following text, highlighting consecutive sentences starting with the same word doesn't work at all. 

Text:
```
The Content Analysis Tool in the Yoast SEO plugin measures many aspects of the text you’re writing. These checks run real-time, so you’ll receive feedback while writing! The content analysis helps you to make your text SEO-friendly. In this post, I’ll first describe the most important features of the Content Analysis Tool. After that, I’ll explain how to use and interpret these features.

Most important features

1.  The plugin allows you to formulate a meta description. This description has to be a short text describing the main topic of the page. If the meta description contains the search term people use, the exact text will be shown by Google below your URL in the search results.

2.  The plugin analyzes the text you write. It calculates the Flesch reading-ease score, which indicates the readability of your article. The Flesch reading-ease score takes into account sentence length, for example. In the future, we’ll add more checks on readability. This will allow you to check the SEO and readability of your text simultaneously.

3. The plugin does numerous content checks on your page. It checks whether you use your focus keyword in:

the title of the page;
a heading;
the URL;
the content of the article;
the meta description;
the alt tag of the images.
The plugin also checks the presence of links and images in the article. It calculates the number of words and the density of usage of the focus keyword in the article. Moreover, the plugin checks whether you’re using the same focus keyword on other pages of your website. This should prevent you from competing with yourself.

If you write a relatively SEO-friendly text (based on the aspects mentioned above) the plugin will indicate this with a green bullet. Writing pages that are rewarded with green bullets will help you improve the ranking of those pages.
```
![add_new_post_ _clean_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/15857635/ab146046-2cbc-11e6-9b61-d973bd91a745.png)
_Example text_

![add_new_post_ _clean_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/15857706/024cb5b6-2cbd-11e6-8a20-8c57d6c5a521.png)
_Result_

**Comment by tacoverdo** [comment]
Another example of the highlighter for consecutive sentences causing weird results:

![add_new_post_ _clean_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/15889662/52d4c1b8-2d6c-11e6-8781-bc106a92d9ee.png)
