### ISSUE TITLE
Incorrect sentence detection in case of semicolons

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#620]
### What did you expect to happen?
Semicolons should be used as sentence terminators. 

### What happened instead?
The content assessor views/marks the three sentences separated by semicolons as one sentence.
In the following example, the sentence starting with 'Examples are' should end after 'preceding vowel;':
![schermafbeelding 2016-06-07 om 13 52 30](https://cloud.githubusercontent.com/assets/17744553/15856645/1b0ccfa6-2cb7-11e6-8347-34192d6bdec0.png)

### How can we reproduce this behavior?
Write a sentence containing 20+ words, ending with a period, with a semicolon somewhere in the middle. Hit the mark button for too long sentences. 

### Technical info
* Platform: WordPress
* Platform version: 4.5.2
* Yoast SEO version: trunk

**Comment by atimmer** [comment]
This is caused by the check for a capital letter after a sentence delimiter. We shouldn't check this for `;`, `:`, `?` and `!`.
