### ISSUE TITLE
Incorrect marking of complex words

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#626]
### What did you expect to happen?
All words containing over 3 syllables to be marked completely.

### What happened instead?
Some complex words are not marked completely. The problem seems to originate from the order in which the marks are generated: all instances of 'diacritic' are marked first, whereupon 'diacritical' cannot be identified anymore in `<yoastmark class='yoast-text-mark'>diacritic</yoastmark>al`.
![schermafbeelding 2016-06-07 om 14 44 57](https://cloud.githubusercontent.com/assets/17744553/15858003/a6e278ee-2cbe-11e6-9aac-ef0874877f84.png)

### How can we reproduce this behavior?
Type a four-syllable word and more-than-four-syllable containing that four-syllable word, for example: "familiar familiarity". Then hit the mark complex word button.

### Technical info
* Platform: WordPress
* Platform version: 4.5.2
* Yoast SEO version: trunk

**Comment by IreneStr** [comment]
Additional words: calculates, relatively, indicate

**Comment by jcomack** [comment]
Possibly related to: https://github.com/Yoast/wordpress-seo/issues/4799

**Comment by atimmer** [comment]
Fixed by https://github.com/Yoast/YoastSEO.js/pull/643
