### ISSUE TITLE
An error occured in the 'sentenceBeginnings' assessment

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#633]
### What did you expect to happen?
No error to occur

### What happened instead?
An error occurred
![schermafbeelding 2016-06-08 om 09 03 52](https://cloud.githubusercontent.com/assets/17744553/15885536/2167e704-2d58-11e6-8fe9-1b3ad45c6d30.png)
![schermafbeelding 2016-06-08 om 09 04 04](https://cloud.githubusercontent.com/assets/17744553/15885537/2341f006-2d58-11e6-9323-ce5a19a05e93.png)

### How can we reproduce this behavior?
Write the text from the image and look at the sentenceBeginning bullet in the content assessor.

### Technical info
* Platform: WordPress
* Platform version: 4.5.2
* Yoast SEO version: trunk

**Comment by atimmer** [comment]
This is fixed in 1.4, relevant PR: https://github.com/Yoast/YoastSEO.js/pull/792
