### ISSUE TITLE
Transition word assessor matches non-transition word uses of several transition words

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#636]
### What did you expect to happen?

The transition word assessor to only match transition word uses of 'first, 'second' etc.
### What happened instead?

![schermafbeelding 2016-06-08 om 10 00 19](https://cloud.githubusercontent.com/assets/17744553/15886968/ede21e1a-2d5f-11e6-9b80-14bbf6a6634a.png)
It marks non-transition word uses of 'first, 'second' etc.
### How can we reproduce this behavior?

Write a sentence containing 'first division' or any other use of  'first, 'second' etc. that isn't a transition word.
### Possible solution

We should think of a way to only match 'first', 'second', 'third', ... only if at is at the beginning of a sentence, because only at the beginning of a sentence these word are most likely a transition word.
### Technical info
- Platform: WordPress
- Platform version: 4.5.2
- Yoast SEO version: trunk

**Comment by IreneStr** [comment]
The same goes for 'as' in sentences like 'The property of the commune, it has been listed since 1926 **as** a monument historique by the French Ministry of Culture.'

**Comment by IreneStr** [comment]
We also have to think about what to do with 'too' in order for it to be not marked in sentences like "his notes are helpful and not *too numerous*, and his laborious task has been performed with an unusual blend of scholarship and modesty"
'Too' only at the end of sentences?

**Comment by IreneStr** [comment]
Same problem: 'overall'

> The senator’s defiant remarks came after Clinton effectively declared victory in her overall battle against Sanders at a rally in New York.

**Comment by Djennez** [comment]
This issue is still reproducible as of Yoast 9.7.

**Comment by IreneStr** [comment]
Labeled as wontfix (for now) because this requires a level of context awareness in the analysis which we are not even close to.
