### ISSUE TITLE
Text in code tags should not be highlighted

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/YoastSEO.js#638]
# Problem description

I've created a text with just one sentence that contains a transition word. This sentence is wrapped in `code` tags. It is properly analyzed, but highlighting it doesn't seem to work.
# Example

![add_new_post_ _clean_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/15889091/fb51e800-2d69-11e6-803b-571cf891c893.png)
_Sentence isn't highlighted_

![add_new_post_ _clean_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/15889139/32c40cfa-2d6a-11e6-8716-87d448c92ab4.png)
_Added another transition word to show that highlighting does work_
# Technical info

WordPress version: 4.5.2
Yoast SEO: 3.3-beta4

**Comment by atimmer** [comment]
This is probably on accident, but content in `<code>` tags should never be highlighted. The same goes for `<pre>` tags.

**Comment by jcomack** [comment]
Both `<code>` and `<pre>` tags are being highlighted 'properly' in the latest `develop` version.

Based on feedback from @atimmer, it was made known that we don't want to mark content between these tags (and possibly also others). However, to support this, the tokenizer needs to be refactored so we can pass along various properties to blacklist tokens from being highlighted.

Considering the impact of this, we'll probably have to wait for a future release. 

@jdevalk, what are your thoughts on this?

**Comment by doyler** [comment]
I did not want to make another issue regarding this topic, but I was wondering if this was still planned for a future release.

Like many others, I have a technical blog on WordPress (using Yoast), and my readability DROPS once I start adding in some pre or code tags.

**Comment by rmarcano** [comment]
We have received a similar request for another user with a technical blog using the WP-Syntax plugin. 
He is requesting that any code wrapped inside code tags be ignored for the readability analysis, for example: 
<pre lang="sas">
MY CODE HERE
</pre>

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 215237 when this conversation has been closed.

**Comment by gmmedia** [comment]
Something new about that problem?

**Comment by freewheelnat** [comment]
I have the same issue on my technical blog. I write some code tutorials posts and I always have a poor readability on them. I love your plugin, it's very useful on non code posts, so I would love it if the plugin would exclude text inside <pre> tags.

**Comment by igorschoester** [comment]
This issue was probably fixed for some time now 😄 

Retesting this in `Yoast SEO 9.6` shows it is fixed.
Tested in Chrome, both Gutenberg and classic editors.
