### ISSUE TITLE
Passive voice marker marks sentence without verbs

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#639]
### What did you expect to happen?
The passive voice marker to only mark sentences containing an auxiliary and -ed verb or irregular verb.

### What happened instead?
It marked a sentence without auxiliaries, -ed verbs and irregular verbs.
![schermafbeelding 2016-06-08 om 11 19 03](https://cloud.githubusercontent.com/assets/17744553/15889451/7cafda3c-2d6b-11e6-8039-6c88e25af2a5.png)
Is this the mark corresponding with the following sentence: Not to be confused with the inventor Frank Brian Mercer?

### How can we reproduce this behavior?
Copy paste this wikipedia page: https://en.wikipedia.org/wiki/Frank_Mercer and hit the passive voice marker button.

### Technical info
* Platform: WordPress
* Platform version: 4.5.2
* Yoast SEO version: trunk (beta4)

**Comment by atimmer** [comment]
Reevaluate once the sentence detection has been improved in other issues.

**Comment by terw-dan** [comment]
This is fixed with the improved sentence detection.
