### ISSUE TITLE
SentenceTooLong marks sentence containing 2 words

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#642]
### What did you expect to happen?
The sentenceTooLong assessments to only mark sentences containing 20+ words.

### What happened instead?
It marked a two-word sentence.
![schermafbeelding 2016-06-08 om 11 41 21](https://cloud.githubusercontent.com/assets/17744553/15890064/24294f62-2d6e-11e6-90cf-4df14d58c1e4.png)

### How can we reproduce this behavior?
Copy paste https://en.wikipedia.org/wiki/Frank_Mercer including the notes. Then hit the mark too long sentences button.

### Technical info
* Platform: WordPress
* Platform version: 4.5.2
* Yoast SEO version: trunk (beta4)

**Comment by atimmer** [comment]
Reevaluate once we have fixed the sentence detection in other issues.

**Comment by boblinthorst** [comment]
No longer an issue, fixed in 3.4.4 👍
