### ISSUE TITLE
Marker 'eyes' are turning themselves off

### ISSUE THREAD

**Issue by moorscode** [Yoast/YoastSEO.js#667]
### What did you expect to happen?
To see them selected when I don't do anything.

### What happened instead?
Click on a marker eye.
Wait for some time.
See it get deactivated.
Though the markings still appear in the editor.

### How can we reproduce this behavior?
Click on a marker, keep the console open so you can see the HTML is being modified (3-5 seconds) and after a second the marker will disappear.

### Technical info
* Platform: WordPress | Drupal | Standalone
* Platform version:
* Yoast SEO version: trunk

**Comment by atimmer** [comment]
Also see https://github.com/Yoast/wordpress-seo/issues/4806

**Comment by moorscode** [comment]
Duplicate
