### ISSUE TITLE
New/empty post doesn't show any explanation about the content tab

### ISSUE THREAD

**Issue by moorscode** [Yoast/YoastSEO.js#674]
### What did you expect to happen?
When there are no applicable checks there should be some explanation about what you are looking at or what you can expect to be happening.

### What happened instead?
![screen shot 2016-06-10 at 12 02 45](https://cloud.githubusercontent.com/assets/2005352/15961175/a2d61aa2-2f03-11e6-9c3b-f99ee920ceee.png)

### How can we reproduce this behavior?
Have a new/empty post/page.

### Technical info
* Platform: any
* Platform version:
* Yoast SEO version: trunk (@10 juni)

**Comment by atimmer** [comment]
Fixed by the new 'no content' assessment.
