### ISSUE TITLE
Localize text analysis

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/YoastSEO.js#68]
We've received reports that not all current checks may apply to every language/locale.

We received the following example for Hebrew;

> almost all prepositions such as "to", "for" etc are attached to the noun itself in Hebrew. This makes them unrecognizable to Yoast SEO, and so it states that the keyword "isn't" there and makes recommendations based on it.

I'm sure there are more differences like this rendering certain checks unnecessary for specific locales or, the contrary, adding the need for specific checks for a specific locale. 

This is not an issue that can be fixed easily, as it does require knowledge of (how Google handles) each locale, but it might be a good place for the discussion on if/how we want to do this.

**Comment by terw-dan** [comment]
Since we now have a way to add assessments for different languages this issue can be closed. Specific language requirements have their own issues.
