### ISSUE TITLE
Snippet Preview title too close to line above

### ISSUE THREAD

**Issue by moorscode** [Yoast/YoastSEO.js#680]
The title has been moved up a bit in latest trunk.

![screen shot 2016-06-10 at 14 11 56](https://cloud.githubusercontent.com/assets/2005352/15963941/f665ea96-2f15-11e6-850f-ff86d12184fc.png)

Also the screen-reader-text reads: `Seo title preview:` instead of `SEO title preview`
https://github.com/Yoast/YoastSEO.js/blob/develop/js/snippetPreview.js#L368

**Comment by afercia** [comment]
Hm looks correctly aligned for me, latest trunk built CSS

<img width="960" alt="screen shot 2016-06-10 at 14 33 01" src="https://cloud.githubusercontent.com/assets/1682452/15964332/4c93c4ae-2f18-11e6-852f-154b8a51ae94.png">
