### ISSUE TITLE
Sentence detection does not split in case of a point directly followed by a <strong> tag

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#687]
### What did you expect to happen?

The sentence detection to split correctly, also when encountering a `<strong>` tag.
### What happened instead?

It did not spilt correctly.
![schermafbeelding 2016-06-10 om 15 57 14](https://cloud.githubusercontent.com/assets/17744553/15966574/0bbe7f8a-2f24-11e6-9653-e789ae933273.png)
### How can we reproduce this behavior?

Hit the mark too long sentences button when using this text:
`You need to find your special niche and write great content about that niche on your food blog to surface on page one in Google. <strong>This is really hard.</strong>`
### Technical info
- Platform: WordPress
- Platform version: 4.5.2
- Yoast SEO version: trunk (3.3 beta4)

**Comment by Djennez** [comment]
This does not seem to be an issue any longer, can't reproduce in either Gutenberg or Classic editor.
