### ISSUE TITLE
'Linking to Another Page' Warning When Using Page Sections

### ISSUE THREAD

**Issue by amboutwe** [Yoast/YoastSEO.js#690]
### What did you expect to happen?

No warning message when the link is to a section within the same page.
### What happened instead?

Warning message: 'You're linking to another page with the focus keyword'
### How can we reproduce this behavior?
1. Create a post with the sample text below.
2. Replace `ADD-LINK-HERE` with a link to a section within the same post like `http://example.com/my-fantastic-post/#section`
3. Enter focus keyword 'sit'.
4. Warning appears.
### Technical info
- Platform: WordPress
- Platform version: 4.5.2
- Yoast SEO version: 3.2.5

**Sample Text**
`Lorem ipsum dolor <a href="ADD-LINK-HERE">sit</a> amet, consectetur adipiscing elit.`

**Comment by atimmer** [comment]
This is fixed in 1.4. Relevant PR: https://github.com/Yoast/YoastSEO.js/pull/722

**Comment by Pcosta88** [comment]
Please re-open issue to fix a variation as the full URL is fixed but not if the internal link is just for a #section 

![textjump](https://cloud.githubusercontent.com/assets/8238074/17420405/6d519fda-5a70-11e6-91d2-db0195f258b8.jpg)

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 137550 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 470751 when this conversation has been closed.

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 521934 when this conversation has been closed.

**Comment by monbauza** [comment]
In Yoast SEO v11.7, if the section link includes an absolute URL, the "_You're linking to another page with the words you want this page to rank for_" warning isn't triggered. See examples below.
- `<a href="#section">link to section</a>` triggers the warning
- `<a href="http://example.com/my-fantastic-post/#section">link to section</a>` does NOT trigger the warning

**Comment by monbauza** [comment]
Please inform the customer of conversation # 527936 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 587639 when this conversation has been closed.
