### ISSUE TITLE
Add abbreviation exceptions to sentence detection

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#698]
We should make a list of abbreviations that serve as exceptions in the sentence detection to avoid incorrect sentence splitting. 

The sentence detection can already handle abbreviations that are followed by lowercase:
![schermafbeelding 2016-06-13 om 09 48 02](https://cloud.githubusercontent.com/assets/17744553/16000322/042b03ea-314c-11e6-8e6c-9b86a0448b5c.png)

But the sentence detection fails when abbreviations are followed by uppercase:
![schermafbeelding 2016-06-13 om 09 43 52](https://cloud.githubusercontent.com/assets/17744553/16000266/98711a40-314b-11e6-9657-8b693aa0b9aa.png)

We already used a list of abbreviations in an early version of the passive voice assessment. We could use this list, and, if necessary, expand on this list:

A.D.
Adm.
Adv.
B.C.
Br.
Brig.
Cmrd.
Col.
Cpl.
Cpt.
D.
Dr.
Esq.
Fr.
Gen.
Gov.
Hon.
Jr.
Lieut.
Lt.
Maj.
Mr.
Mrs.
Ms.
Msgr.
Mx.
Pfc.
Pr.
Prof.
Pvt.
Rep.
Reps.
Rev.
Rt. Hon.
Sen.
Sens.
Sgt.
Sps.
Sr.
St.
vs.
i.e.
e.g.
viz.
Mt.

**Comment by IreneStr** [comment]
We should also add time zone abbreviations:
![schermafbeelding 2016-07-12 om 15 43 14](https://cloud.githubusercontent.com/assets/17744553/16769103/71e54398-4847-11e6-9db4-010dc5e0bb3d.png)

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 562526 when this conversation has been closed.
