### ISSUE TITLE
Textual enhancements and typo fixes

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/YoastSEO.js#699]
# Remove indefinite article
* [x] [passiveVoiceAssessment.js line 50](https://github.com/Yoast/YoastSEO.js/blob/develop/js/assessments/passiveVoiceAssessment.js#L50) contains to `... contains a passive voice ...`. Since `passive voice` is not quantifiable, the indefinite article is not required. So the sentence should be changed to ` ... contains passive voice ...`.
* [x] [passiveVoiceAssessment.js line 68](https://github.com/Yoast/YoastSEO.js/blob/develop/js/assessments/passiveVoiceAssessment.js#L68) contains to `... contains a passive voice ...`. Since `passive voice` is not quantifiable, the indefinite article is not required. So the sentence should be changed to ` ... contains passive voice ...`.

# Fix singular/plural
A couple of strings are untranslatable because they seem to contain two singular/plural combinations. This can be solved by clearly indicating which variable is responsible for singular/plural and fixing the other.
* [x] [textLengthAssessment.js line 16 - 18](https://github.com/Yoast/YoastSEO.js/blob/develop/js/assessments/textLengthAssessment.js#L16-18)
* [x] [textLengthAssessment.js line 29 - 31](https://github.com/Yoast/YoastSEO.js/blob/develop/js/assessments/textLengthAssessment.js#L29-31)
* [x] [taxonomyTextLengthAssessment.js line 16 - 18](https://github.com/Yoast/YoastSEO.js/blob/49e9cc3d67dc1a74e8df0580521633181d983206/js/assessments/taxonomyTextLengthAssessment.js#L16-18)
* [x] [taxonomyTextLengthAssessment.js line 29 - 31](https://github.com/Yoast/YoastSEO.js/blob/49e9cc3d67dc1a74e8df0580521633181d983206/js/assessments/taxonomyTextLengthAssessment.js#L29-31)
* [x] [taxonomyTextLengthAssessment.js line 42 - 44](https://github.com/Yoast/YoastSEO.js/blob/49e9cc3d67dc1a74e8df0580521633181d983206/js/assessments/taxonomyTextLengthAssessment.js#L42-44)
* [x] [taxonomyTextLengthAssessment.js line 55 - 57](https://github.com/Yoast/YoastSEO.js/blob/49e9cc3d67dc1a74e8df0580521633181d983206/js/assessments/taxonomyTextLengthAssessment.js#L55-57)
* [x] [titleLengthAssessment.js line 20 - 25](https://github.com/Yoast/YoastSEO.js/blob/49e9cc3d67dc1a74e8df0580521633181d983206/js/assessments/titleLengthAssessment.js#L20-25)
* [x] [titleLengthAssessment.js line 37 - 38](https://github.com/Yoast/YoastSEO.js/blob/49e9cc3d67dc1a74e8df0580521633181d983206/js/assessments/titleLengthAssessment.js#L37-38)
* [x] [titleLengthAssessment.js line 49 - 54](https://github.com/Yoast/YoastSEO.js/blob/49e9cc3d67dc1a74e8df0580521633181d983206/js/assessments/titleLengthAssessment.js#L49-54)
* [x] [textLengthAssessment.js line 42 - 46](https://github.com/Yoast/YoastSEO.js/blob/develop/js/assessments/textLengthAssessment.js#L42-46)
* [x] [subheadingDistributionTooShortAssessment.js line 56 - 63](https://github.com/Yoast/YoastSEO.js/blob/49e9cc3d67dc1a74e8df0580521633181d983206/js/assessments/subheadingDistributionTooShortAssessment.js#L56-63)
* [x] [transitionWordsAssessment.js line 46 - 63](https://github.com/Yoast/YoastSEO.js/blob/06c5633ce2f88cd0084ac934b9f6f44cc2519f3c/js/assessments/transitionWordsAssessment.js#L46)
* [x] [paragraphTooShortAssessment.js line 46 - 50](https://github.com/Yoast/YoastSEO.js/blob/e5a3e0e7228bb835348c67de728d3a4d20baf248/js/assessments/paragraphTooShortAssessment.js#L46-50)

  
## Example
Current lines: 
```php
/* Translators: %1$d expands to the number of words in the text, %2$s to the recommended minimum of words */
"The text contains %1$d word, which is slightly below the recommended minimum of %2$d word. Add a bit more copy.",
"The text contains %1$d words, which is slightly below the recommended minimum of %2$d words. Add a bit more copy.",
```

To solve this problem for most languages, the easiest fix is to simply change `%2$d word` into `%2$s words`. That solution would be invalid for some languages, as they handle singular/plural differently. But to do a quick fix, the string could be changed to:
```php
/* Translators: %1$d expands to the number of words in the text (used for singular/plural), %2$s to the recommended minimum of words (always >1) */
"The text contains %1$d word, which is slightly below the recommended minimum of %2$d words. Add a bit more copy.",
"The text contains %1$d words, which is slightly below the recommended minimum of %2$d words. Add a bit more copy.",
```

A better solution would be to turn this into two separate sentences that both can be singular/plural. This would work in every language. Example of the resulting plural sentences:
`The text contains %1$d words.` and 
`This is slightly below the recommended minimum of %2$d words. Add a bit more copy.`

# Technical info
* Platform: WordPress
* Platform version: 4.5.2
* Yoast SEO version: 3.3-beta5

**Comment by IreneStr** [comment]
@tacoverdo I am not sure it's the case for every assessment, but in the example I think the second singular/plural difference could be removed altogether. I don't think we would ever set the recommended minimum to 1 word.

**Comment by tacoverdo** [comment]
@IreneStr [Some languages](https://github.com/GlotPress/GlotPress-WP/blob/develop/locales/locales.php) use singular not just for 1, but also for 21, 31 etc. 
So for those languages you would still need singular/plural, even if the value never is 1.
