### ISSUE TITLE
Avoid "covert" transliteration defaults

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#700]
As stated in #483, we do not want default transliterations. However, en_US is used as default locale in YoastSEO.js/js/values/Paper.js, meaning that if this is not overwritten, the en_US transliterations are used.
Is there a way to fix this?

**Comment by atimmer** [comment]
Not having default transliterations is a consideration in the context of a separate transliterations module. YoastSEO.js always has a locale and the default is en_US, with the default en_US transliterations. See https://github.com/Yoast/YoastSEO.js/issues/797 for moving transliterations to a separate module.
