### ISSUE TITLE
Empty sentences can trigger NaN%

### ISSUE THREAD

**Issue by terw-dan** [Yoast/YoastSEO.js#702]
### What did you expect to happen?

The percentage set to 0% in stead of NaN% in assessment result texts.
### What happened instead?

NaN% in stead of 0%.
### How can we reproduce this behavior?

Use a couple of  spaces as content. Then this happens. 
![image](https://cloud.githubusercontent.com/assets/11272096/16001577/19a8baee-3153-11e6-9f5e-2f38ffbdae8b.png)
### Technical info
- Platform: Standalone
- Yoast SEO version: 3.3 develop

**Comment by Djennez** [comment]
Non-existent anymore. Presumably fixed with https://github.com/Yoast/YoastSEO.js/pull/822

Closing thread.
