### ISSUE TITLE
Double spacing makes transitional words unnoticed.

### ISSUE THREAD

**Issue by boblinthorst** [Yoast/YoastSEO.js#713]
### What did you expect to happen?
double spacing to not be considered when checking texts.

### What happened instead?
double spacing causes the transitional word 'than'  to be unnoticed.
this sentence for example:
I seem to have less  than the requested amount of transitional words.

__with double spacing__
![than_double_spaced](https://cloud.githubusercontent.com/assets/11849359/16039796/394fd664-322c-11e6-81e3-07aec0fd5397.png)

__without double spacing__

![than_not_double_spaced](https://cloud.githubusercontent.com/assets/11849359/16039800/3d251ba0-322c-11e6-8fb6-61d2b831eda1.png)

### Technical info
* Platform: WordPress
* Platform version: 4.4.3
* Yoast SEO version: right before release of 3.3

**Comment by atimmer** [comment]
This wasn't actually an issue with the double space, but rather an issue with the non-break space character that was before `than`. Nevertheless we can fix that as well, so see #764 for that.
