### ISSUE TITLE
Remove partial sentences in translatable text strings in titleLengthAssessment.js

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#718]
Like @tacoverdo wrote in https://github.com/Yoast/YoastSEO.js/pull/706/files , translatable text strings should be full sentences, not partial sentences.

js/assessments/titleLengthAssessment.js contains two partial sentences. We should fix that.

**Comment by terw-dan** [comment]
The title lenght assessment is replaced with the title width assessment that doesn't used combined
