### ISSUE TITLE
Slug preview box is not saving for older posts

### ISSUE THREAD

**Issue by cmunns** [Yoast/YoastSEO.js#723]
### What did you expect to happen?

Let me first say that on new products (created after more recent plugin updates are not affected by this problem). The problem is that on older posts the snippet preview slug is empty and will not save. 
### What happened instead?

The primary problem with this is that if anyone tries to edit any part of the snippet description and/or slug the javascript will replace the already saved slug value and replace it with an null value which on-save will generate the slug as the post-title.
### How can we reproduce this behavior?

Not sure how to reproduce but here is a video of the behavior.
http://recordit.co/FCcQmhqh7E
### Technical info
- Platform: WordPress | Drupal | Standalone
  WP 
- Platform version:
  4.5.2
- Yoast SEO version:
  3.3.1
- Potential Plugin Conflict
  Perfect SEO URL https://www.perfectseourl.com/support/compatibility/is-yoast-seo-supported/
  Problem seems to be resolved when I deactivate the plugin, but considering this seems like a javascript issue I'm reporting it here first as that plugin doesn't have any javascript 

### Update

I have noticed this problem only persists when there is a category or in this case product_cat selected for the given post/product. Once a category is chosen the permalink looks visibly different and I'm assuming that perhaps the yoast-scraper-js ceases to function at this time ?

**Comment by cmunns** [comment]
@atimmer Was there ever a status update on this? I am still having this issue and now it actually crops up and both older and new posts.

**Comment by cmunns** [comment]
I've discovered that the div below is missing when Perfect SEO URL is active. Anyway you guys can use the actual slug meta box when scraping for the snippet preview ?
`<span id="editable-post-name”>foo bar</span>/</a></span>`

**Comment by cmunns** [comment]
@atimmer Was curious if you ever updated anything based on my provided report and feedback ?

**Comment by Djennez** [comment]
Hi @cmunns and apologies for never sending a reaction your way.

The issue you are describing seems very specific and not easily reproduceable. If this issue is still relevant for you, would you mind checking the browser console for javascript errors?

**Comment by Djennez** [comment]
This thread will be closed due to inactivity.

If information was requested from the creator of this issue, please add that to this thread and we will look into reopening this.

If you have a similar issue, [follow this link to open a new bug report](http://kb.yoast.com/article/180-how-to-write-a-good-bug-report).
