### ISSUE TITLE
Finnish conjugation

### ISSUE THREAD

**Issue by atimmer** [Yoast/YoastSEO.js#747]
Finish has something called [conjugation](https://en.wikipedia.org/wiki/Finnish_verb_conjugation) which means that the same word has a different spelling based on the other parts of the sentence it is in.

At DrupalJam I briefly spoke with [Mikko Hämäläinen](https://www.linkedin.com/in/mikkohamalainen) and he promised me to send a tool that can work with these conjugations. He sent me the following message:

> (...) here are few I've found: 
> 
> http://www2.lingsoft.fi/cgi-bin/fintwol?word=koirillannekaan
> 
> This is a demo of a proprietary library. It seems to be very good at what it does, which is basically, finding the base form of a conjugated word. The example "koirillennekaan" means "(give or do sth to) not-also-to-your-dogs", so it combines ownership, negation, relation to other dogs with the basic form of the word dog. I would imagine this being useful, but unfortunately, using it probably costs money.  
> 
> http://bisqwit.iki.fi/source/formo.html
> This is a GPL licensed cmd line tool that can conjugate words. I haven't tried that myself, but might be very useful as the source is freely available. You can check it out and when/if adding Finnish language tools to Yoast becomes relevant, just copy the good parts and covert them to JS/PHP whatever you're using :)

So this might be a nice start if we start adding Finnish support.

**Comment by omarreiss** [comment]
Nice context. I'm sure our linguists will find when we ever pickup finnish.
