### ISSUE TITLE
Too many decimals for Sentences contain more than 20 words check

### ISSUE THREAD

**Issue by PatrickYoast** [Yoast/YoastSEO.js#756]
### What did you expect to happen?
That the check shows only 1 decimal

### What happened instead?
Instead of 26.3% I got 26.31578947368421%

### How can we reproduce this behavior?
Enter in any paragraph in de content analysis on https://yoast.com/research/real-time-content-analysis/

### Technical info
* Platform: Standalone
* Platform version: -
* Yoast SEO version: -

**Comment by atimmer** [comment]
This was an issue with cache on https://yoast.com/research/real-time-content-analysis/.
