### ISSUE TITLE
getWords does return empty strings

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#763]
getWords should not return empty strings, but it does.

To reproduce: enter ' , ' in getWords.

**Comment by IreneStr** [comment]
After this fix, add

```
	it( "returns an object with English sentence beginnings in lists", function() {
		var mockPaper = new Paper( " , " );
		expect( sentenceBeginnings( mockPaper )).toEqual( [] );
	});
```

to getSentenceBeginningsSpec.js

**Comment by terw-dan** [comment]
The tokenizer will not see an individual `,` as a sentence, unless it is the only character. Therefore it will not break the sentencebeginnings.
