### ISSUE TITLE
Custom fields implementation

### ISSUE THREAD

**Issue by Petervw** [Yoast/YoastSEO.js#78]
## Functionality:
As a user of the blog posts section in WordPress, I want to use custom fields in the page analysis tool. The page analysis tool should use the fields in the scanning process to determine the content value.

## UI:
The page analysis should be analysed when the user is done with typing in one of the input fields. After that, we should trigger the custom field analysis and "on finish" update the results in the page analysis scoring page.

## Integration & Data management:
To resolve this issue, we have a few scenario’s which could be used. After our discussion, we think Scenario 6 is our best case.

### Scenario 1:
Load all short codes on page load.

##### Pros:
 - Everything is on the page available when we need it.

##### Cons:
 - The page load time is very slow.

### Scenario 2:
Pre-load on page in user memory.

##### Pros:
 - Faster page load then Scenario 1.
 - Bottlenecks are traceable
 - Everything is loaded when we need it on the page.

##### Cons:
 - Possible client side memory issue.

### Scenario 3:
Dynamic fetch (async).

##### Pros:
 - We don't have to preload everything
 - There isn't much stored on the client side

##### Cons:
 - Unpredictable
 - Timing issues

### Scenario 4:
Scenario 2 + reload functionality

##### Pros:
 - We have more up-to-date data

##### Cons:
 - Same as Scenario 2

### Scenario 5:
Build our own short code integration.

##### Pros:
 - Other plugin developers don't have to change a lot in their plugins.

##### Cons:
 - We need to centralize all short codes

### Scenario 6:
Local storage for all (rendered) short codes. This scenario includes a hash verifier to detect updates.

##### Pros:
 - Very fast storing mechanism for clients

##### Cons:
 - We need to hash the local storage and verify it with our hash to detect updates

**Comment by monecchi** [comment]
+1 for a custom fields implementation. I've got a lot of data which would be taken into account if custom fields were scrapped too.
