### ISSUE TITLE
HTML character &#8217; is viewed as a sentence terminator

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#780]
### What happened?

The HTML character `&#8217;` is viewed as a sentence terminator (probably because of the semicolon).
### How can we reproduce this behavior?

Mark passive voice using this sentence:
`When our first child was only about six months old, I knew my second child would be close to my first but we didn&#8217;t have enough money to do another adoption for  a while so we thought we better get started doing infertility treatments again.`

**Comment by IreneStr** [comment]
This is also relevant for special characters/diacritics: `Werksk&#252;chen` -->Werksküchen

**Comment by IreneStr** [comment]
Also `&#8211;`  -->  dash &#8211;

**Comment by atimmer** [comment]
We can probably fix this by adding HTML entities to the tokenizer. As in: Adding `&#\d+;` as a token in the tokenizer in `html.js`.

**Comment by terw-dan** [comment]
Please use this branch when fixing this issue: 
https://github.com/Yoast/YoastSEO.js/tree/issue780-html-sentence-terminator

**Comment by Djennez** [comment]
This issue seems to have been fixed in the meantime. Closing this thread.
