### ISSUE TITLE
Focus keyword with special character (such as apostrophe) gives SEO messages

### ISSUE THREAD

**Issue by CarolineGeven** [Yoast/YoastSEO.js#860]
When I have a focus keyword that contains a special character, such as an apostrophe `'` and the post gets saved, the focus keyword is stripped of the apostrophe, giving a warning that the focus keyword cannot be found anywhere.

Example:
Focus keyword contains the word: `foto's`
In the text, title and meta description, the word `foto's` is present. While writing the post upon first draft, the focus keyword gets counted correctly.
After saving the post and returning, the focus keyword field has stripped the apostrophe, making the focus keyword `fotos`, while the rest of the text stays the same. This causes at least the following messages to pop up, making a post that has a score of 'good' go to 'OK'.
>> The focus keyword does not appear in the SEO title.
>> A meta description has been specified, but does not contain the focus keyword.
>> The focus keyword density is 0%

When you use the focus keyword in your alt attributes, h2 and first alinea, those warnings will popup as well.

* Platform: WordPress
* Platform version: 4.5.3
* Yoast SEO version: 3.4.1

**Comment by zenichanin** [comment]
I just noticed this issue in the latest version too.  Why does it strip out characters out of focus keywords? It's not unreasonable to want the focus keyword to have an apostrophe.
