### ISSUE TITLE
Readability issue with NextGEN Gallery

### ISSUE THREAD

**Issue by benvaassen** [Yoast/YoastSEO.js#869]
## What did you expect to happen?

I expect to see highlighted text to appear. 

After pressing here: 
![edit_post_ _local_wordpress_ _wordpress](https://cloud.githubusercontent.com/assets/11910661/17661922/656117fe-62e2-11e6-8145-874bbd61a744.png)

I expect to see: 
![edit_post_ _local_wordpress_ _wordpress](https://cloud.githubusercontent.com/assets/11910661/17661880/22b7d104-62e2-11e6-9782-4ec42c9773f1.png)
## What happened instead?

The eye becomes pink, but it does not highlight any word or sentence and it doesn't produce any error message or javascript error.
![edit_post_ _local_wordpress_ _wordpress](https://cloud.githubusercontent.com/assets/11910661/17662048/223dbefe-62e3-11e6-8d43-f1e699102385.png)
## How can we reproduce this behavior?

Activate both Yoast SEO (or Premium) and NextGen Gallery, edit a post and press on the eye to mark the result in the text. 
## Technical info
- Platform: WordPress
- Platform version: 4.5.3
- Yoast SEO version: 3.4.2
- NextGEN Gallery: 2.1.49

**Comment by benvaassen** [comment]
Please inform the customer of conversation # 141092 when this conversation has been closed

**Comment by CarolineGeven** [comment]
Closing as this is not relevant anymore.
