### ISSUE TITLE
Bold individual words in snippet preview

### ISSUE THREAD

**Issue by jdevalk** [Yoast/YoastSEO.js#882]
## What did you expect to happen?

I expected the individual words in my focus keyword to be bolded in the snippet, as Google does. Search, for instance, for `snippet preview Yoast`. You'll see the words are highlighted, even when they appear separately.
## What happened instead?

Only an entire occurrence of the "phrase" was bolded, not the individual words.
## How can we reproduce this behavior?

See above.
## Technical info
- Platform: All
- Platform version: Latest
- Yoast SEO version: 3.4

**Comment by IreneStr** [comment]
When solving this issue, please use the following branch: 
https://github.com/Yoast/YoastSEO.js/tree/issue882-bold-individual-words

**Comment by jdevalk** [comment]
This has already been fixed.
