### ISSUE TITLE
Keyword is not found when there is a space after the focus keyword input

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#897]
## What did you expect to happen?

The focus keyword to be found regardless of the presence of a space after it in the focus keyword input field. 
## What happened instead?

Without a space after the focus keyword in the input field, the keyword was matched and counted. However, when I added a space after the focus keyword in the input field, the keyword density dropped to 0%. 
## How can we reproduce this behavior?

Write a text, chose a focus keyword, put the focus keyword in the input field followed by a space.
## Technical info
- Platform: Standalone
- Yoast SEO version: develop

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/YoastSEO.js/issues/1167

**Comment by Pcosta88** [comment]
**1.Add some lorem and the focus keyword**

![screen_shot_2017-10-04_at_4_39_30_pm](https://user-images.githubusercontent.com/8238074/31199238-c195d4ae-a924-11e7-9b72-31be016dc04b.png)

2.Enter Keyword without a space at end, see it output the right statement

![screen shot 2017-10-04 at 4 54 23 pm](https://user-images.githubusercontent.com/8238074/31199259-d0ae3eb8-a924-11e7-82e9-f9dddd19b6fc.png)

3.Add a space at the end and see it change to an incorrect statement

![screen shot 2017-10-04 at 4 54 31 pm](https://user-images.githubusercontent.com/8238074/31199273-d90b6284-a924-11e7-8502-f74fc8f8d5a5.png)

Tech Specs
WP: 4.8.2
Yoast: 5.5.1

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 236353 when this conversation has been closed.

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 271507 when this conversation has been closed.

**Comment by suascat** [comment]
Please inform the customer of conversation # 314418 when this conversation has been closed.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 314418 when this conversation has been closed.

**Comment by IreneStr** [comment]
This has been fixed around the time morphology was introduced (9.0, Oct 23).
