### ISSUE TITLE
Focus keyword does not match different quotation marks

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#898]
## What did you expect to happen?

The focus keyword to match regardless of the type of quotation marks that is used in the text and focus keyword.
## What happened instead?

The keyword does not match if the keyword in the text and the keyword in the keyword input field differ in the type of quotation mark used.
## How can we reproduce this behavior?

Use this text:
`So far, you’ve got physical relaxation, which diminishes stress, reduced judgment, allowing you to talk and behave however you want, and stimulation of the brain’s reward system, which makes you feel like something nice is about to happen. But the fourth neurotransmitter tops the bill: opioids. Sometimes called endorphins or internal opiates, they get released by alcohol too. Everyone knows that opiates feel good, but did you know that you can get your opiates legally by downing a stiff drink? The American martini – which consists of three ounces of gin and little else – feels particularly nice for a very simple reason. The faster the alcohol goes in, the more internal opiates get released. Hence the aaaaahhhhh.`

Use this as focus keyword (literally, with this exact quotation mark): `brain's reward system`

The keyword density is 0% instead of 0,9%.
## Technical info
- Platform: Standalone
- Yoast SEO version: develop

**Comment by atimmer** [comment]
This has a PR, so we should either merge or close the PR.
