### ISSUE TITLE
Sassdash dependency

### ISSUE THREAD

**Issue by alxy** [Yoast/YoastSEO.js#902]
Hello,

I have a question regarding the ``sassdash`` dependency: https://github.com/Yoast/YoastSEO.js/blob/develop/package.json#L43

Why is it a devDependency? In the SCSS files it is included ( https://github.com/Yoast/YoastSEO.js/blob/develop/css/analyzer.scss#L1 ), thats why building the css failed for me first. Shouldnt this be a regular dependeny? Or how are the scss files meant to be compiled?

edit// I use node/gulp and pulled this package in as dependency.

**Comment by atimmer** [comment]
@alxy Thank you for noticing this. Yes, sassdash should be a normal dependency.
