### ISSUE TITLE
Improve regex for keyword matching

### ISSUE THREAD

**Issue by terw-dan** [Yoast/YoastSEO.js#944]
Currently we add wordboundaries to the keyword, because using `/b` is not possible because it doesn't capture all wordboundaries, or sees some characters as wordboundaries (this occurs especially with non-latin texts). 

The downside of this is that the wordboundaries are always captured with the keyword. 
In the sentence `this is a very beautiful keyword I have` if we cant to capture the word `keyword` it will actually capture ` keyword ` (including the spaces). 

This has 2 consequences; 
In the phrase `keyword keyword keyword` it only matches twice. The 2nd occurrence of `keyword` isn't captured, since the space in front of it is already captured by the first keyword. 

When highlighting the keyword in the snippet, we add <strong>-tags around the highlighted keyword, but it will also include the spaces, so it will be something like `<strong> keyword </strong>` instead of `<strong>keyword</strong>`. 
It would be nice if we can improve this. 

## How can we reproduce this behavior?
Look at the HTML in the snippet preview when a word is highlighted, this is the most visible place, but it occurs everywhere. 

## Technical info

* Platform: Standalone
* Yoast SEO version: 3.8

**Comment by atimmer** [comment]
Closing in favor of https://github.com/Yoast/YoastSEO.js/issues/1348
