### ISSUE TITLE
Organize assessments based on locales instead of languages

### ISSUE THREAD

**Issue by andizer** [Yoast/YoastSEO.js#948]
We might consider the organization of the language specific assessments in locale based directories instead of language directories.
At the moment we are looking to the locale which will be mapped to a config directory. For example: when the locale starts with `en` where will use the `english` directory and for `de` it will be `german`. 
It might be better to use `en` as the directory name, because the translation for locale to config isn't needed anymore in that case.

**Comment by omarreiss** [comment]
Good idea. But seems to have functioned "fine" for years. So closing as wontfix.
