### ISSUE TITLE
Quotation mark causes incorrect sentence detection

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#956]
The following text is regarded as one sentence: 
`Denn sie bekommen dann eine Zulage von 100 Prozent.“ Es funktioniert. `

Complete text fragment: 
`„Zumal ich von Frau Vogell vom Kaufhof gehört habe, dass sie sich vor Bereitschaft ihrer Mitarbeiter nicht retten kann, am verkaufsoffenen Sonntag zu arbeiten. Denn sie bekommen dann eine Zulage von 100 Prozent.“ Es funktioniert.`

## How can we reproduce this behavior?
Paste the above text to the standalone, log the sentences.

* Platform: Standalone browserified
* Yoast SEO version: develop

**Comment by terw-dan** [comment]
When fixing this issue, please use this branch: https://github.com/Yoast/YoastSEO.js/tree/issue956-sentence-detection

**Comment by manuelaugustin** [comment]
See also #871
