### ISSUE TITLE
Review the scoring for German now we have all assessments

### ISSUE THREAD

**Issue by terw-dan** [Yoast/YoastSEO.js#990]
The scoring for German and English should be the same now we run the same assessments. 

In calculating penalty points in the contentAssessor, we rate languages English different from German. 
With all assessments now being able to run in German, we should review this, so German doesn't get a heavier penalty then English. 
See: https://github.com/Yoast/wordpress-seo/issues/6286

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 162754 when this conversation has been closed.
