### ISSUE TITLE
Improve the first paragraph keyword matching. 

### ISSUE THREAD

**Issue by terw-dan** [Yoast/YoastSEO.js#994]
When checking for keywords in the first paragraph, we should do a better check to see what is in the first paragraph. 
If a paragraph has no text, but only an image, we should skip this and check the next paragraph. 

This is easily reproduced by creating a text, starting with an image, and a piece of text containing the keyword. It will now recognize the keyword. 
Add a couple of enters after the image. The image is now seen as a seperate paragraph, and it won't recognize the keyword in the first paragraph. 

This issue was reported in earlier versions of the plugin.
https://github.com/Yoast/wordpress-seo/issues/4091

## Technical info

* Platform: WordPress
* Platform version: 4.7
* Yoast SEO version: 4.0.2

**Comment by Pcosta88** [comment]
Please inform the customer of conversation #156705 when this conversation has been closed.

**Comment by benvaassen** [comment]
Please inform the customer of conversation # 172689 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 175675 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 369375 when this conversation has been closed.

**Comment by michaelbriantina** [comment]
Please inform the customer of conversation # 387866 when this conversation has been closed.

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/YoastSEO.js/issues/985

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/YoastSEO.js/issues/1064

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/wordpress-seo/issues/7960

**Comment by ahamaton** [comment]
I think I have found a very simple solution but you may want to build a default setting in to the platform so that people dont need to figure this out.  I havent tested it loads but I have found that if you simply left align the text it adds the p tags and they stay there after you save.  Then yoast recognises the words in the first paragraph.  As I say I havent tested it loads so I might be wrong but it looks hopeful to me

**Comment by iamazik** [comment]
Please inform the customer of conversation # 401471 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 409419 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 410441 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 414465 when this conversation has been closed.

**Comment by manuelaugustin** [comment]
The fix for this issue was merged into a feature branch which won't be included in the next release. We expect the fix to be included in 8.4.
