### ISSUE TITLE
Improve textstrings for image alt tags assessment. 

### ISSUE THREAD

**Issue by terw-dan** [Yoast/YoastSEO.js#995]
# Problem description

When having just one image, which doesn't have an alt attribute, on a page, the Yoast SEO analysis reports the following:
`The images on this page are missing alt attributes.`
With just one image on the page, this shouldn't be plural.
# Example

![add_new_post_ _wpbeta_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/16916161/c037d1ce-4cfb-11e6-9775-735fc708dbfb.png)
# Possible solution

Simply using a single/plural form based on the total wouldn't make sense. 

If there are multiple images, but only 1 has an alt-tag, we report `The images on this page contain alt attributes with the focus keyword.`, but that isn't technically correct. Because only 1 of the images has an alt-tag. 

When we change the strings to a plural/single form, we should take a look at this as well. Maybe change it to `1 out of 3 images` when there are multiple images, or somewhat simpler `not all images`.

This issue replaces: https://github.com/Yoast/wordpress-seo/issues/5197

**Comment by Djennez** [comment]
The current version of the plugin does not have this line anymore. A new, related line might be:

```Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!```

However, this line does not claim that there is but one image. It reads more as "at lease one" image is failing this check.
